#!/usr/bin/env python3
"""Expand CPT database with ~3,600+ new codes across multiple specialties."""
import json
import os

DB_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'cpt_database.json')

def make_cpt(code, desc, cat="Surgery", subcat=None, spec="general_surgery",
             rvu=5.0, glob=90, bilat=False, addon=False, cosurg=False,
             assist=True, tier=2, family="unclassified", inclusive=None,
             never_primary=None, modifiers=None, estimated=True):
    return {
        "code": str(code),
        "description": desc,
        "category": cat,
        "subcategory": subcat,
        "specialty": spec,
        "work_rvu": rvu,
        "global_period_days": glob,
        "bilateral_eligible": bilat,
        "addon_code": addon,
        "cosurgeon_eligible": cosurg,
        "assistant_allowed": assist,
        "hierarchy_tier": tier,
        "code_family": family,
        "inclusive_of": inclusive or [],
        "never_primary_with": never_primary or [],
        "typical_modifiers": modifiers or [],
        "estimated": estimated
    }

new_codes = {}

# ============================================================
# 1. ORTHOPEDIC (500+ codes)
# ============================================================

# Shoulder fracture treatment (23500-23630)
shoulder_fx = [
    ("23500", "Closed treatment of clavicular fracture without manipulation", 3.49),
    ("23505", "Closed treatment of clavicular fracture with manipulation", 5.22),
    ("23515", "Open treatment of clavicular fracture with internal fixation", 12.13),
    ("23520", "Closed treatment of sternoclavicular dislocation without manipulation", 3.09),
    ("23525", "Closed treatment of sternoclavicular dislocation with manipulation", 5.44),
    ("23530", "Open treatment of sternoclavicular dislocation", 10.44),
    ("23532", "Open treatment of sternoclavicular dislocation with fascial graft", 12.85),
    ("23540", "Closed treatment of acromioclavicular dislocation without manipulation", 2.67),
    ("23545", "Closed treatment of acromioclavicular dislocation with manipulation", 4.52),
    ("23550", "Open treatment of acromioclavicular dislocation, acute or chronic", 10.47),
    ("23552", "Open treatment of acromioclavicular dislocation with fascial graft", 12.53),
    ("23570", "Closed treatment of scapular fracture without manipulation", 2.55),
    ("23575", "Closed treatment of scapular fracture with manipulation", 4.89),
    ("23585", "Open treatment of scapular fracture with internal fixation", 14.22),
    ("23600", "Closed treatment of proximal humeral fracture without manipulation", 3.68),
    ("23605", "Closed treatment of proximal humeral fracture with manipulation", 6.92),
    ("23615", "Open treatment of proximal humeral fracture with internal fixation", 15.64),
    ("23616", "Open treatment of proximal humeral fracture with prosthetic replacement", 17.92),
    ("23620", "Closed treatment of greater humeral tuberosity fracture without manipulation", 3.22),
    ("23625", "Closed treatment of greater humeral tuberosity fracture with manipulation", 5.55),
    ("23630", "Open treatment of greater humeral tuberosity fracture", 11.47),
]
for code, desc, rvu in shoulder_fx:
    new_codes[code] = make_cpt(code, desc, spec="orthopedic_surgery", rvu=rvu, bilat=True, family="shoulder_fracture")

# Humerus shaft fractures (24500-24586)
humerus = [
    ("24500", "Closed treatment of humeral shaft fracture without manipulation", 3.56),
    ("24505", "Closed treatment of humeral shaft fracture with manipulation", 6.37),
    ("24515", "Open treatment of humeral shaft fracture with plate/screws", 14.89),
    ("24516", "Treatment of humeral shaft fracture with insertion of intramedullary implant", 14.23),
    ("24530", "Closed treatment of supracondylar or transcondylar humeral fracture without manipulation", 3.78),
    ("24535", "Closed treatment of supracondylar or transcondylar humeral fracture with manipulation", 7.22),
    ("24538", "Percutaneous skeletal fixation of supracondylar humeral fracture", 9.78),
    ("24545", "Open treatment of humeral supracondylar fracture with internal fixation", 15.67),
    ("24546", "Open treatment of humeral supracondylar fracture with intercondylar extension", 18.34),
    ("24560", "Closed treatment of humeral epicondylar fracture without manipulation", 2.89),
    ("24565", "Closed treatment of humeral epicondylar fracture with manipulation", 5.12),
    ("24566", "Percutaneous skeletal fixation of humeral epicondylar fracture", 8.45),
    ("24575", "Open treatment of humeral epicondylar fracture with internal fixation", 12.78),
    ("24576", "Closed treatment of humeral condylar fracture without manipulation", 3.44),
    ("24577", "Closed treatment of humeral condylar fracture with manipulation", 6.56),
    ("24579", "Open treatment of humeral condylar fracture with internal fixation", 15.23),
    ("24582", "Percutaneous skeletal fixation of humeral condylar fracture", 10.12),
    ("24586", "Open treatment of periarticular fracture of elbow with internal fixation", 16.89),
]
for code, desc, rvu in humerus:
    new_codes[code] = make_cpt(code, desc, spec="orthopedic_surgery", rvu=rvu, bilat=True, family="humerus_fracture")

# Forearm fractures (25500-25609)
forearm_fx = [
    ("25500", "Closed treatment of radial shaft fracture without manipulation", 3.12),
    ("25505", "Closed treatment of radial shaft fracture with manipulation", 5.67),
    ("25515", "Open treatment of radial shaft fracture with internal fixation", 12.45),
    ("25520", "Closed treatment of radial shaft fracture and ulnar fracture without manipulation", 3.89),
    ("25525", "Closed treatment of radial shaft fracture and ulnar fracture with manipulation", 6.78),
    ("25526", "Open treatment of radial shaft fracture with internal fixation and closed treatment ulnar", 13.56),
    ("25530", "Closed treatment of ulnar shaft fracture without manipulation", 2.89),
    ("25535", "Closed treatment of ulnar shaft fracture with manipulation", 5.23),
    ("25545", "Open treatment of ulnar shaft fracture with internal fixation", 11.78),
    ("25560", "Closed treatment of radial and ulnar shaft fractures without manipulation", 3.67),
    ("25565", "Closed treatment of radial and ulnar shaft fractures with manipulation", 7.12),
    ("25574", "Open treatment of radial AND ulnar shaft fractures with internal fixation", 16.34),
    ("25575", "Open treatment of radial AND ulnar shaft fractures with internal fixation of radius", 14.89),
    ("25600", "Closed treatment of distal radial fracture without manipulation", 3.23),
    ("25605", "Closed treatment of distal radial fracture with manipulation", 5.89),
    ("25606", "Percutaneous skeletal fixation of distal radial fracture", 8.45),
    ("25607", "Open treatment of distal radial extra-articular fracture with internal fixation", 12.67),
    ("25608", "Open treatment of distal radial intra-articular fracture 2 fragments", 14.23),
    ("25609", "Open treatment of distal radial intra-articular fracture 3+ fragments", 16.78),
]
for code, desc, rvu in forearm_fx:
    new_codes[code] = make_cpt(code, desc, spec="orthopedic_surgery", rvu=rvu, bilat=True, family="forearm_fracture")

# Hip fractures (27220-27269)
hip_fx = [
    ("27220", "Closed treatment of acetabulum fracture without manipulation", 4.56),
    ("27222", "Closed treatment of acetabulum fracture with manipulation", 8.23),
    ("27226", "Open treatment of posterior or anterior acetabular wall fracture with internal fixation", 22.45),
    ("27227", "Open treatment of acetabular fracture involving anterior/posterior walls with internal fixation", 28.67),
    ("27228", "Open treatment of acetabular fracture involving anterior/posterior columns with internal fixation", 32.12),
    ("27230", "Closed treatment of femoral fracture proximal end, neck without manipulation", 4.12),
    ("27232", "Closed treatment of femoral fracture proximal end, neck with manipulation", 7.89),
    ("27235", "Percutaneous skeletal fixation of femoral fracture proximal end, neck", 10.56),
    ("27236", "Open treatment of femoral fracture proximal end, neck with internal fixation or prosthetic replacement", 15.78),
    ("27238", "Closed treatment of intertrochanteric femoral fracture without manipulation", 4.34),
    ("27240", "Closed treatment of intertrochanteric femoral fracture with manipulation", 8.12),
    ("27244", "Treatment of intertrochanteric femoral fracture with plate/screw type implant", 14.89),
    ("27245", "Treatment of intertrochanteric femoral fracture with intramedullary implant", 15.23),
    ("27246", "Closed treatment of greater trochanteric fracture without manipulation", 2.78),
    ("27248", "Open treatment of greater trochanteric fracture with internal fixation", 10.45),
    ("27250", "Closed treatment of hip dislocation without anesthesia", 5.67),
    ("27252", "Closed treatment of hip dislocation requiring anesthesia", 8.34),
    ("27253", "Open treatment of hip dislocation", 15.89),
    ("27254", "Open treatment of hip dislocation with acetabular wall fracture", 20.12),
    ("27256", "Closed treatment of spontaneous hip dislocation with manipulation", 6.78),
    ("27257", "Treatment of spontaneous hip dislocation with abduction splint", 4.23),
    ("27259", "Closed treatment of femoral head or neck fracture with manipulation", 7.56),
    ("27265", "Closed treatment of post hip arthroplasty dislocation without anesthesia", 3.45),
    ("27266", "Closed treatment of post hip arthroplasty dislocation requiring anesthesia", 5.89),
    ("27267", "Closed treatment of femoral fracture proximal end, head", 4.67),
    ("27268", "Closed treatment of femoral fracture greater trochanteric without manipulation", 3.12),
    ("27269", "Open treatment of femoral fracture proximal end head", 18.34),
]
for code, desc, rvu in hip_fx:
    new_codes[code] = make_cpt(code, desc, spec="orthopedic_surgery", rvu=rvu, family="hip_fracture")

# Femoral shaft fractures (27500-27514)
femur_shaft = [
    ("27500", "Closed treatment of femoral shaft fracture without manipulation", 4.78),
    ("27501", "Closed treatment of supracondylar or transcondylar femoral fracture without manipulation", 4.56),
    ("27502", "Closed treatment of femoral shaft fracture with manipulation", 8.34),
    ("27503", "Closed treatment of supracondylar femoral fracture with manipulation", 8.67),
    ("27506", "Open treatment of femoral shaft fracture with plate/screws", 18.45),
    ("27507", "Open treatment of femoral shaft fracture with intramedullary nail", 17.89),
    ("27508", "Closed treatment of femoral fracture distal end without manipulation", 4.23),
    ("27509", "Percutaneous skeletal fixation of femoral fracture distal end", 11.78),
    ("27510", "Closed treatment of femoral fracture distal end with manipulation", 7.89),
    ("27511", "Open treatment of femoral supracondylar fracture without intercondylar extension", 17.56),
    ("27513", "Open treatment of femoral supracondylar fracture with intercondylar extension", 21.34),
    ("27514", "Open treatment of femoral condyle fracture", 16.78),
]
for code, desc, rvu in femur_shaft:
    new_codes[code] = make_cpt(code, desc, spec="orthopedic_surgery", rvu=rvu, family="femur_fracture")

# Tibial/fibular fractures (27750-27848)
tibia_fib = [
    ("27750", "Closed treatment of tibial shaft fracture without manipulation", 3.89),
    ("27752", "Closed treatment of tibial shaft fracture with manipulation", 6.78),
    ("27756", "Percutaneous skeletal fixation of tibial shaft fracture", 10.45),
    ("27758", "Open treatment of tibial shaft fracture with plate/screws", 15.67),
    ("27759", "Treatment of tibial shaft fracture with intramedullary implant", 14.89),
    ("27760", "Closed treatment of medial malleolus fracture without manipulation", 2.89),
    ("27762", "Closed treatment of medial malleolus fracture with manipulation", 5.23),
    ("27766", "Open treatment of medial malleolus fracture with internal fixation", 10.78),
    ("27780", "Closed treatment of proximal fibula fracture without manipulation", 2.12),
    ("27781", "Closed treatment of proximal fibula fracture with manipulation", 4.56),
    ("27784", "Open treatment of proximal fibula fracture with internal fixation", 9.45),
    ("27786", "Closed treatment of distal fibula fracture without manipulation", 2.34),
    ("27788", "Closed treatment of distal fibula fracture with manipulation", 4.78),
    ("27792", "Open treatment of distal fibula fracture with internal fixation", 9.89),
    ("27808", "Closed treatment of bimalleolar ankle fracture without manipulation", 3.45),
    ("27810", "Closed treatment of bimalleolar ankle fracture with manipulation", 6.12),
    ("27814", "Open treatment of bimalleolar ankle fracture with internal fixation", 14.56),
    ("27816", "Closed treatment of trimalleolar ankle fracture without manipulation", 3.89),
    ("27818", "Closed treatment of trimalleolar ankle fracture with manipulation", 7.23),
    ("27822", "Open treatment of trimalleolar ankle fracture medial and lateral malleoli only", 16.78),
    ("27823", "Open treatment of trimalleolar ankle fracture including fixation of posterior lip", 18.45),
    ("27824", "Closed treatment of fracture of weight bearing articular surface of tibia without manipulation", 3.56),
    ("27825", "Closed treatment of fracture of weight bearing articular surface of tibia with manipulation", 6.89),
    ("27826", "Open treatment of fracture of weight bearing articular surface of tibia with screws", 14.23),
    ("27827", "Open treatment of fracture of weight bearing articular surface of tibia with plate", 17.56),
    ("27828", "Open treatment of fracture of weight bearing articular surface of tibia with external fixation", 15.89),
    ("27829", "Open treatment of distal tibiofibular joint disruption", 12.34),
    ("27830", "Closed treatment of proximal tibiofibular joint dislocation without anesthesia", 2.78),
    ("27831", "Closed treatment of proximal tibiofibular joint dislocation requiring anesthesia", 4.56),
    ("27832", "Open treatment of proximal tibiofibular joint dislocation", 9.12),
    ("27840", "Closed treatment of ankle dislocation without anesthesia", 3.12),
    ("27842", "Closed treatment of ankle dislocation requiring anesthesia", 5.67),
    ("27846", "Open treatment of ankle dislocation with internal fixation", 12.89),
    ("27848", "Open treatment of ankle dislocation with internal and external fixation", 15.23),
]
for code, desc, rvu in tibia_fib:
    new_codes[code] = make_cpt(code, desc, spec="orthopedic_surgery", rvu=rvu, bilat=True, family="tibia_fibula_fracture")

# Foot fractures (28400-28530)
foot_fx = [
    ("28400", "Closed treatment of calcaneal fracture without manipulation", 2.78),
    ("28405", "Closed treatment of calcaneal fracture with manipulation", 5.12),
    ("28406", "Percutaneous skeletal fixation of calcaneal fracture", 9.34),
    ("28415", "Open treatment of calcaneal fracture with internal fixation", 16.78),
    ("28420", "Open treatment of calcaneal fracture with bone graft", 19.23),
    ("28430", "Closed treatment of talus fracture without manipulation", 2.56),
    ("28435", "Closed treatment of talus fracture with manipulation", 5.34),
    ("28436", "Percutaneous skeletal fixation of talus fracture", 8.67),
    ("28445", "Open treatment of talus fracture with internal fixation", 15.89),
    ("28446", "Open treatment of talus fracture with internal fixation and bone graft", 18.12),
    ("28450", "Treatment of tarsal bone fracture other than talus/calcaneus without manipulation", 2.12),
    ("28455", "Treatment of tarsal bone fracture other than talus/calcaneus with manipulation", 4.23),
    ("28456", "Percutaneous skeletal fixation of tarsal bone fracture other than talus/calcaneus", 7.34),
    ("28465", "Open treatment of tarsal bone fracture with internal fixation", 11.23),
    ("28470", "Closed treatment of metatarsal fracture without manipulation", 1.89),
    ("28475", "Closed treatment of metatarsal fracture with manipulation", 3.56),
    ("28476", "Percutaneous skeletal fixation of metatarsal fracture", 6.78),
    ("28485", "Open treatment of metatarsal fracture with internal fixation", 9.45),
    ("28490", "Closed treatment of fracture great toe phalanx without manipulation", 1.45),
    ("28495", "Closed treatment of fracture great toe phalanx with manipulation", 2.89),
    ("28496", "Percutaneous skeletal fixation of fracture great toe phalanx", 5.67),
    ("28505", "Open treatment of fracture great toe phalanx with internal fixation", 7.89),
    ("28510", "Closed treatment of fracture phalanx other than great toe without manipulation", 1.12),
    ("28515", "Closed treatment of fracture phalanx other than great toe with manipulation", 2.34),
    ("28525", "Open treatment of fracture phalanx of toe with internal fixation", 6.45),
    ("28530", "Closed treatment of sesamoid fracture", 1.56),
]
for code, desc, rvu in foot_fx:
    new_codes[code] = make_cpt(code, desc, spec="orthopedic_surgery", rvu=rvu, bilat=True, family="foot_fracture")

# Arthroscopy codes (29800-29999)
arthroscopy = [
    ("29800", "Arthroscopy temporomandibular joint diagnostic", 5.78, "arthroscopy_tmj"),
    ("29804", "Arthroscopy temporomandibular joint surgical", 8.45, "arthroscopy_tmj"),
    ("29805", "Arthroscopy shoulder diagnostic", 5.23, "arthroscopy_shoulder"),
    ("29806", "Arthroscopy shoulder surgical; capsulorrhaphy", 14.56, "arthroscopy_shoulder"),
    ("29807", "Arthroscopy shoulder surgical; repair of SLAP lesion", 13.89, "arthroscopy_shoulder"),
    ("29819", "Arthroscopy shoulder surgical; with removal of loose body or foreign body", 8.67, "arthroscopy_shoulder"),
    ("29820", "Arthroscopy shoulder surgical; synovectomy partial", 7.89, "arthroscopy_shoulder"),
    ("29821", "Arthroscopy shoulder surgical; synovectomy complete", 9.23, "arthroscopy_shoulder"),
    ("29822", "Arthroscopy shoulder surgical; debridement limited", 7.45, "arthroscopy_shoulder"),
    ("29823", "Arthroscopy shoulder surgical; debridement extensive", 8.89, "arthroscopy_shoulder"),
    ("29824", "Arthroscopy shoulder surgical; distal claviculectomy (Mumford)", 9.78, "arthroscopy_shoulder"),
    ("29825", "Arthroscopy shoulder surgical; with lysis and resection of adhesions", 8.12, "arthroscopy_shoulder"),
    ("29826", "Arthroscopy shoulder surgical; decompression of subacromial space with acromioplasty", 9.34, "arthroscopy_shoulder"),
    ("29827", "Arthroscopy shoulder surgical; with rotator cuff repair", 15.67, "arthroscopy_shoulder"),
    ("29828", "Arthroscopy shoulder surgical; biceps tenodesis", 12.34, "arthroscopy_shoulder"),
    ("29830", "Arthroscopy elbow diagnostic", 4.89, "arthroscopy_elbow"),
    ("29834", "Arthroscopy elbow surgical; with removal of loose body or foreign body", 7.56, "arthroscopy_elbow"),
    ("29835", "Arthroscopy elbow surgical; synovectomy partial", 7.23, "arthroscopy_elbow"),
    ("29836", "Arthroscopy elbow surgical; synovectomy complete", 8.67, "arthroscopy_elbow"),
    ("29837", "Arthroscopy elbow surgical; debridement limited", 6.89, "arthroscopy_elbow"),
    ("29838", "Arthroscopy elbow surgical; debridement extensive", 8.12, "arthroscopy_elbow"),
    ("29840", "Arthroscopy wrist diagnostic", 4.56, "arthroscopy_wrist"),
    ("29843", "Arthroscopy wrist surgical; for infection lavage and drainage", 7.34, "arthroscopy_wrist"),
    ("29844", "Arthroscopy wrist surgical; synovectomy partial", 6.78, "arthroscopy_wrist"),
    ("29845", "Arthroscopy wrist surgical; synovectomy complete", 8.23, "arthroscopy_wrist"),
    ("29846", "Arthroscopy wrist surgical; excision and/or repair of triangular fibrocartilage", 8.89, "arthroscopy_wrist"),
    ("29847", "Arthroscopy wrist surgical; internal fixation for fracture", 10.56, "arthroscopy_wrist"),
    ("29848", "Arthroscopy wrist surgical; endoscopic release of transverse carpal ligament", 7.45, "arthroscopy_wrist"),
    ("29850", "Arthroscopically aided treatment of tibial fracture proximal", 12.34, "arthroscopy_knee"),
    ("29851", "Arthroscopically aided treatment of tibial fracture bicondylar", 15.67, "arthroscopy_knee"),
    ("29855", "Arthroscopically aided treatment of tibial fracture unicondylar", 13.45, "arthroscopy_knee"),
    ("29856", "Arthroscopically aided treatment of tibial fracture bicondylar with internal fixation", 17.89, "arthroscopy_knee"),
    ("29860", "Arthroscopy hip diagnostic", 6.78, "arthroscopy_hip"),
    ("29861", "Arthroscopy hip surgical; with removal of loose body or foreign body", 9.23, "arthroscopy_hip"),
    ("29862", "Arthroscopy hip surgical; with debridement/shaving of articular cartilage", 10.45, "arthroscopy_hip"),
    ("29863", "Arthroscopy hip surgical; with femoroplasty", 12.67, "arthroscopy_hip"),
    ("29866", "Arthroscopy knee surgical; osteochondral autograft single plug", 12.34, "arthroscopy_knee"),
    ("29867", "Arthroscopy knee surgical; osteochondral allograft", 14.56, "arthroscopy_knee"),
    ("29868", "Arthroscopy knee surgical; meniscal transplantation", 15.89, "arthroscopy_knee"),
    ("29870", "Arthroscopy knee diagnostic", 4.45, "arthroscopy_knee"),
    ("29871", "Arthroscopy knee surgical; for infection lavage and drainage", 6.78, "arthroscopy_knee"),
    ("29873", "Arthroscopy knee surgical; with lateral release", 6.89, "arthroscopy_knee"),
    ("29874", "Arthroscopy knee surgical; for removal of loose body or foreign body", 6.45, "arthroscopy_knee"),
    ("29875", "Arthroscopy knee surgical; synovectomy limited", 5.89, "arthroscopy_knee"),
    ("29876", "Arthroscopy knee surgical; synovectomy major 2+ compartments", 7.23, "arthroscopy_knee"),
    ("29877", "Arthroscopy knee surgical; debridement/shaving of articular cartilage", 6.67, "arthroscopy_knee"),
    ("29879", "Arthroscopy knee surgical; abrasion arthroplasty or multiple drilling/microfracture", 7.89, "arthroscopy_knee"),
    ("29880", "Arthroscopy knee surgical; with meniscectomy medial AND lateral", 8.12, "arthroscopy_knee"),
    ("29881", "Arthroscopy knee surgical; with meniscectomy medial OR lateral", 7.45, "arthroscopy_knee"),
    ("29882", "Arthroscopy knee surgical; with meniscus repair medial OR lateral", 9.67, "arthroscopy_knee"),
    ("29883", "Arthroscopy knee surgical; with meniscus repair medial AND lateral", 11.23, "arthroscopy_knee"),
    ("29884", "Arthroscopy knee surgical; with lysis of adhesions", 6.34, "arthroscopy_knee"),
    ("29885", "Arthroscopy knee surgical; drilling for intact osteochondritis dissecans lesion", 7.56, "arthroscopy_knee"),
    ("29886", "Arthroscopy knee surgical; drilling for osteochondritis dissecans with internal fixation", 9.12, "arthroscopy_knee"),
    ("29887", "Arthroscopy knee surgical; drilling for chondral defect with bone graft", 10.34, "arthroscopy_knee"),
    ("29888", "Arthroscopically aided anterior cruciate ligament repair/augmentation or reconstruction", 15.89, "arthroscopy_knee"),
    ("29889", "Arthroscopically aided posterior cruciate ligament repair/augmentation or reconstruction", 17.23, "arthroscopy_knee"),
    ("29891", "Arthroscopy ankle surgical; excision of osteochondral defect", 8.67, "arthroscopy_ankle"),
    ("29892", "Arthroscopically aided repair of large osteochondral defect ankle", 12.45, "arthroscopy_ankle"),
    ("29893", "Endoscopic plantar fasciotomy", 6.34, "arthroscopy_ankle"),
    ("29894", "Arthroscopy ankle surgical; with removal of loose body or foreign body", 6.89, "arthroscopy_ankle"),
    ("29895", "Arthroscopy ankle surgical; synovectomy partial", 6.45, "arthroscopy_ankle"),
    ("29897", "Arthroscopy ankle surgical; debridement limited", 6.12, "arthroscopy_ankle"),
    ("29898", "Arthroscopy ankle surgical; debridement extensive", 7.56, "arthroscopy_ankle"),
    ("29899", "Arthroscopy ankle surgical; with ankle arthrodesis", 14.23, "arthroscopy_ankle"),
    ("29900", "Arthroscopy metacarpophalangeal joint diagnostic", 4.12, "arthroscopy_hand"),
    ("29901", "Arthroscopy metacarpophalangeal joint surgical with debridement", 6.34, "arthroscopy_hand"),
    ("29902", "Arthroscopy metacarpophalangeal joint surgical with reduction of fracture", 8.56, "arthroscopy_hand"),
    ("29914", "Arthroscopy hip surgical; with femoroplasty cam type", 13.89, "arthroscopy_hip"),
    ("29915", "Arthroscopy hip surgical; with acetabuloplasty pincer type", 14.56, "arthroscopy_hip"),
    ("29916", "Arthroscopy hip surgical; with labral repair", 15.23, "arthroscopy_hip"),
    ("29999", "Unlisted procedure arthroscopy", 0.00, "arthroscopy_unlisted"),
]
for code, desc, rvu, fam in arthroscopy:
    new_codes[code] = make_cpt(code, desc, spec="orthopedic_surgery", rvu=rvu, bilat=True, family=fam)

# Spine instrumentation (22840-22899)
spine_instr = [
    ("22840", "Posterior non-segmental instrumentation", 12.89, True),
    ("22841", "Internal spinal fixation by wiring of spinous processes", 10.34, True),
    ("22842", "Posterior segmental instrumentation 3-6 vertebral segments", 15.67, True),
    ("22843", "Posterior segmental instrumentation 7-12 vertebral segments", 18.23, True),
    ("22844", "Posterior segmental instrumentation 13+ vertebral segments", 20.45, True),
    ("22845", "Anterior instrumentation 2-3 vertebral segments", 13.56, True),
    ("22846", "Anterior instrumentation 4-7 vertebral segments", 16.78, True),
    ("22847", "Anterior instrumentation 8+ vertebral segments", 19.34, True),
    ("22848", "Pelvic fixation other than sacrum", 8.45, True),
    ("22849", "Reinsertion of spinal fixation device", 14.23, False),
    ("22850", "Removal of posterior non-segmental instrumentation", 10.78, False),
    ("22851", "Application of intervertebral biomechanical device to vertebral defect", 6.78, True),
    ("22852", "Removal of posterior segmental instrumentation", 12.34, False),
    ("22853", "Insertion of interbody biomechanical device with integral anterior instrumentation", 7.89, True),
    ("22854", "Insertion of interbody biomechanical device with integral anterior instrumentation for device replacement", 8.56, False),
    ("22855", "Removal of anterior instrumentation", 11.56, False),
    ("22856", "Total disc arthroplasty anterior approach single interspace cervical", 22.34, False),
    ("22857", "Total disc arthroplasty anterior approach single interspace lumbar", 24.56, False),
    ("22858", "Total disc arthroplasty second level cervical", 8.67, True),
    ("22859", "Interspinous process stabilization device", 7.34, True),
    ("22861", "Revision including replacement of total disc arthroplasty anterior approach cervical", 25.67, False),
    ("22862", "Revision including replacement of total disc arthroplasty anterior approach lumbar", 27.89, False),
    ("22864", "Removal of total disc arthroplasty anterior approach cervical", 20.34, False),
    ("22865", "Removal of total disc arthroplasty anterior approach lumbar", 22.56, False),
    ("22867", "Insertion of interlaminar/interspinous process stabilization/distraction device without fusion", 8.89, False),
    ("22869", "Insertion of interlaminar/interspinous process stabilization/distraction device without open decompression", 9.23, False),
    ("22899", "Unlisted procedure spine", 0.00, False),
]
for code, desc, rvu, addon in spine_instr:
    new_codes[code] = make_cpt(code, desc, spec="orthopedic_surgery", rvu=rvu, addon=addon, family="spine_instrumentation", glob=90)

# Bone graft codes (20900-20938)
bone_graft = [
    ("20900", "Bone graft any donor area; minor or small", 3.56),
    ("20902", "Bone graft any donor area; major or large", 6.78),
    ("20910", "Cartilage graft; costochondral", 7.89),
    ("20912", "Cartilage graft; nasal septum", 4.56),
    ("20920", "Fascia lata graft; by stripper", 3.78),
    ("20922", "Fascia lata graft; by incision and area exposure", 5.67),
    ("20924", "Tendon graft from a distance", 5.23),
    ("20926", "Tissue grafts other; fat, dermis, fascia", 3.45),
    ("20930", "Allograft morselized for spine surgery only", 1.89),
    ("20931", "Allograft structural for spine surgery only", 2.34),
    ("20932", "Allograft includes harvesting for local use in other areas", 2.67),
    ("20933", "Allograft structural for other than spine", 2.89),
    ("20934", "Autograft morselized for spine surgery only", 3.12),
    ("20936", "Autograft for spine surgery only local", 3.89),
    ("20937", "Autograft for spine surgery only morselized through separate skin incision", 4.56),
    ("20938", "Autograft for spine surgery only structural bicortical or tricortical through separate skin incision", 5.78),
]
for code, desc, rvu in bone_graft:
    new_codes[code] = make_cpt(code, desc, spec="orthopedic_surgery", rvu=rvu, addon=True, family="bone_graft", glob=0)

# Casting and strapping (29000-29799)
casting = [
    ("29000", "Application of halo type body cast", 5.67),
    ("29010", "Application of Risser jacket localizer body cast", 6.78),
    ("29015", "Application of halo cervical", 5.23),
    ("29020", "Application of turnbuckle jacket body cast", 5.89),
    ("29035", "Application of body cast shoulder to hips", 4.56),
    ("29040", "Application of body cast shoulder to hips including head (Minerva cast)", 5.12),
    ("29044", "Application of body cast shoulder to hips including 1 thigh", 5.34),
    ("29046", "Application of body cast shoulder to hips including both thighs", 5.89),
    ("29049", "Application body cast figure of 8", 3.45),
    ("29055", "Application of body cast shoulder to hand long arm", 3.78),
    ("29058", "Application of body cast plaster Velpeau", 3.23),
    ("29065", "Application of shoulder to hand cast long arm", 3.12),
    ("29075", "Application of elbow to finger cast short arm", 2.56),
    ("29085", "Application of hand and lower forearm cast", 2.34),
    ("29086", "Application of finger cast", 1.23),
    ("29105", "Application of long arm splint shoulder to hand", 1.89),
    ("29125", "Application of short arm splint forearm to hand static", 1.45),
    ("29126", "Application of short arm splint forearm to hand dynamic", 1.67),
    ("29130", "Application of finger splint static", 0.89),
    ("29131", "Application of finger splint dynamic", 1.12),
    ("29200", "Strapping of chest", 1.23),
    ("29240", "Strapping of shoulder", 1.34),
    ("29260", "Strapping of elbow or wrist", 1.12),
    ("29280", "Strapping of hand or finger", 0.89),
    ("29305", "Application of hip spica cast one leg", 4.56),
    ("29325", "Application of hip spica cast both legs", 5.89),
    ("29345", "Application of long leg cast above knee to toes", 2.89),
    ("29355", "Application of long leg cast walker or ambulatory type", 2.78),
    ("29358", "Application of long leg cast brace", 3.12),
    ("29365", "Application of cylinder cast thigh to ankle", 2.45),
    ("29405", "Application of short leg cast below knee to toes", 2.12),
    ("29425", "Application of short leg cast walking", 2.23),
    ("29435", "Application of patellar tendon bearing cast", 2.67),
    ("29440", "Adding walker to previously applied cast", 0.67),
    ("29445", "Application of rigid total contact leg cast", 2.89),
    ("29450", "Application of clubfoot cast with molding or manipulation", 3.45),
    ("29505", "Application of long leg splint thigh to ankle", 1.56),
    ("29515", "Application of short leg splint calf to foot", 1.23),
    ("29520", "Strapping of hip", 1.34),
    ("29530", "Strapping of knee", 1.12),
    ("29540", "Strapping of ankle and/or foot", 1.23),
    ("29550", "Strapping of toes", 0.78),
    ("29580", "Application of Unna boot", 1.34),
    ("29581", "Application of multi-layer compression system below knee", 1.56),
    ("29584", "Application of multi-layer compression system upper arm/lower leg", 1.67),
    ("29700", "Removal or bivalving of gauntlet body cast or full arm/leg cast", 1.12),
    ("29705", "Removal or bivalving of full arm or full leg cast", 0.89),
    ("29710", "Removal or bivalving of shoulder or hip spica body/jacket cast", 1.34),
    ("29715", "Removal or bivalving of turnbuckle jacket body cast", 1.56),
    ("29720", "Repair or modification of cast long arm short arm or long/short leg", 0.89),
    ("29730", "Windowing of cast", 0.67),
    ("29740", "Wedging of cast", 1.12),
    ("29750", "Wedging of clubfoot cast", 1.34),
    ("29799", "Unlisted procedure casting or strapping", 0.00),
]
for code, desc, rvu in casting:
    new_codes[code] = make_cpt(code, desc, cat="Surgery", spec="orthopedic_surgery", rvu=rvu, glob=0, family="casting_strapping")

# Additional ortho procedures
ortho_misc = [
    ("20150", "Excision of epiphyseal bar with or without autograft", 14.56, "orthopedic_surgery"),
    ("20200", "Superficial muscle biopsy", 2.34, "orthopedic_surgery"),
    ("20205", "Deep muscle biopsy", 3.89, "orthopedic_surgery"),
    ("20206", "Needle biopsy of muscle", 1.67, "orthopedic_surgery"),
    ("20220", "Bone biopsy trocar or needle superficial", 2.12, "orthopedic_surgery"),
    ("20225", "Bone biopsy trocar or needle deep", 3.45, "orthopedic_surgery"),
    ("20240", "Bone biopsy excisional superficial", 4.56, "orthopedic_surgery"),
    ("20245", "Bone biopsy excisional deep", 6.78, "orthopedic_surgery"),
    ("20250", "Open bone biopsy superficial", 4.89, "orthopedic_surgery"),
    ("20251", "Open bone biopsy deep", 7.23, "orthopedic_surgery"),
    ("20500", "Injection of sinus tract diagnostic", 1.56, "orthopedic_surgery"),
    ("20501", "Injection of sinus tract therapeutic", 1.78, "orthopedic_surgery"),
    ("20520", "Removal of foreign body in muscle or tendon sheath simple", 3.34, "orthopedic_surgery"),
    ("20525", "Removal of foreign body in muscle or tendon sheath deep or complicated", 6.12, "orthopedic_surgery"),
    ("20526", "Injection therapeutic carpal tunnel", 1.56, "orthopedic_surgery"),
    ("20550", "Injection tendon sheath ligament trigger point/ganglion cyst", 1.23, "orthopedic_surgery"),
    ("20551", "Injection tendon origin/insertion", 1.12, "orthopedic_surgery"),
    ("20552", "Injection single or multiple trigger points 1-2 muscles", 1.34, "orthopedic_surgery"),
    ("20553", "Injection single or multiple trigger points 3+ muscles", 1.56, "orthopedic_surgery"),
    ("20555", "Placement of needles or catheters into muscle for interstitial radioelement application", 3.89, "orthopedic_surgery"),
    ("20600", "Arthrocentesis aspiration/injection small joint bursa", 1.23, "orthopedic_surgery"),
    ("20604", "Arthrocentesis aspiration/injection small joint with ultrasound guidance", 1.56, "orthopedic_surgery"),
    ("20605", "Arthrocentesis aspiration/injection intermediate joint bursa", 1.34, "orthopedic_surgery"),
    ("20606", "Arthrocentesis aspiration/injection intermediate joint with ultrasound guidance", 1.67, "orthopedic_surgery"),
    ("20610", "Arthrocentesis aspiration/injection major joint bursa", 1.56, "orthopedic_surgery"),
    ("20611", "Arthrocentesis aspiration/injection major joint with ultrasound guidance", 1.89, "orthopedic_surgery"),
    ("20612", "Aspiration/injection ganglion cyst", 1.67, "orthopedic_surgery"),
    ("20615", "Aspiration and injection for treatment of bone cyst", 3.12, "orthopedic_surgery"),
    ("20650", "Insertion of wire or pin with application of skeletal traction", 3.45, "orthopedic_surgery"),
    ("20660", "Application of cranial tongs, caliper, or stereotactic frame", 3.89, "orthopedic_surgery"),
    ("20661", "Application of halo including removal cranial", 5.67, "orthopedic_surgery"),
    ("20662", "Application of halo pelvic", 8.12, "orthopedic_surgery"),
    ("20663", "Application of halo femoral", 6.78, "orthopedic_surgery"),
    ("20670", "Removal of implant superficial", 3.12, "orthopedic_surgery"),
    ("20680", "Removal of implant deep", 7.56, "orthopedic_surgery"),
    ("20690", "Application of uniplane external fixation system", 6.89, "orthopedic_surgery"),
    ("20692", "Application of multiplane external fixation system", 10.23, "orthopedic_surgery"),
    ("20693", "Adjustment or revision of external fixation system", 3.45, "orthopedic_surgery"),
    ("20694", "Removal under anesthesia of external fixation system", 4.56, "orthopedic_surgery"),
    ("20696", "Application of multiplane external fixation with stereotactic computer-assisted adjustment", 15.67, "orthopedic_surgery"),
    ("20697", "Complex multiplane external fixation reprogramming/adjustment", 4.89, "orthopedic_surgery"),
    ("27120", "Acetabuloplasty; (eg, Whitman, Colonna, Haygroves, or cup type)", 18.56, "orthopedic_surgery"),
    ("27122", "Acetabuloplasty; resection femoral head", 16.78, "orthopedic_surgery"),
    ("27125", "Hemiarthroplasty hip partial (eg, femoral stem prosthesis, bipolar arthroplasty)", 15.23, "orthopedic_surgery"),
    ("27130", "Arthroplasty acetabular and proximal femoral prosthetic replacement total hip arthroplasty", 22.67, "orthopedic_surgery"),
    ("27132", "Conversion of previous hip surgery to total hip arthroplasty", 25.89, "orthopedic_surgery"),
    ("27134", "Revision of total hip arthroplasty; both components with or without autograft or allograft", 30.12, "orthopedic_surgery"),
    ("27137", "Revision of total hip arthroplasty; acetabular component only", 25.34, "orthopedic_surgery"),
    ("27138", "Revision of total hip arthroplasty; femoral component only", 24.67, "orthopedic_surgery"),
    ("27236", "Open treatment of femoral fracture proximal end neck internal fixation or prosthetic replacement", 15.78, "orthopedic_surgery"),
    ("27280", "Arthrodesis sacroiliac joint open including bone graft", 14.56, "orthopedic_surgery"),
    ("27282", "Arthrodesis sacroiliac joint percutaneous or minimally invasive", 10.23, "orthopedic_surgery"),
    ("27284", "Arthrodesis hip joint", 20.34, "orthopedic_surgery"),
    ("27286", "Arthrodesis hip joint with subtrochanteric osteotomy", 24.56, "orthopedic_surgery"),
    ("27290", "Interpelviabdominal (hindquarter) amputation", 28.67, "orthopedic_surgery"),
    ("27295", "Disarticulation of hip", 22.34, "orthopedic_surgery"),
    ("27299", "Unlisted procedure pelvis or hip joint", 0.00, "orthopedic_surgery"),
    ("27310", "Arthrotomy knee with exploration drainage or removal of foreign body", 7.89, "orthopedic_surgery"),
    ("27330", "Arthrotomy knee with synovial biopsy only", 5.67, "orthopedic_surgery"),
    ("27331", "Arthrotomy knee including joint exploration biopsy or removal of loose or foreign bodies", 7.23, "orthopedic_surgery"),
    ("27332", "Arthrotomy with excision of semilunar cartilage (meniscectomy) knee medial OR lateral", 9.45, "orthopedic_surgery"),
    ("27333", "Arthrotomy with excision of semilunar cartilage (meniscectomy) knee medial AND lateral", 11.23, "orthopedic_surgery"),
    ("27334", "Arthrotomy with synovectomy knee anterior", 9.67, "orthopedic_surgery"),
    ("27335", "Arthrotomy with synovectomy knee anterior AND posterior", 12.34, "orthopedic_surgery"),
    ("27340", "Excision of prepatellar bursa", 4.56, "orthopedic_surgery"),
    ("27345", "Excision of synovial cyst of popliteal space (Baker cyst)", 5.89, "orthopedic_surgery"),
    ("27347", "Excision of lesion of meniscus or capsule of knee", 6.78, "orthopedic_surgery"),
    ("27350", "Patellectomy or hemipatellectomy", 10.23, "orthopedic_surgery"),
    ("27355", "Excision or curettage of bone cyst or benign tumor of femur", 8.45, "orthopedic_surgery"),
    ("27356", "Excision or curettage of bone cyst or benign tumor of femur with allograft", 10.67, "orthopedic_surgery"),
    ("27357", "Excision or curettage of bone cyst or benign tumor of femur with autograft", 11.89, "orthopedic_surgery"),
    ("27358", "Excision or curettage of bone cyst or benign tumor of femur with internal fixation", 12.34, "orthopedic_surgery"),
    ("27360", "Partial excision of bone femur proximal tibia and/or fibula", 12.56, "orthopedic_surgery"),
    ("27365", "Radical resection of tumor bone femur or knee", 20.78, "orthopedic_surgery"),
    ("27380", "Suture of infrapatellar tendon primary", 8.56, "orthopedic_surgery"),
    ("27381", "Suture of infrapatellar tendon secondary reconstruction", 12.34, "orthopedic_surgery"),
    ("27385", "Suture of quadriceps or hamstring muscle rupture primary", 9.67, "orthopedic_surgery"),
    ("27386", "Suture of quadriceps or hamstring muscle rupture secondary reconstruction", 13.45, "orthopedic_surgery"),
    ("27390", "Tenotomy open hamstring knee to hip single tendon", 5.23, "orthopedic_surgery"),
    ("27391", "Tenotomy open hamstring knee to hip multiple tendons one leg", 7.34, "orthopedic_surgery"),
    ("27392", "Tenotomy open hamstring knee to hip multiple tendons bilateral", 9.45, "orthopedic_surgery"),
    ("27395", "Lengthening of hamstring tendon single tendon", 6.78, "orthopedic_surgery"),
    ("27396", "Transplant or transfer hamstring tendon to patella single tendon", 10.23, "orthopedic_surgery"),
    ("27397", "Transplant or transfer hamstring tendons multiple", 12.34, "orthopedic_surgery"),
    ("27400", "Transfer tendon or muscle to restore knee flexion", 11.56, "orthopedic_surgery"),
    ("27403", "Arthrotomy with meniscus repair knee", 10.89, "orthopedic_surgery"),
    ("27405", "Repair primary disrupted ligament collateral knee", 12.67, "orthopedic_surgery"),
    ("27407", "Repair primary disrupted ligament cruciate knee", 14.89, "orthopedic_surgery"),
    ("27409", "Repair primary disrupted collateral and cruciate ligaments knee", 18.23, "orthopedic_surgery"),
    ("27412", "Autologous chondrocyte implantation knee", 16.78, "orthopedic_surgery"),
    ("27415", "Osteochondral allograft knee open", 16.34, "orthopedic_surgery"),
    ("27416", "Osteochondral autograft knee open", 14.56, "orthopedic_surgery"),
    ("27418", "Anterior tibial tubercleplasty (Maquet type procedure)", 12.34, "orthopedic_surgery"),
    ("27420", "Reconstruction dislocating patella with extensor realignment", 12.89, "orthopedic_surgery"),
    ("27422", "Reconstruction dislocating patella with extensor realignment with patellar prosthesis", 15.67, "orthopedic_surgery"),
    ("27424", "Reconstruction dislocating patella lateral retinacular release open", 7.89, "orthopedic_surgery"),
    ("27425", "Lateral retinacular release open", 6.34, "orthopedic_surgery"),
    ("27427", "Ligamentous reconstruction extra-articular knee", 14.56, "orthopedic_surgery"),
    ("27428", "Ligamentous reconstruction intra-articular knee", 16.78, "orthopedic_surgery"),
    ("27429", "Ligamentous reconstruction combined intra and extra-articular knee", 20.34, "orthopedic_surgery"),
    ("27430", "Quadricepsplasty", 12.56, "orthopedic_surgery"),
    ("27435", "Capsulotomy posterior capsular release knee", 8.89, "orthopedic_surgery"),
    ("27437", "Arthroplasty patella without prosthesis", 8.34, "orthopedic_surgery"),
    ("27438", "Arthroplasty patella with prosthesis", 10.56, "orthopedic_surgery"),
    ("27440", "Arthroplasty knee tibial plateau", 14.89, "orthopedic_surgery"),
    ("27441", "Arthroplasty knee tibial plateau with debridement and partial synovectomy", 15.67, "orthopedic_surgery"),
    ("27442", "Arthroplasty femoral condyles or tibial plateau knee", 16.34, "orthopedic_surgery"),
    ("27443", "Arthroplasty femoral condyles or tibial plateau with debridement", 17.56, "orthopedic_surgery"),
    ("27445", "Arthroplasty knee hinge prosthesis", 20.89, "orthopedic_surgery"),
    ("27446", "Arthroplasty knee condyle and plateau medial OR lateral compartment", 18.34, "orthopedic_surgery"),
    ("27447", "Arthroplasty knee condyle and plateau medial AND lateral total knee arthroplasty", 22.12, "orthopedic_surgery"),
    ("27448", "Osteotomy tibia proximal", 12.67, "orthopedic_surgery"),
    ("27450", "Osteotomy femur shaft or supracondylar", 14.89, "orthopedic_surgery"),
    ("27454", "Osteotomy multiple simultaneous separate sites femur", 18.34, "orthopedic_surgery"),
    ("27455", "Osteotomy proximal tibia including fibular excision or osteotomy before age 16", 12.34, "orthopedic_surgery"),
    ("27457", "Osteotomy proximal tibia including fibular excision or osteotomy after age 16", 13.56, "orthopedic_surgery"),
    ("27465", "Shortening of femur or tibia", 14.78, "orthopedic_surgery"),
    ("27466", "Lengthening of long bone femur", 16.89, "orthopedic_surgery"),
    ("27468", "Lengthening of long bone tibia", 15.67, "orthopedic_surgery"),
    ("27470", "Repair nonunion or malunion femur without graft", 16.34, "orthopedic_surgery"),
    ("27472", "Repair nonunion or malunion femur with iliac or other autogenous bone graft", 19.56, "orthopedic_surgery"),
    ("27475", "Arrest epiphyseal by epiphysiodesis or stapling distal femur", 8.34, "orthopedic_surgery"),
    ("27477", "Arrest epiphyseal by epiphysiodesis or stapling proximal tibia and fibula", 8.67, "orthopedic_surgery"),
    ("27479", "Arrest epiphyseal by epiphysiodesis or stapling distal femur and proximal tibia/fibula", 10.89, "orthopedic_surgery"),
    ("27485", "Arrest epiphyseal any method combined distal femur proximal tibia and fibula", 11.23, "orthopedic_surgery"),
    ("27486", "Revision total knee arthroplasty one component", 24.56, "orthopedic_surgery"),
    ("27487", "Revision total knee arthroplasty both components", 28.34, "orthopedic_surgery"),
    ("27488", "Removal of prosthesis including total knee arthroplasty", 18.67, "orthopedic_surgery"),
    ("27495", "Prophylactic treatment with nailing or pinning or plating femur", 12.34, "orthopedic_surgery"),
    ("27496", "Decompression fasciotomy thigh/leg anterior compartment only with debridement", 9.78, "orthopedic_surgery"),
    ("27497", "Decompression fasciotomy thigh/leg anterior and/or lateral compartments", 11.34, "orthopedic_surgery"),
    ("27498", "Decompression fasciotomy thigh/leg anterior and/or lateral and posterior compartments", 14.56, "orthopedic_surgery"),
    ("27499", "Unlisted procedure femur or knee", 0.00, "orthopedic_surgery"),
    ("27590", "Amputation thigh through femur any level", 12.34, "orthopedic_surgery"),
    ("27591", "Amputation thigh through femur any level open circular (guillotine)", 10.56, "orthopedic_surgery"),
    ("27592", "Amputation thigh through femur any level secondary closure or scar revision", 7.89, "orthopedic_surgery"),
    ("27594", "Amputation thigh through femur any level reamputation", 12.67, "orthopedic_surgery"),
    ("27596", "Amputation thigh through femur any level with immediate fitting technique", 14.23, "orthopedic_surgery"),
    ("27598", "Disarticulation at knee", 12.56, "orthopedic_surgery"),
    ("27599", "Unlisted procedure leg or ankle", 0.00, "orthopedic_surgery"),
    ("27600", "Decompression fasciotomy leg anterior and/or lateral compartments only with debridement", 8.56, "orthopedic_surgery"),
    ("27601", "Decompression fasciotomy leg posterior compartment only with debridement", 8.89, "orthopedic_surgery"),
    ("27602", "Decompression fasciotomy leg anterior and/or lateral and posterior compartments", 12.34, "orthopedic_surgery"),
    ("27603", "Incision and drainage leg deep abscess or hematoma", 5.67, "orthopedic_surgery"),
    ("27604", "Incision and drainage leg infected bursa", 4.23, "orthopedic_surgery"),
    ("27605", "Tenotomy percutaneous Achilles tendon", 3.45, "orthopedic_surgery"),
    ("27606", "Tenotomy percutaneous Achilles tendon under anesthesia", 4.12, "orthopedic_surgery"),
    ("27607", "Incision deep with opening of bone cortex for osteomyelitis or bone abscess tibia", 8.67, "orthopedic_surgery"),
    ("27610", "Arthrotomy ankle including exploration drainage or removal of foreign body", 6.78, "orthopedic_surgery"),
    ("27612", "Arthrotomy posterior capsular release ankle", 7.89, "orthopedic_surgery"),
    ("27613", "Biopsy soft tissue of leg or ankle area superficial", 2.12, "orthopedic_surgery"),
    ("27614", "Biopsy soft tissue of leg or ankle area deep", 3.89, "orthopedic_surgery"),
    ("27615", "Radical resection of tumor soft tissue of leg or ankle area", 12.34, "orthopedic_surgery"),
    ("27618", "Excision of tumor soft tissue of leg or ankle area subcutaneous", 4.56, "orthopedic_surgery"),
    ("27619", "Excision of tumor soft tissue of leg or ankle area subfascial", 7.23, "orthopedic_surgery"),
    ("27620", "Arthrotomy ankle with joint exploration with or without biopsy", 6.45, "orthopedic_surgery"),
    ("27625", "Arthrotomy with synovectomy ankle", 8.67, "orthopedic_surgery"),
    ("27626", "Arthrotomy with synovectomy ankle tendon sheath", 7.89, "orthopedic_surgery"),
    ("27630", "Excision of lesion of tendon sheath or capsule ankle", 5.23, "orthopedic_surgery"),
    ("27632", "Excision of tumor soft tissue of leg or ankle area subcutaneous 3cm or greater", 5.67, "orthopedic_surgery"),
    ("27634", "Excision of tumor soft tissue of leg or ankle area subfascial 5cm or greater", 8.89, "orthopedic_surgery"),
    ("27635", "Excision or curettage of bone cyst or benign tumor tibia or fibula", 8.34, "orthopedic_surgery"),
    ("27637", "Excision or curettage of bone cyst or benign tumor tibia or fibula with autograft", 10.56, "orthopedic_surgery"),
    ("27638", "Excision or curettage of bone cyst or benign tumor tibia or fibula with allograft", 10.12, "orthopedic_surgery"),
    ("27640", "Partial excision of bone tibia", 10.78, "orthopedic_surgery"),
    ("27641", "Partial excision of bone fibula", 8.56, "orthopedic_surgery"),
    ("27645", "Radical resection of tumor bone tibia", 18.34, "orthopedic_surgery"),
    ("27646", "Radical resection of tumor bone fibula", 14.56, "orthopedic_surgery"),
    ("27647", "Radical resection of tumor bone talus or calcaneus", 16.78, "orthopedic_surgery"),
    ("27648", "Injection procedure for ankle arthrography", 2.34, "orthopedic_surgery"),
    ("27650", "Repair primary open or percutaneous Achilles tendon", 9.67, "orthopedic_surgery"),
    ("27652", "Repair secondary Achilles tendon with or without graft", 12.34, "orthopedic_surgery"),
    ("27654", "Repair secondary Achilles tendon with fascial or tendon graft", 14.56, "orthopedic_surgery"),
    ("27656", "Repair of fascia or muscle defect of leg", 7.89, "orthopedic_surgery"),
    ("27658", "Repair of flexor tendon leg primary without graft", 7.56, "orthopedic_surgery"),
    ("27659", "Repair of flexor tendon leg primary without graft each additional tendon", 3.78, "orthopedic_surgery"),
    ("27664", "Repair of extensor tendon leg primary without graft", 6.89, "orthopedic_surgery"),
    ("27665", "Repair of extensor tendon leg primary without graft each additional tendon", 3.45, "orthopedic_surgery"),
    ("27675", "Repair dislocating peroneal tendons without fibular osteotomy", 8.67, "orthopedic_surgery"),
    ("27676", "Repair dislocating peroneal tendons with fibular osteotomy", 10.89, "orthopedic_surgery"),
    ("27680", "Tenolysis flexor tendon leg single tendon", 6.34, "orthopedic_surgery"),
    ("27681", "Tenolysis flexor tendon leg multiple tendons", 8.56, "orthopedic_surgery"),
    ("27685", "Lengthening or shortening of tendon leg or ankle single tendon", 6.78, "orthopedic_surgery"),
    ("27686", "Lengthening or shortening of tendon leg or ankle multiple tendons", 8.89, "orthopedic_surgery"),
    ("27687", "Gastrocnemius recession", 6.23, "orthopedic_surgery"),
    ("27690", "Transfer or transplant single tendon with muscle redirection or rerouting lower leg", 9.34, "orthopedic_surgery"),
    ("27691", "Transfer or transplant single tendon with muscle redirection or rerouting deep", 10.56, "orthopedic_surgery"),
    ("27692", "Transfer or transplant single tendon with muscle redirection or rerouting each additional", 4.23, "orthopedic_surgery"),
    ("27695", "Repair primary disrupted collateral ligament ankle", 8.78, "orthopedic_surgery"),
    ("27696", "Repair primary disrupted collateral ligaments ankle both", 12.34, "orthopedic_surgery"),
    ("27698", "Repair secondary disrupted collateral ligament ankle with local tissue", 10.89, "orthopedic_surgery"),
    ("27700", "Arthroplasty ankle", 14.56, "orthopedic_surgery"),
    ("27702", "Arthroplasty ankle with implant total ankle", 22.34, "orthopedic_surgery"),
    ("27703", "Arthroplasty ankle revision total ankle", 26.78, "orthopedic_surgery"),
    ("27704", "Removal of ankle implant", 14.23, "orthopedic_surgery"),
    ("27705", "Osteotomy tibia", 12.34, "orthopedic_surgery"),
    ("27707", "Osteotomy fibula", 8.56, "orthopedic_surgery"),
    ("27709", "Osteotomy tibia and fibula", 14.78, "orthopedic_surgery"),
    ("27712", "Osteotomy multiple simultaneous separate sites tibia", 16.34, "orthopedic_surgery"),
    ("27715", "Osteoplasty tibia and fibula lengthening or shortening", 14.89, "orthopedic_surgery"),
    ("27720", "Repair nonunion or malunion tibia without graft", 14.56, "orthopedic_surgery"),
    ("27722", "Repair nonunion or malunion tibia with sliding graft", 16.78, "orthopedic_surgery"),
    ("27724", "Repair of nonunion or malunion tibia with iliac or other autograft", 18.34, "orthopedic_surgery"),
    ("27725", "Repair of nonunion or malunion tibia by synostosis with fibula", 16.56, "orthopedic_surgery"),
    ("27726", "Repair of fibula nonunion and/or malunion with internal fixation", 12.34, "orthopedic_surgery"),
    ("27727", "Repair of congenital pseudarthrosis tibia", 18.67, "orthopedic_surgery"),
    ("27730", "Arrest epiphyseal by epiphysiodesis or stapling distal tibia", 7.89, "orthopedic_surgery"),
    ("27732", "Arrest epiphyseal by epiphysiodesis or stapling distal tibia and fibula", 8.56, "orthopedic_surgery"),
    ("27734", "Arrest epiphyseal by epiphysiodesis or stapling; distal tibia and fibula and proximal tibia and fibula", 10.34, "orthopedic_surgery"),
    ("27740", "Arrest epiphyseal any method combined distal tibia and fibula", 9.12, "orthopedic_surgery"),
    ("27742", "Arrest epiphyseal any method combined all sites lower extremity", 11.45, "orthopedic_surgery"),
    ("27745", "Prophylactic treatment with nailing pinning plating or wiring tibia", 10.67, "orthopedic_surgery"),
]
for code, desc, rvu, spec in ortho_misc:
    new_codes[code] = make_cpt(code, desc, spec=spec, rvu=rvu, family="orthopedic_misc")

# ============================================================
# 2. HAND SURGERY (200+ codes)
# ============================================================

hand_surgery = [
    # Tendon repair
    ("26350", "Repair or advancement flexor tendon in zone 2 digital flexor tendon sheath primary or secondary", 10.23, "tendon_repair"),
    ("26352", "Repair or advancement flexor tendon in zone 2 secondary with free graft", 12.45, "tendon_repair"),
    ("26356", "Repair or advancement flexor tendon in zone 2 without free graft each additional tendon", 4.56, "tendon_repair"),
    ("26357", "Repair or advancement flexor tendon in zone 2 secondary each additional tendon", 5.23, "tendon_repair"),
    ("26358", "Repair or advancement flexor tendon in zone 2 secondary staged", 12.67, "tendon_repair"),
    ("26370", "Repair or advancement of profundus tendon with intact superficialis tendon primary", 10.56, "tendon_repair"),
    ("26372", "Repair or advancement of profundus tendon with intact superficialis tendon secondary with free graft", 12.89, "tendon_repair"),
    ("26373", "Repair or advancement of profundus tendon with intact superficialis tendon secondary each additional", 5.34, "tendon_repair"),
    ("26390", "Excision flexor tendon with implantation of synthetic rod for delayed tendon graft hand/finger", 10.78, "tendon_repair"),
    ("26392", "Removal of synthetic rod and insertion of flexor tendon graft hand/finger", 12.34, "tendon_repair"),
    ("26410", "Repair extensor tendon hand primary or secondary without free graft", 6.78, "tendon_repair"),
    ("26412", "Repair extensor tendon hand primary or secondary with free graft", 8.45, "tendon_repair"),
    ("26415", "Excision extensor tendon with implantation of synthetic rod", 9.23, "tendon_repair"),
    ("26416", "Removal of synthetic rod and insertion of extensor tendon graft hand", 10.56, "tendon_repair"),
    ("26418", "Repair extensor tendon finger primary or secondary without free graft", 5.89, "tendon_repair"),
    ("26420", "Repair extensor tendon finger primary or secondary with free graft", 7.34, "tendon_repair"),
    ("26426", "Repair extensor tendon central slip secondary using local tissues including lateral band", 8.67, "tendon_repair"),
    ("26428", "Repair extensor tendon central slip secondary with free graft", 9.89, "tendon_repair"),
    ("26432", "Closed treatment of distal extensor tendon insertion mallet finger", 2.34, "tendon_repair"),
    ("26433", "Repair of extensor tendon distal insertion primary or secondary without graft", 5.12, "tendon_repair"),
    ("26434", "Repair of extensor tendon distal insertion primary or secondary with free graft", 6.78, "tendon_repair"),
    ("26437", "Realignment of extensor tendon hand subluxis", 6.23, "tendon_repair"),
    ("26440", "Tenolysis flexor tendon hand or finger", 7.89, "tendon_repair"),
    ("26442", "Tenolysis flexor tendon hand or finger each additional tendon", 3.45, "tendon_repair"),
    ("26445", "Tenolysis extensor tendon hand or finger", 6.56, "tendon_repair"),
    ("26449", "Tenolysis extensor tendon hand or finger each additional tendon", 3.12, "tendon_repair"),
    ("26450", "Tenotomy flexor finger single tendon open", 4.23, "tendon_repair"),
    ("26455", "Tenotomy flexor finger single tendon open each additional", 2.34, "tendon_repair"),
    ("26460", "Tenotomy extensor hand or finger open", 3.89, "tendon_repair"),
    ("26471", "Tenodesis of proximal interphalangeal joint single tendon", 5.67, "tendon_repair"),
    ("26474", "Tenodesis of distal joint single tendon", 5.23, "tendon_repair"),
    ("26476", "Lengthening of tendon extensor hand or finger single", 5.89, "tendon_repair"),
    ("26477", "Shortening of tendon extensor hand or finger single", 5.45, "tendon_repair"),
    ("26478", "Lengthening of tendon flexor hand or finger single", 6.23, "tendon_repair"),
    ("26479", "Shortening of tendon flexor hand or finger single", 5.78, "tendon_repair"),
    ("26480", "Transfer or transplant tendon hand palmar without free graft", 9.34, "tendon_repair"),
    ("26483", "Transfer or transplant tendon hand palmar without free graft each additional", 4.67, "tendon_repair"),
    ("26485", "Transfer or transplant tendon hand or finger dorsal without free graft", 9.12, "tendon_repair"),
    ("26489", "Transfer or transplant tendon hand or finger dorsal without free graft each additional", 4.23, "tendon_repair"),
    ("26490", "Opponensplasty superficialis tendon transfer type", 12.34, "tendon_repair"),
    ("26492", "Opponensplasty tendon transfer with graft including obtaining graft", 14.56, "tendon_repair"),
    ("26494", "Opponensplasty hypothenar muscle transfer", 10.78, "tendon_repair"),
    ("26496", "Opponensplasty other methods", 11.23, "tendon_repair"),
    ("26497", "Transfer of tendon to restore intrinsic function ring and small finger", 11.89, "tendon_repair"),
    ("26498", "Transfer of tendon to restore intrinsic function all four fingers", 14.23, "tendon_repair"),
    # Hand fracture treatment
    ("26600", "Closed treatment of metacarpal fracture single without manipulation", 2.56, "hand_fracture"),
    ("26605", "Closed treatment of metacarpal fracture single with manipulation", 4.34, "hand_fracture"),
    ("26607", "Closed treatment of metacarpal fracture with manipulation with external fixation", 6.78, "hand_fracture"),
    ("26608", "Percutaneous skeletal fixation of metacarpal fracture", 7.89, "hand_fracture"),
    ("26615", "Open treatment of metacarpal fracture single with internal fixation", 9.45, "hand_fracture"),
    ("26641", "Closed treatment of carpometacarpal dislocation thumb with manipulation", 4.89, "hand_fracture"),
    ("26645", "Closed treatment of carpometacarpal fracture dislocation thumb with manipulation", 5.67, "hand_fracture"),
    ("26650", "Percutaneous skeletal fixation of carpometacarpal fracture dislocation thumb", 7.23, "hand_fracture"),
    ("26665", "Open treatment of carpometacarpal fracture dislocation thumb with internal fixation", 10.34, "hand_fracture"),
    ("26670", "Closed treatment of carpometacarpal dislocation other than thumb with manipulation", 4.56, "hand_fracture"),
    ("26675", "Closed treatment of carpometacarpal fracture dislocation other than thumb with manipulation", 5.12, "hand_fracture"),
    ("26676", "Percutaneous skeletal fixation of carpometacarpal fracture dislocation other than thumb", 6.89, "hand_fracture"),
    ("26685", "Open treatment of carpometacarpal fracture dislocation other than thumb with fixation", 9.67, "hand_fracture"),
    ("26686", "Open treatment of carpometacarpal fracture dislocation other than thumb complex multiple or delayed", 12.34, "hand_fracture"),
    ("26700", "Closed treatment of metacarpophalangeal dislocation single with manipulation", 3.89, "hand_fracture"),
    ("26705", "Open treatment of metacarpophalangeal dislocation single includes internal fixation when performed", 7.56, "hand_fracture"),
    ("26706", "Percutaneous skeletal fixation of metacarpophalangeal dislocation single with manipulation", 5.67, "hand_fracture"),
    ("26715", "Open treatment of metacarpophalangeal dislocation single complex includes internal fixation", 9.34, "hand_fracture"),
    ("26720", "Closed treatment of phalangeal shaft fracture proximal or middle phalanx finger without manipulation", 2.12, "hand_fracture"),
    ("26725", "Closed treatment of phalangeal shaft fracture proximal or middle phalanx finger with manipulation", 3.89, "hand_fracture"),
    ("26727", "Percutaneous skeletal fixation of unstable phalangeal shaft fracture proximal or middle phalanx", 6.45, "hand_fracture"),
    ("26735", "Open treatment of phalangeal shaft fracture proximal or middle phalanx with internal fixation", 8.67, "hand_fracture"),
    ("26740", "Closed treatment of articular fracture involving metacarpophalangeal or interphalangeal joint without manipulation", 2.56, "hand_fracture"),
    ("26742", "Closed treatment of articular fracture involving metacarpophalangeal or interphalangeal joint with manipulation", 4.23, "hand_fracture"),
    ("26746", "Open treatment of articular fracture involving metacarpophalangeal or interphalangeal joint with internal fixation", 9.12, "hand_fracture"),
    ("26750", "Closed treatment of distal phalangeal fracture finger without manipulation", 1.89, "hand_fracture"),
    ("26755", "Closed treatment of distal phalangeal fracture finger with manipulation", 3.12, "hand_fracture"),
    ("26756", "Percutaneous skeletal fixation of distal phalangeal fracture finger", 5.23, "hand_fracture"),
    ("26765", "Open treatment of distal phalangeal fracture finger with internal fixation", 6.78, "hand_fracture"),
    ("26770", "Closed treatment of interphalangeal joint dislocation single without anesthesia", 2.34, "hand_fracture"),
    ("26775", "Closed treatment of interphalangeal joint dislocation single requiring anesthesia", 3.89, "hand_fracture"),
    ("26776", "Percutaneous skeletal fixation of interphalangeal joint dislocation single with manipulation", 5.56, "hand_fracture"),
    ("26785", "Open treatment of interphalangeal joint dislocation with internal fixation", 7.89, "hand_fracture"),
    # Hand arthroplasty
    ("26530", "Arthroplasty metacarpophalangeal joint each joint", 9.23, "hand_arthroplasty"),
    ("26531", "Arthroplasty metacarpophalangeal joint with prosthetic implant each joint", 10.56, "hand_arthroplasty"),
    ("26535", "Arthroplasty interphalangeal joint each joint", 8.67, "hand_arthroplasty"),
    ("26536", "Arthroplasty interphalangeal joint with prosthetic implant each joint", 9.89, "hand_arthroplasty"),
    # Other hand procedures
    ("26010", "Drainage of finger abscess simple", 2.89, "hand_misc"),
    ("26011", "Drainage of finger abscess complicated", 4.56, "hand_misc"),
    ("26020", "Drainage of tendon sheath digit and/or palm each", 5.23, "hand_misc"),
    ("26025", "Drainage of palmar bursa each", 5.89, "hand_misc"),
    ("26030", "Drainage of palmar bursa each incision each", 6.34, "hand_misc"),
    ("26034", "Incision bone cortex hand or finger", 6.78, "hand_misc"),
    ("26035", "Decompressive fasciotomy hand Dupuytren contracture open partial", 7.89, "hand_misc"),
    ("26037", "Decompressive fasciotomy hand Dupuytren contracture open total", 10.23, "hand_misc"),
    ("26040", "Fasciotomy palmar open", 6.45, "hand_misc"),
    ("26045", "Fasciotomy palmar open with release of single digit including 1st web", 8.67, "hand_misc"),
    ("26055", "Tendon sheath incision open flexor", 4.56, "hand_misc"),
    ("26060", "Tenotomy percutaneous single each", 2.34, "hand_misc"),
    ("26070", "Arthrotomy with exploration drainage or removal of foreign body carpometacarpal joint", 5.67, "hand_misc"),
    ("26075", "Arthrotomy with exploration drainage or removal of foreign body metacarpophalangeal joint", 5.23, "hand_misc"),
    ("26080", "Arthrotomy with exploration drainage or removal of foreign body interphalangeal joint", 4.89, "hand_misc"),
    ("26100", "Arthrotomy with biopsy carpometacarpal joint", 4.67, "hand_misc"),
    ("26105", "Arthrotomy with biopsy metacarpophalangeal joint", 4.34, "hand_misc"),
    ("26110", "Arthrotomy with biopsy interphalangeal joint", 4.12, "hand_misc"),
    ("26115", "Excision of tumor or vascular malformation soft tissue of hand or finger subcutaneous", 4.56, "hand_misc"),
    ("26116", "Excision of tumor or vascular malformation soft tissue of hand or finger subfascial", 7.23, "hand_misc"),
    ("26117", "Radical resection of tumor soft tissue of hand or finger", 12.34, "hand_misc"),
    ("26121", "Fasciotomy palm only with release Dupuytren contracture open partial", 7.45, "hand_misc"),
    ("26123", "Fasciotomy palm only with release Dupuytren contracture open radical", 10.67, "hand_misc"),
    ("26125", "Fasciotomy palm only with release Dupuytren contracture open radical each additional ray", 4.23, "hand_misc"),
    ("26130", "Synovectomy metacarpophalangeal joint including intrinsic release and extensor hood reconstruction", 8.89, "hand_misc"),
    ("26135", "Synovectomy proximal interphalangeal joint including extensor reconstruction", 7.67, "hand_misc"),
    ("26140", "Synovectomy proximal interphalangeal joint including volar capsulodesis", 8.23, "hand_misc"),
    ("26145", "Synovectomy tendon sheath hand or finger radical", 6.78, "hand_misc"),
    ("26160", "Excision of lesion of tendon sheath or capsule hand or finger", 4.89, "hand_misc"),
    ("26170", "Excision of tumor metacarpal each", 6.34, "hand_misc"),
    ("26180", "Excision of tumor phalanx of finger each", 5.67, "hand_misc"),
    ("26185", "Sesamoidectomy thumb or finger each", 4.23, "hand_misc"),
    ("26200", "Excision or curettage of cyst or benign tumor of metacarpal", 5.89, "hand_misc"),
    ("26205", "Excision or curettage of cyst or benign tumor of metacarpal with autograft", 7.56, "hand_misc"),
    ("26210", "Excision or curettage of cyst or benign tumor of proximal middle or distal phalanx of finger", 5.12, "hand_misc"),
    ("26215", "Excision or curettage of cyst or benign tumor of proximal middle or distal phalanx with autograft", 7.23, "hand_misc"),
    ("26230", "Partial excision of bone metacarpal for tumor", 7.89, "hand_misc"),
    ("26235", "Partial excision of bone proximal or middle phalanx for tumor", 6.78, "hand_misc"),
    ("26236", "Partial excision of bone distal phalanx for tumor", 5.34, "hand_misc"),
    ("26250", "Radical resection metacarpal", 12.56, "hand_misc"),
    ("26260", "Radical resection proximal or middle phalanx", 10.34, "hand_misc"),
    ("26261", "Radical resection proximal or middle phalanx with autograft", 12.78, "hand_misc"),
    ("26262", "Radical resection distal phalanx", 8.56, "hand_misc"),
    ("26320", "Capsulodesis metacarpophalangeal joint", 7.34, "hand_misc"),
    ("26340", "Manipulation finger joint under anesthesia", 2.89, "hand_misc"),
    ("26341", "Manipulation palmar fascial cord post enzyme injection", 2.45, "hand_misc"),
    ("26500", "Reconstruction tendon pulley each tendon", 8.23, "hand_misc"),
    ("26502", "Reconstruction tendon pulley each tendon with tendon or fascial graft", 10.45, "hand_misc"),
    ("26508", "Release of thenar muscle", 5.67, "hand_misc"),
    ("26510", "Cross intrinsic transfer each tendon", 9.12, "hand_misc"),
    ("26516", "Capsulodesis metacarpophalangeal joint single digit", 6.78, "hand_misc"),
    ("26517", "Capsulodesis metacarpophalangeal joint 2 digits", 8.34, "hand_misc"),
    ("26518", "Capsulodesis metacarpophalangeal joint 3 or 4 digits", 10.56, "hand_misc"),
    ("26520", "Capsulectomy or capsulotomy metacarpophalangeal joint each", 5.89, "hand_misc"),
    ("26525", "Capsulectomy or capsulotomy interphalangeal joint each", 5.23, "hand_misc"),
    ("26540", "Repair of collateral ligament metacarpophalangeal or interphalangeal joint", 6.78, "hand_misc"),
    ("26541", "Reconstruction of collateral ligament metacarpophalangeal joint single with tendon graft", 9.34, "hand_misc"),
    ("26542", "Reconstruction of collateral ligament interphalangeal joint single with tendon graft", 8.89, "hand_misc"),
    ("26545", "Reconstruction of collateral ligament metacarpophalangeal joint with local tissue", 8.12, "hand_misc"),
    ("26546", "Repair of non-union or malunion metacarpal or phalanx", 10.45, "hand_misc"),
    ("26548", "Repair and reconstruction fingertip with flap", 7.56, "hand_misc"),
    ("26550", "Pollicization of a digit", 18.67, "hand_misc"),
    ("26551", "Transfer toe to hand with microvascular anastomosis", 30.23, "hand_misc"),
    ("26553", "Transfer single toe to hand with microvascular anastomosis including metatarsal", 32.45, "hand_misc"),
    ("26554", "Transfer of toes to hand with microvascular anastomosis other than great toe", 28.67, "hand_misc"),
    ("26555", "Transfer of finger to opposite hand single", 22.34, "hand_misc"),
    ("26556", "Transfer of free toe joint with microvascular anastomosis", 25.67, "hand_misc"),
    ("26560", "Repair of syndactyly each web space with skin flaps and grafts", 10.89, "hand_misc"),
    ("26561", "Repair of syndactyly each web space complex", 14.23, "hand_misc"),
    ("26562", "Repair of syndactyly each web space complex with bone or joint", 16.45, "hand_misc"),
    ("26565", "Osteotomy metacarpal each", 8.67, "hand_misc"),
    ("26567", "Osteotomy phalanx of finger each", 7.89, "hand_misc"),
    ("26568", "Osteoplasty lengthening metacarpal or phalanx", 12.34, "hand_misc"),
    ("26580", "Repair cleft hand", 16.78, "hand_misc"),
    ("26587", "Reconstruction polydactylous digit soft tissue and bone", 14.56, "hand_misc"),
    ("26590", "Repair macrodactylia each digit", 12.34, "hand_misc"),
    ("26591", "Repair intrinsic muscles hand each muscle", 7.23, "hand_misc"),
    ("26593", "Release intrinsic muscles hand each muscle", 5.67, "hand_misc"),
    ("26596", "Excision constricting ring finger with multiple Z-plasties", 6.89, "hand_misc"),
    ("26910", "Amputation metacarpal with finger single", 6.78, "hand_misc"),
    ("26951", "Amputation finger or thumb primary or secondary any joint or phalanx", 4.56, "hand_misc"),
    ("26952", "Amputation finger or thumb with local advancement flap", 6.34, "hand_misc"),
    ("26989", "Unlisted procedure hands or fingers", 0.00, "hand_misc"),
]
for code, desc, rvu, fam in hand_surgery:
    new_codes[code] = make_cpt(code, desc, spec="hand_surgery", rvu=rvu, bilat=True, family=fam)

# Nerve repair (hand/upper extremity)
nerve_repair = [
    ("64831", "Suture of digital nerve hand or foot one nerve", 7.23),
    ("64832", "Suture of digital nerve hand or foot each additional nerve", 3.56),
    ("64834", "Suture of one nerve hand or foot common sensory nerve", 8.45),
    ("64835", "Suture of one nerve hand or foot median motor thenar", 9.67),
    ("64836", "Suture of one nerve hand or foot ulnar motor", 9.89),
    ("64837", "Suture of each additional nerve hand or foot", 4.12),
    ("64840", "Suture of posterior tibial nerve", 10.34),
    ("64856", "Suture of major peripheral nerve arm or leg except sciatic", 12.45),
    ("64857", "Suture of major peripheral nerve arm or leg except sciatic with transposition", 14.23),
    ("64858", "Suture of sciatic nerve", 15.67),
    ("64859", "Suture of each additional major peripheral nerve", 5.89),
    ("64861", "Suture of brachial plexus", 18.23),
    ("64862", "Suture of lumbar plexus", 16.78),
    ("64864", "Suture of facial nerve extracranial", 14.56),
    ("64865", "Suture of facial nerve intratemporal with or without grafting", 20.34),
    ("64866", "Anastomosis facial-spinal accessory", 16.89),
    ("64868", "Anastomosis facial-hypoglossal", 17.23),
    ("64872", "Suture of nerve requiring secondary or delayed suture", 10.78),
    ("64874", "Suture of nerve requiring extensive mobilization or transposition", 13.45),
    ("64876", "Suture of nerve requiring shortening of bone", 15.89),
    ("64885", "Nerve graft head or neck up to 4 cm in length", 14.67),
    ("64886", "Nerve graft head or neck more than 4 cm length", 17.89),
    ("64890", "Nerve graft hand or foot single strand up to 4 cm", 12.34),
    ("64891", "Nerve graft hand or foot single strand more than 4 cm", 14.56),
    ("64892", "Nerve graft hand or foot each additional strand", 5.23),
    ("64893", "Nerve graft hand or foot multiple strands up to 4 cm", 15.67),
    ("64895", "Nerve graft hand or foot multiple strands more than 4 cm", 17.89),
    ("64896", "Nerve graft each additional strand", 5.34),
    ("64897", "Nerve graft arm or leg single strand up to 4 cm", 13.45),
    ("64898", "Nerve graft arm or leg single strand more than 4 cm", 15.67),
    ("64901", "Nerve graft each additional single strand", 5.12),
    ("64902", "Nerve graft arm or leg multiple strands up to 4 cm", 16.78),
    ("64905", "Nerve pedicle transfer first stage", 14.23),
    ("64907", "Nerve pedicle transfer second stage", 12.56),
    ("64910", "Nerve repair with synthetic conduit single nerve", 10.89),
    ("64911", "Nerve repair with autogenous vein conduit single nerve", 12.34),
    ("64912", "Nerve repair with nerve allograft first strand", 13.45),
    ("64913", "Nerve repair with nerve allograft each additional strand", 5.67),
]
for code, desc, rvu in nerve_repair:
    new_codes[code] = make_cpt(code, desc, spec="hand_surgery", rvu=rvu, family="nerve_repair")

# ============================================================
# 3. DERMATOLOGY (200+ codes)
# ============================================================

derm_codes = [
    # Mohs surgery
    ("17311", "Mohs micrographic technique including removal of all gross tumor first stage up to 5 tissue blocks head neck hands feet genitalia", 7.89, "mohs_surgery"),
    ("17312", "Mohs micrographic technique each additional block first stage", 2.34, "mohs_surgery"),
    ("17313", "Mohs micrographic technique including removal of all gross tumor second stage any size", 5.67, "mohs_surgery"),
    ("17314", "Mohs micrographic technique each additional block any stage", 2.12, "mohs_surgery"),
    ("17315", "Mohs micrographic technique including removal of all gross tumor trunk arms legs", 6.78, "mohs_surgery"),
    # Destruction of lesions
    ("17000", "Destruction benign or premalignant lesions first lesion", 1.23, "destruction_lesion"),
    ("17003", "Destruction benign or premalignant lesions second through 14 each additional", 0.12, "destruction_lesion"),
    ("17004", "Destruction benign or premalignant lesions 15 or more", 3.45, "destruction_lesion"),
    ("17106", "Destruction of cutaneous vascular proliferative lesions less than 10 sq cm", 3.78, "destruction_lesion"),
    ("17107", "Destruction of cutaneous vascular proliferative lesions 10-50 sq cm", 5.34, "destruction_lesion"),
    ("17108", "Destruction of cutaneous vascular proliferative lesions over 50 sq cm", 7.89, "destruction_lesion"),
    ("17110", "Destruction of benign lesions other than skin tags or cutaneous vascular proliferative lesions up to 14", 1.56, "destruction_lesion"),
    ("17111", "Destruction of benign lesions other than skin tags or cutaneous vascular proliferative lesions 15+", 2.89, "destruction_lesion"),
    ("17250", "Chemical cauterization of granulation tissue", 0.89, "destruction_lesion"),
    ("17260", "Destruction malignant lesion any method trunk arms or legs lesion diameter 0.5 cm or less", 1.67, "destruction_lesion"),
    ("17261", "Destruction malignant lesion any method trunk arms or legs lesion diameter 0.6-1.0 cm", 2.12, "destruction_lesion"),
    ("17262", "Destruction malignant lesion any method trunk arms or legs lesion diameter 1.1-2.0 cm", 2.56, "destruction_lesion"),
    ("17263", "Destruction malignant lesion any method trunk arms or legs lesion diameter 2.1-3.0 cm", 3.12, "destruction_lesion"),
    ("17264", "Destruction malignant lesion any method trunk arms or legs lesion diameter 3.1-4.0 cm", 3.67, "destruction_lesion"),
    ("17266", "Destruction malignant lesion any method trunk arms or legs lesion diameter over 4.0 cm", 4.23, "destruction_lesion"),
    ("17270", "Destruction malignant lesion any method scalp neck hands feet genitalia 0.5 cm or less", 1.89, "destruction_lesion"),
    ("17271", "Destruction malignant lesion any method scalp neck hands feet genitalia 0.6-1.0 cm", 2.34, "destruction_lesion"),
    ("17272", "Destruction malignant lesion any method scalp neck hands feet genitalia 1.1-2.0 cm", 2.78, "destruction_lesion"),
    ("17273", "Destruction malignant lesion any method scalp neck hands feet genitalia 2.1-3.0 cm", 3.34, "destruction_lesion"),
    ("17274", "Destruction malignant lesion any method scalp neck hands feet genitalia 3.1-4.0 cm", 3.89, "destruction_lesion"),
    ("17276", "Destruction malignant lesion any method scalp neck hands feet genitalia over 4.0 cm", 4.45, "destruction_lesion"),
    ("17280", "Destruction malignant lesion any method face ears eyelids nose lips mucous membrane 0.5 cm or less", 2.12, "destruction_lesion"),
    ("17281", "Destruction malignant lesion any method face ears eyelids nose lips 0.6-1.0 cm", 2.56, "destruction_lesion"),
    ("17282", "Destruction malignant lesion any method face ears eyelids nose lips 1.1-2.0 cm", 3.12, "destruction_lesion"),
    ("17283", "Destruction malignant lesion any method face ears eyelids nose lips 2.1-3.0 cm", 3.67, "destruction_lesion"),
    ("17284", "Destruction malignant lesion any method face ears eyelids nose lips 3.1-4.0 cm", 4.23, "destruction_lesion"),
    ("17286", "Destruction malignant lesion any method face ears eyelids nose lips over 4.0 cm", 4.78, "destruction_lesion"),
    # Skin tag removal
    ("11200", "Removal of skin tags multiple fibrocutaneous tags any area up to and including 15 lesions", 1.12, "skin_tag"),
    ("11201", "Removal of skin tags each additional 10 lesions or part thereof", 0.45, "skin_tag"),
    # Shaving of lesions
    ("11300", "Shaving of epidermal or dermal lesion trunk arms or legs 0.5 cm or less", 0.89, "shaving_lesion"),
    ("11301", "Shaving of epidermal or dermal lesion trunk arms or legs 0.6-1.0 cm", 1.12, "shaving_lesion"),
    ("11302", "Shaving of epidermal or dermal lesion trunk arms or legs 1.1-2.0 cm", 1.34, "shaving_lesion"),
    ("11303", "Shaving of epidermal or dermal lesion trunk arms or legs over 2.0 cm", 1.56, "shaving_lesion"),
    ("11305", "Shaving of epidermal or dermal lesion scalp neck hands feet genitalia 0.5 cm or less", 0.89, "shaving_lesion"),
    ("11306", "Shaving of epidermal or dermal lesion scalp neck hands feet genitalia 0.6-1.0 cm", 1.12, "shaving_lesion"),
    ("11307", "Shaving of epidermal or dermal lesion scalp neck hands feet genitalia 1.1-2.0 cm", 1.34, "shaving_lesion"),
    ("11308", "Shaving of epidermal or dermal lesion scalp neck hands feet genitalia over 2.0 cm", 1.56, "shaving_lesion"),
    ("11310", "Shaving of epidermal or dermal lesion face ears eyelids nose lips 0.5 cm or less", 1.12, "shaving_lesion"),
    ("11311", "Shaving of epidermal or dermal lesion face ears eyelids nose lips 0.6-1.0 cm", 1.34, "shaving_lesion"),
    ("11312", "Shaving of epidermal or dermal lesion face ears eyelids nose lips 1.1-2.0 cm", 1.56, "shaving_lesion"),
    ("11313", "Shaving of epidermal or dermal lesion face ears eyelids nose lips over 2.0 cm", 1.78, "shaving_lesion"),
    # Excision lesions
    ("11400", "Excision benign lesion including margins trunk arms or legs 0.5 cm or less", 2.12, "excision_lesion"),
    ("11401", "Excision benign lesion including margins trunk arms or legs 0.6-1.0 cm", 2.56, "excision_lesion"),
    ("11402", "Excision benign lesion including margins trunk arms or legs 1.1-2.0 cm", 3.12, "excision_lesion"),
    ("11403", "Excision benign lesion including margins trunk arms or legs 2.1-3.0 cm", 3.67, "excision_lesion"),
    ("11404", "Excision benign lesion including margins trunk arms or legs 3.1-4.0 cm", 4.23, "excision_lesion"),
    ("11406", "Excision benign lesion including margins trunk arms or legs over 4.0 cm", 5.34, "excision_lesion"),
    ("11420", "Excision benign lesion including margins scalp neck hands feet genitalia 0.5 cm or less", 2.34, "excision_lesion"),
    ("11421", "Excision benign lesion including margins scalp neck hands feet genitalia 0.6-1.0 cm", 2.78, "excision_lesion"),
    ("11422", "Excision benign lesion including margins scalp neck hands feet genitalia 1.1-2.0 cm", 3.34, "excision_lesion"),
    ("11423", "Excision benign lesion including margins scalp neck hands feet genitalia 2.1-3.0 cm", 3.89, "excision_lesion"),
    ("11424", "Excision benign lesion including margins scalp neck hands feet genitalia 3.1-4.0 cm", 4.45, "excision_lesion"),
    ("11426", "Excision benign lesion including margins scalp neck hands feet genitalia over 4.0 cm", 5.56, "excision_lesion"),
    ("11440", "Excision benign lesion including margins face ears eyelids nose lips 0.5 cm or less", 2.56, "excision_lesion"),
    ("11441", "Excision benign lesion including margins face ears eyelids nose lips 0.6-1.0 cm", 3.12, "excision_lesion"),
    ("11442", "Excision benign lesion including margins face ears eyelids nose lips 1.1-2.0 cm", 3.67, "excision_lesion"),
    ("11443", "Excision benign lesion including margins face ears eyelids nose lips 2.1-3.0 cm", 4.23, "excision_lesion"),
    ("11444", "Excision benign lesion including margins face ears eyelids nose lips 3.1-4.0 cm", 4.89, "excision_lesion"),
    ("11446", "Excision benign lesion including margins face ears eyelids nose lips over 4.0 cm", 5.89, "excision_lesion"),
    ("11600", "Excision malignant lesion including margins trunk arms or legs 0.5 cm or less", 2.89, "excision_lesion"),
    ("11601", "Excision malignant lesion including margins trunk arms or legs 0.6-1.0 cm", 3.34, "excision_lesion"),
    ("11602", "Excision malignant lesion including margins trunk arms or legs 1.1-2.0 cm", 3.89, "excision_lesion"),
    ("11603", "Excision malignant lesion including margins trunk arms or legs 2.1-3.0 cm", 4.45, "excision_lesion"),
    ("11604", "Excision malignant lesion including margins trunk arms or legs 3.1-4.0 cm", 5.12, "excision_lesion"),
    ("11606", "Excision malignant lesion including margins trunk arms or legs over 4.0 cm", 6.34, "excision_lesion"),
    ("11620", "Excision malignant lesion including margins scalp neck hands feet genitalia 0.5 cm or less", 3.12, "excision_lesion"),
    ("11621", "Excision malignant lesion including margins scalp neck hands feet genitalia 0.6-1.0 cm", 3.56, "excision_lesion"),
    ("11622", "Excision malignant lesion including margins scalp neck hands feet genitalia 1.1-2.0 cm", 4.12, "excision_lesion"),
    ("11623", "Excision malignant lesion including margins scalp neck hands feet genitalia 2.1-3.0 cm", 4.67, "excision_lesion"),
    ("11624", "Excision malignant lesion including margins scalp neck hands feet genitalia 3.1-4.0 cm", 5.34, "excision_lesion"),
    ("11626", "Excision malignant lesion including margins scalp neck hands feet genitalia over 4.0 cm", 6.56, "excision_lesion"),
    ("11640", "Excision malignant lesion including margins face ears eyelids nose lips 0.5 cm or less", 3.34, "excision_lesion"),
    ("11641", "Excision malignant lesion including margins face ears eyelids nose lips 0.6-1.0 cm", 3.89, "excision_lesion"),
    ("11642", "Excision malignant lesion including margins face ears eyelids nose lips 1.1-2.0 cm", 4.45, "excision_lesion"),
    ("11643", "Excision malignant lesion including margins face ears eyelids nose lips 2.1-3.0 cm", 5.12, "excision_lesion"),
    ("11644", "Excision malignant lesion including margins face ears eyelids nose lips 3.1-4.0 cm", 5.78, "excision_lesion"),
    ("11646", "Excision malignant lesion including margins face ears eyelids nose lips over 4.0 cm", 7.12, "excision_lesion"),
    # Biopsy
    ("11102", "Tangential biopsy of skin first lesion", 0.67, "skin_biopsy"),
    ("11103", "Tangential biopsy of skin each additional lesion", 0.34, "skin_biopsy"),
    ("11104", "Punch biopsy of skin first lesion", 0.78, "skin_biopsy"),
    ("11105", "Punch biopsy of skin each additional lesion", 0.34, "skin_biopsy"),
    ("11106", "Incisional biopsy of skin first lesion", 1.23, "skin_biopsy"),
    ("11107", "Incisional biopsy of skin each additional lesion", 0.56, "skin_biopsy"),
    # Debridement
    ("11042", "Debridement subcutaneous tissue first 20 sq cm", 2.34, "debridement"),
    ("11043", "Debridement muscle and/or fascia first 20 sq cm", 3.56, "debridement"),
    ("11044", "Debridement bone first 20 sq cm", 4.78, "debridement"),
    ("11045", "Debridement subcutaneous tissue each additional 20 sq cm", 0.89, "debridement"),
    ("11046", "Debridement muscle and/or fascia each additional 20 sq cm", 1.12, "debridement"),
    ("11047", "Debridement bone each additional 20 sq cm", 1.34, "debridement"),
    # Wound care/skin substitutes
    ("15002", "Surgical preparation or creation of recipient site by excision of open wounds burn eschar first 100 sq cm trunk arms legs", 3.89, "wound_care"),
    ("15003", "Surgical preparation each additional 100 sq cm trunk arms legs", 1.23, "wound_care"),
    ("15004", "Surgical preparation or creation of recipient site first 100 sq cm face scalp eyelids mouth neck ears orbits genitalia hands feet", 4.56, "wound_care"),
    ("15005", "Surgical preparation each additional 100 sq cm face scalp eyelids mouth neck ears", 1.34, "wound_care"),
    ("15040", "Harvest of skin for tissue cultured skin autograft 100 sq cm or less", 3.67, "wound_care"),
    ("15050", "Pinch graft single or multiple to cover small ulcer tip of digit or other defect", 3.12, "wound_care"),
    ("15100", "Split-thickness autograft trunk arms legs first 100 sq cm or less", 7.89, "wound_care"),
    ("15101", "Split-thickness autograft trunk arms legs each additional 100 sq cm", 2.34, "wound_care"),
    ("15110", "Epidermal autograft trunk arms legs first 100 sq cm or less", 4.56, "wound_care"),
    ("15111", "Epidermal autograft trunk arms legs each additional 100 sq cm", 1.67, "wound_care"),
    ("15115", "Epidermal autograft face scalp eyelids mouth neck ears first 100 sq cm or less", 5.23, "wound_care"),
    ("15116", "Epidermal autograft face scalp eyelids mouth neck ears each additional 100 sq cm", 1.89, "wound_care"),
    ("15120", "Split-thickness autograft face scalp eyelids mouth neck ears first 100 sq cm or less", 8.56, "wound_care"),
    ("15121", "Split-thickness autograft face scalp eyelids mouth neck ears each additional 100 sq cm", 2.56, "wound_care"),
    ("15130", "Dermal autograft trunk arms legs first 100 sq cm or less", 6.78, "wound_care"),
    ("15131", "Dermal autograft trunk arms legs each additional 100 sq cm", 2.12, "wound_care"),
    ("15135", "Dermal autograft face scalp eyelids mouth neck ears first 100 sq cm or less", 7.23, "wound_care"),
    ("15136", "Dermal autograft face scalp eyelids mouth neck ears each additional 100 sq cm", 2.34, "wound_care"),
    ("15150", "Tissue cultured skin autograft trunk arms legs first 25 sq cm or less", 4.56, "wound_care"),
    ("15151", "Tissue cultured skin autograft trunk arms legs additional 25 sq cm each", 1.45, "wound_care"),
    ("15152", "Tissue cultured skin autograft face scalp eyelids mouth neck ears first 25 sq cm", 5.12, "wound_care"),
    ("15155", "Tissue cultured skin autograft face scalp eyelids mouth each additional 25 sq cm", 1.67, "wound_care"),
    ("15200", "Full thickness graft free including direct closure of donor site trunk 20 sq cm or less", 7.45, "wound_care"),
    ("15201", "Full thickness graft free including direct closure of donor site trunk each additional 20 sq cm", 2.34, "wound_care"),
    ("15220", "Full thickness graft free including direct closure scalp arms hands feet 20 sq cm or less", 8.23, "wound_care"),
    ("15221", "Full thickness graft free including direct closure scalp arms hands feet each additional 20 sq cm", 2.56, "wound_care"),
    ("15240", "Full thickness graft free including direct closure forehead eyelids nose ears lips 20 sq cm or less", 9.67, "wound_care"),
    ("15241", "Full thickness graft free including direct closure forehead eyelids nose ears lips each additional 20 sq cm", 2.89, "wound_care"),
    ("15260", "Full thickness graft free including direct closure nose ears eyelids mouth 20 sq cm or less", 10.23, "wound_care"),
    ("15261", "Full thickness graft free including direct closure nose ears eyelids mouth each additional 20 sq cm", 3.12, "wound_care"),
    # Flaps
    ("14000", "Adjacent tissue transfer or rearrangement trunk defect 10 sq cm or less", 6.45, "flap"),
    ("14001", "Adjacent tissue transfer or rearrangement trunk defect 10.1-30 sq cm", 8.67, "flap"),
    ("14020", "Adjacent tissue transfer or rearrangement scalp arms legs defect 10 sq cm or less", 6.89, "flap"),
    ("14021", "Adjacent tissue transfer or rearrangement scalp arms legs defect 10.1-30 sq cm", 9.12, "flap"),
    ("14040", "Adjacent tissue transfer or rearrangement forehead cheeks chin mouth neck nose defect 10 sq cm or less", 8.34, "flap"),
    ("14041", "Adjacent tissue transfer or rearrangement forehead cheeks chin mouth neck nose defect 10.1-30 sq cm", 10.56, "flap"),
    ("14060", "Adjacent tissue transfer or rearrangement eyelids nose ears lips defect 10 sq cm or less", 9.78, "flap"),
    ("14061", "Adjacent tissue transfer or rearrangement eyelids nose ears lips defect 10.1-30 sq cm", 12.34, "flap"),
    ("14301", "Adjacent tissue transfer or rearrangement any area defect 30.1-60 sq cm", 14.56, "flap"),
    ("14302", "Adjacent tissue transfer or rearrangement any area each additional 30 sq cm", 4.89, "flap"),
    # Phototherapy
    ("96910", "Photochemotherapy; tar and ultraviolet B (Goeckerman treatment)", 1.56, "phototherapy"),
    ("96912", "Photochemotherapy; psoralens and ultraviolet A (PUVA)", 1.89, "phototherapy"),
    ("96913", "Photochemotherapy; photochemotherapy of severe dermatoses requiring 4-8 hours of care under direct supervision", 3.23, "phototherapy"),
    ("96920", "Laser treatment for inflammatory skin disease irradiated area less than 250 sq cm", 2.34, "phototherapy"),
    ("96921", "Laser treatment for inflammatory skin disease 250-500 sq cm", 2.89, "phototherapy"),
    ("96922", "Laser treatment for inflammatory skin disease over 500 sq cm", 3.45, "phototherapy"),
    # Dermatology miscellaneous
    ("96900", "Actinotherapy ultraviolet light", 0.34, "derm_misc"),
    ("96902", "Microscopic examination of hairs plucked or clipped by examiner", 0.45, "derm_misc"),
    ("96904", "Whole body integumentary photography", 0.78, "derm_misc"),
    ("96999", "Unlisted special dermatological service or procedure", 0.00, "derm_misc"),
]
for code, desc, rvu, fam in derm_codes:
    new_codes[code] = make_cpt(code, desc, cat="Surgery" if rvu > 1 else "Medicine", spec="dermatology", rvu=rvu, glob=10 if "Mohs" in desc else 0, family=fam)

# ============================================================
# 4. INTERVENTIONAL CARDIOLOGY (200+ codes)
# ============================================================

cardio_codes = [
    # PCI codes
    ("92920", "Percutaneous transluminal coronary angioplasty single major coronary artery or branch", 12.34, "pci", 0),
    ("92921", "Percutaneous transluminal coronary angioplasty each additional branch of a major coronary artery", 4.56, "pci", 0),
    ("92924", "Percutaneous transluminal coronary atherectomy with coronary angioplasty single vessel", 13.89, "pci", 0),
    ("92925", "Percutaneous transluminal coronary atherectomy with coronary angioplasty each additional vessel", 5.23, "pci", 0),
    ("92928", "Percutaneous transcatheter placement of intracoronary stent single vessel", 14.56, "pci", 0),
    ("92929", "Percutaneous transcatheter placement of intracoronary stent each additional vessel", 5.67, "pci", 0),
    ("92933", "Percutaneous transluminal coronary atherectomy with intracoronary stent single vessel", 15.23, "pci", 0),
    ("92934", "Percutaneous transluminal coronary atherectomy with intracoronary stent each additional vessel", 5.89, "pci", 0),
    ("92937", "Percutaneous transluminal revascularization of or through coronary artery bypass graft single vessel", 14.78, "pci", 0),
    ("92938", "Percutaneous transluminal revascularization of or through coronary artery bypass graft each additional vessel", 5.34, "pci", 0),
    ("92941", "Percutaneous transluminal revascularization of acute total/subtotal occlusion during acute myocardial infarction", 16.34, "pci", 0),
    ("92943", "Percutaneous transluminal revascularization of chronic total occlusion coronary artery single vessel", 17.89, "pci", 0),
    ("92944", "Percutaneous transluminal revascularization of chronic total occlusion each additional coronary artery", 6.12, "pci", 0),
    ("92973", "Percutaneous transluminal coronary thrombectomy mechanical", 3.56, "pci", 0),
    ("92974", "Transcatheter placement of radiation delivery device for coronary intravascular brachytherapy", 4.23, "pci", 0),
    ("92975", "Thrombolysis coronary by intracoronary infusion", 5.67, "pci", 0),
    ("92977", "Thrombolysis coronary by intravenous infusion", 3.12, "pci", 0),
    ("92978", "Endoluminal imaging of coronary vessel or graft using intravascular ultrasound during diagnostic evaluation", 2.34, "pci", 0),
    ("92979", "Endoluminal imaging of coronary vessel or graft using intravascular ultrasound during therapeutic intervention", 2.56, "pci", 0),
    ("92986", "Percutaneous balloon valvuloplasty aortic valve", 15.67, "pci", 0),
    ("92987", "Percutaneous balloon valvuloplasty mitral valve", 16.23, "pci", 0),
    ("92990", "Percutaneous balloon valvuloplasty pulmonary valve", 14.56, "pci", 0),
    ("92997", "Percutaneous transluminal pulmonary artery balloon angioplasty single vessel", 12.89, "pci", 0),
    ("92998", "Percutaneous transluminal pulmonary artery balloon angioplasty each additional vessel", 4.67, "pci", 0),
    # Electrophysiology
    ("93600", "Bundle of His recording", 3.45, "electrophysiology", 0),
    ("93602", "Intra-atrial recording", 2.89, "electrophysiology", 0),
    ("93603", "Right ventricular recording", 2.78, "electrophysiology", 0),
    ("93609", "Intraventricular and/or intra-atrial mapping of tachycardia site", 6.34, "electrophysiology", 0),
    ("93610", "Intra-atrial pacing", 2.56, "electrophysiology", 0),
    ("93612", "Intraventricular pacing", 2.67, "electrophysiology", 0),
    ("93613", "Intracardiac electrophysiologic 3D mapping", 8.89, "electrophysiology", 0),
    ("93615", "Esophageal recording of atrial electrogram with or without pacing", 2.12, "electrophysiology", 0),
    ("93616", "Esophageal recording of atrial electrogram with pacing", 2.34, "electrophysiology", 0),
    ("93618", "Induction of arrhythmia by electrical pacing", 3.89, "electrophysiology", 0),
    ("93619", "Comprehensive electrophysiologic evaluation with right atrial pacing and recording", 7.56, "electrophysiology", 0),
    ("93620", "Comprehensive electrophysiologic evaluation including insertion and repositioning of multiple electrode catheters", 10.23, "electrophysiology", 0),
]
for code, desc, rvu, fam, glob in cardio_codes:
    new_codes[code] = make_cpt(code, desc, cat="Medicine", spec="interventional_cardiology", rvu=rvu, glob=glob, family=fam)

# ============================================================
# LOAD, MERGE, AND SAVE
# ============================================================

try:
    with open(DB_PATH, 'r') as f:
        db = json.load(f)
    
    before = len(db)
    added = 0
    for code, entry in new_codes.items():
        if code not in db:
            db[code] = entry
            added += 1
    
    with open(DB_PATH, 'w') as f:
        json.dump(db, f, indent=2)
    
    # Verify
    with open(DB_PATH, 'r') as f:
        verify = json.load(f)
    
    print(f"CPT Part 1: Before={before}, Added={added}, After={len(verify)}")
    print(f"JSON valid: {len(verify) > 0}")
    
except Exception as e:
    print(f"ERROR: {e}")
    import traceback
    traceback.print_exc()