#!/usr/bin/env python3
"""Expand CPT database - Part 2: Cardiology, GI, Urology, Pulm, Radiology, PM&R/Pain."""
import json
import os

DB_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'cpt_database.json')

def make_cpt(code, desc, cat="Surgery", subcat=None, spec="general_surgery",
             rvu=5.0, glob=90, bilat=False, addon=False, cosurg=False,
             assist=True, tier=2, family="unclassified", inclusive=None,
             never_primary=None, modifiers=None, estimated=True):
    return {
        "code": str(code),
        "description": desc,
        "category": cat,
        "subcategory": subcat,
        "specialty": spec,
        "work_rvu": rvu,
        "global_period_days": glob,
        "bilateral_eligible": bilat,
        "addon_code": addon,
        "cosurgeon_eligible": cosurg,
        "assistant_allowed": assist,
        "hierarchy_tier": tier,
        "code_family": family,
        "inclusive_of": inclusive or [],
        "never_primary_with": never_primary or [],
        "typical_modifiers": modifiers or [],
        "estimated": estimated
    }

new_codes = {}

# ============================================================
# 4. INTERVENTIONAL CARDIOLOGY (continued)
# ============================================================

cardio_ep = [
    ("93621", "Comprehensive electrophysiologic evaluation with left atrial pacing and recording from coronary sinus", 3.45),
    ("93622", "Comprehensive electrophysiologic evaluation with left ventricular pacing and recording", 3.67),
    ("93623", "Programmed stimulation and pacing after intravenous drug infusion", 2.89),
    ("93624", "Electrophysiologic follow-up study with pacing and recording", 4.56),
    ("93631", "Intra-operative epicardial and endocardial pacing and mapping to localize zone of origin of arrhythmia", 8.34),
    ("93640", "Electrophysiologic evaluation of single or dual chamber pacing cardioverter-defibrillator leads", 3.23),
    ("93641", "Electrophysiologic evaluation of single or dual chamber transvenous pacing cardioverter-defibrillator", 4.12),
    ("93642", "Electrophysiologic evaluation of single or dual chamber transvenous pacing cardioverter-defibrillator with DFT testing", 4.89),
    ("93650", "Intracardiac catheter ablation of atrioventricular node function to create complete heart block", 12.34),
    ("93653", "Comprehensive electrophysiologic evaluation with insertion and repositioning of multiple electrode catheters with induction or attempted induction of arrhythmia with right atrial pacing and recording and catheter ablation of arrhythmogenic focus including SVT AF atrial flutter", 15.67),
    ("93654", "Comprehensive electrophysiologic evaluation with insertion and repositioning of multiple electrode catheters with induction or attempted induction of arrhythmia with catheter ablation of arrhythmogenic focus VT", 18.23),
    ("93655", "Intracardiac catheter ablation of a discrete mechanism of arrhythmia not related to initial ablation procedure", 6.78),
    ("93656", "Comprehensive electrophysiologic evaluation including transseptal catheterizations insertion and repositioning of multiple electrode catheters with induction or attempted induction of arrhythmia with atrial pacing and recording intracardiac catheter ablation of atrial fibrillation by pulmonary vein isolation", 20.45),
    ("93657", "Additional linear or focal intracardiac catheter ablation of the left or right atrium for treatment of atrial fibrillation remaining after pulmonary vein isolation", 7.89),
    ("93660", "Evaluation of cardiovascular function with tilt table evaluation with continuous ECG monitoring and target heart rate pharmacological intervention", 2.34),
    ("93662", "Intracardiac echocardiography during therapeutic/diagnostic intervention including imaging supervision and interpretation", 3.56),
]
for code, desc, rvu in cardio_ep:
    new_codes[code] = make_cpt(code, desc, cat="Medicine", spec="interventional_cardiology", rvu=rvu, glob=0, family="electrophysiology")

# Pacemaker/ICD (33206-33275)
pacer_icd = [
    ("33206", "Insertion of new or replacement of permanent pacemaker with transvenous electrodes atrial", 9.67),
    ("33207", "Insertion of new or replacement of permanent pacemaker with transvenous electrodes ventricular", 9.23),
    ("33208", "Insertion of new or replacement of permanent pacemaker with transvenous electrodes atrial and ventricular", 10.89),
    ("33210", "Insertion or replacement of temporary transvenous single chamber cardiac electrode or pacemaker catheter", 4.56),
    ("33211", "Insertion or replacement of temporary transvenous dual chamber pacing electrodes", 5.34),
    ("33212", "Insertion of pacemaker pulse generator only single chamber existing single lead", 5.78),
    ("33213", "Insertion of pacemaker pulse generator only dual chamber existing leads", 6.12),
    ("33214", "Upgrade of implanted pacemaker system conversion of single chamber system to dual chamber system", 8.45),
    ("33215", "Repositioning of previously implanted transvenous pacemaker or defibrillator electrode", 5.89),
    ("33216", "Insertion of a single transvenous electrode permanent pacemaker or cardioverter-defibrillator", 6.34),
    ("33217", "Insertion of 2 transvenous electrodes permanent pacemaker or cardioverter-defibrillator", 7.56),
    ("33218", "Repair of single transvenous electrode for permanent pacemaker or cardioverter-defibrillator", 5.23),
    ("33220", "Repair of 2 transvenous electrodes for permanent pacemaker or cardioverter-defibrillator", 6.45),
    ("33221", "Insertion of pacemaker pulse generator only dual chamber existing multiple leads", 6.78),
    ("33222", "Relocation of skin pocket for pacemaker", 4.89),
    ("33223", "Relocation of skin pocket for implantable defibrillator", 5.23),
    ("33224", "Insertion of pacing electrode cardiac venous system for left ventricular pacing at time of insertion of ICD or pacemaker", 6.89),
    ("33225", "Insertion of pacing electrode cardiac venous system for left ventricular pacing at time of upgrade to implantable defibrillator", 7.23),
    ("33226", "Repositioning of previously implanted cardiac venous system lead (left ventricular pacing)", 5.56),
    ("33227", "Removal of permanent pacemaker pulse generator with replacement single lead system", 4.56),
    ("33228", "Removal of permanent pacemaker pulse generator with replacement dual lead system", 4.89),
    ("33229", "Removal of permanent pacemaker pulse generator with replacement multiple lead system", 5.23),
    ("33230", "Insertion of implantable defibrillator pulse generator only with existing dual leads", 7.89),
    ("33231", "Insertion of implantable defibrillator pulse generator only with existing multiple leads", 8.23),
    ("33233", "Removal of permanent pacemaker pulse generator only", 4.12),
    ("33234", "Removal of transvenous pacemaker electrode single lead system atrial or ventricular", 6.78),
    ("33235", "Removal of transvenous pacemaker electrode dual lead system", 7.89),
    ("33236", "Removal of permanent epicardial pacemaker and electrodes by thoracotomy single lead system", 12.34),
    ("33237", "Removal of permanent epicardial pacemaker and electrodes by thoracotomy dual lead system", 13.56),
    ("33238", "Removal of permanent transvenous electrode by thoracotomy", 14.78),
    ("33240", "Insertion of implantable defibrillator pulse generator only with existing single lead", 7.56),
    ("33241", "Removal of implantable defibrillator pulse generator only", 4.89),
    ("33243", "Removal of single or dual chamber implantable defibrillator electrode by thoracotomy", 15.23),
    ("33244", "Removal of single or dual chamber implantable defibrillator electrode by transvenous extraction", 12.67),
    ("33249", "Insertion or replacement of permanent implantable defibrillator system with transvenous lead sensing and treating one or more chambers", 14.56),
    ("33250", "Operative ablation of supraventricular arrhythmogenic focus or pathway", 18.34),
    ("33251", "Operative ablation of supraventricular arrhythmogenic focus or pathway with cardiopulmonary bypass", 22.67),
    ("33254", "Operative tissue ablation and reconstruction of atria limited", 20.45),
    ("33255", "Operative tissue ablation and reconstruction of atria extensive", 24.78),
    ("33256", "Operative tissue ablation and reconstruction of atria extensive with bypass", 28.34),
    ("33257", "Operative tissue ablation and reconstruction of atria performed at time of other cardiac procedure limited", 8.56),
    ("33258", "Operative tissue ablation and reconstruction of atria performed at time of other cardiac procedure extensive", 10.89),
    ("33259", "Operative tissue ablation and reconstruction of atria performed at time of other cardiac procedure extensive with bypass", 12.34),
    ("33261", "Operative ablation of ventricular arrhythmogenic focus with cardiopulmonary bypass", 24.56),
    ("33262", "Removal of implantable defibrillator pulse generator with replacement single lead system", 5.67),
    ("33263", "Removal of implantable defibrillator pulse generator with replacement dual lead system", 6.12),
    ("33264", "Removal of implantable defibrillator pulse generator with replacement multiple lead system", 6.56),
    ("33270", "Insertion or replacement of permanent subcutaneous implantable defibrillator system", 10.23),
    ("33271", "Insertion of subcutaneous implantable defibrillator electrode", 6.78),
    ("33272", "Removal of subcutaneous implantable defibrillator electrode", 5.34),
    ("33273", "Repositioning of previously implanted subcutaneous implantable defibrillator electrode", 5.89),
    ("33274", "Transcatheter insertion or replacement of permanent leadless pacemaker ventricular", 12.34),
    ("33275", "Transcatheter removal of permanent leadless pacemaker ventricular", 14.56),
]
for code, desc, rvu in pacer_icd:
    new_codes[code] = make_cpt(code, desc, spec="interventional_cardiology", rvu=rvu, glob=90, family="pacemaker_icd")

# Additional cardiology
cardio_misc = [
    ("93000", "Electrocardiogram routine ECG with at least 12 leads with interpretation and report", 0.52, "Medicine", "diagnostic_cardiology", 0),
    ("93005", "Electrocardiogram routine ECG tracing only without interpretation", 0.17, "Medicine", "diagnostic_cardiology", 0),
    ("93010", "Electrocardiogram routine ECG interpretation and report only", 0.35, "Medicine", "diagnostic_cardiology", 0),
    ("93015", "Cardiovascular stress test using maximal or submaximal treadmill or bicycle exercise with supervision interpretation and report", 1.56, "Medicine", "diagnostic_cardiology", 0),
    ("93016", "Cardiovascular stress test supervision only", 0.45, "Medicine", "diagnostic_cardiology", 0),
    ("93017", "Cardiovascular stress test tracing only", 0.34, "Medicine", "diagnostic_cardiology", 0),
    ("93018", "Cardiovascular stress test interpretation and report only", 0.67, "Medicine", "diagnostic_cardiology", 0),
    ("93024", "Ergonovine provocation test", 2.34, "Medicine", "diagnostic_cardiology", 0),
    ("93040", "Rhythm ECG 1-3 leads with interpretation and report", 0.23, "Medicine", "diagnostic_cardiology", 0),
    ("93041", "Rhythm ECG 1-3 leads tracing only", 0.12, "Medicine", "diagnostic_cardiology", 0),
    ("93042", "Rhythm ECG 1-3 leads interpretation and report only", 0.15, "Medicine", "diagnostic_cardiology", 0),
    ("93224", "External electrocardiographic recording up to 48 hours by continuous recording including recording scanning analysis with report review and interpretation", 1.45, "Medicine", "diagnostic_cardiology", 0),
    ("93225", "External electrocardiographic recording up to 48 hours continuous recording", 0.00, "Medicine", "diagnostic_cardiology", 0),
    ("93226", "External electrocardiographic recording up to 48 hours scanning analysis with report", 0.52, "Medicine", "diagnostic_cardiology", 0),
    ("93227", "External electrocardiographic recording up to 48 hours review and interpretation", 0.52, "Medicine", "diagnostic_cardiology", 0),
    ("93228", "External mobile cardiovascular telemetry with ECG recording review and interpretation per 30 days", 1.23, "Medicine", "diagnostic_cardiology", 0),
    ("93229", "External mobile cardiovascular telemetry with ECG technical support per 30 days", 0.00, "Medicine", "diagnostic_cardiology", 0),
    ("93268", "External patient and/or auto activated electrocardiographic rhythm derived event recording up to 30 days with interpretation and report", 1.34, "Medicine", "diagnostic_cardiology", 0),
    ("93270", "External patient and/or auto activated electrocardiographic rhythm derived event recording and transmission", 0.00, "Medicine", "diagnostic_cardiology", 0),
    ("93271", "External patient and/or auto activated electrocardiographic rhythm derived event recording scanning analysis", 0.34, "Medicine", "diagnostic_cardiology", 0),
    ("93272", "External patient and/or auto activated electrocardiographic rhythm derived event recording review and interpretation", 0.52, "Medicine", "diagnostic_cardiology", 0),
    ("93278", "Signal-averaged electrocardiography with or without ECG", 0.56, "Medicine", "diagnostic_cardiology", 0),
    ("93279", "Programming device evaluation single dual or multiple lead pacemaker system with iterative adjustment", 0.67, "Medicine", "diagnostic_cardiology", 0),
    ("93280", "Programming device evaluation single dual or multiple lead pacemaker system in person", 0.78, "Medicine", "diagnostic_cardiology", 0),
    ("93281", "Programming device evaluation single dual or multiple lead implantable defibrillator system with iterative adjustment", 1.23, "Medicine", "diagnostic_cardiology", 0),
    ("93282", "Programming device evaluation in person with iterative adjustment single lead pacemaker system", 0.89, "Medicine", "diagnostic_cardiology", 0),
    ("93283", "Programming device evaluation in person with iterative adjustment dual lead pacemaker system", 1.12, "Medicine", "diagnostic_cardiology", 0),
    ("93284", "Programming device evaluation in person with iterative adjustment multiple lead pacemaker system", 1.34, "Medicine", "diagnostic_cardiology", 0),
    ("93285", "Programming device evaluation in person with iterative adjustment single dual or multiple lead ICD system", 1.56, "Medicine", "diagnostic_cardiology", 0),
    ("93286", "Peri-procedural device evaluation and programming of device system single dual or multiple lead pacemaker", 0.56, "Medicine", "diagnostic_cardiology", 0),
    ("93287", "Peri-procedural device evaluation and programming of device system single dual or multiple lead ICD", 0.67, "Medicine", "diagnostic_cardiology", 0),
    ("93288", "Interrogation device evaluation in person with analysis review and report single dual or multiple lead pacemaker", 0.45, "Medicine", "diagnostic_cardiology", 0),
    ("93289", "Interrogation device evaluation in person with analysis review and report single dual or multiple lead ICD", 0.67, "Medicine", "diagnostic_cardiology", 0),
    ("93290", "Interrogation device evaluation in person with analysis review and report cardiac contractility modulation system", 0.56, "Medicine", "diagnostic_cardiology", 0),
    ("93291", "Interrogation device evaluation in person with analysis review and report subcutaneous cardiac rhythm monitor", 0.45, "Medicine", "diagnostic_cardiology", 0),
    ("93292", "Interrogation device evaluation in person with analysis review and report wearable defibrillator system", 0.56, "Medicine", "diagnostic_cardiology", 0),
    ("93293", "Transtelephonic rhythm strip pacemaker evaluation single dual or multiple lead pacemaker 90 days", 0.34, "Medicine", "diagnostic_cardiology", 0),
    ("93294", "Interrogation device evaluation remote up to 90 days single dual or multiple lead pacemaker", 0.45, "Medicine", "diagnostic_cardiology", 0),
    ("93295", "Interrogation device evaluation remote up to 90 days single dual or multiple lead ICD", 0.56, "Medicine", "diagnostic_cardiology", 0),
    ("93296", "Interrogation device evaluation remote up to 90 days single dual or multiple lead pacemaker ICD or subcutaneous cardiac rhythm monitor system technical support", 0.00, "Medicine", "diagnostic_cardiology", 0),
    ("93297", "Interrogation device evaluation remote up to 30 days cardiac contractility modulation system", 0.45, "Medicine", "diagnostic_cardiology", 0),
    ("93298", "Interrogation device evaluation remote up to 30 days subcutaneous cardiac rhythm monitor", 0.34, "Medicine", "diagnostic_cardiology", 0),
    ("93303", "Transthoracic echocardiography for congenital cardiac anomalies complete", 3.45, "Medicine", "diagnostic_cardiology", 0),
    ("93304", "Transthoracic echocardiography for congenital cardiac anomalies follow-up or limited study", 2.12, "Medicine", "diagnostic_cardiology", 0),
    ("93306", "Transthoracic echocardiography complete with Doppler and color flow Doppler", 2.67, "Medicine", "diagnostic_cardiology", 0),
    ("93307", "Transthoracic echocardiography complete without Doppler", 1.89, "Medicine", "diagnostic_cardiology", 0),
    ("93308", "Transthoracic echocardiography follow-up or limited study", 0.89, "Medicine", "diagnostic_cardiology", 0),
    ("93312", "Transesophageal echocardiography real time with image documentation including probe placement", 4.56, "Medicine", "diagnostic_cardiology", 0),
    ("93313", "Transesophageal echocardiography placement of probe only", 2.34, "Medicine", "diagnostic_cardiology", 0),
    ("93314", "Transesophageal echocardiography image acquisition interpretation and report only", 2.89, "Medicine", "diagnostic_cardiology", 0),
    ("93315", "Transesophageal echocardiography for congenital cardiac anomalies including probe placement", 5.23, "Medicine", "diagnostic_cardiology", 0),
    ("93316", "Transesophageal echocardiography for congenital cardiac anomalies probe placement only", 2.56, "Medicine", "diagnostic_cardiology", 0),
    ("93317", "Transesophageal echocardiography for congenital cardiac anomalies image acquisition interpretation and report only", 3.12, "Medicine", "diagnostic_cardiology", 0),
    ("93318", "Transesophageal echocardiography for monitoring purposes during cardiac surgery", 3.45, "Medicine", "diagnostic_cardiology", 0),
    ("93320", "Doppler echocardiography pulsed wave and/or continuous wave with spectral display", 0.56, "Medicine", "diagnostic_cardiology", 0),
    ("93321", "Doppler echocardiography pulsed wave and/or continuous wave with spectral display follow-up or limited study", 0.34, "Medicine", "diagnostic_cardiology", 0),
    ("93325", "Doppler echocardiography color flow velocity mapping", 0.23, "Medicine", "diagnostic_cardiology", 0),
    ("93350", "Echocardiography transthoracic real-time with image documentation during rest and cardiovascular stress test", 2.34, "Medicine", "diagnostic_cardiology", 0),
    ("93351", "Echocardiography transthoracic real-time with image documentation during rest and cardiovascular stress test with interpretation and report", 3.12, "Medicine", "diagnostic_cardiology", 0),
    ("93352", "Use of echocardiographic contrast agent during stress echocardiography", 0.23, "Medicine", "diagnostic_cardiology", 0),
    ("93451", "Right heart catheterization", 4.56, "Medicine", "diagnostic_cardiology", 0),
    ("93452", "Left heart catheterization including intraprocedural injection for left ventriculography", 5.89, "Medicine", "diagnostic_cardiology", 0),
    ("93453", "Combined right and left heart catheterization including intraprocedural injection for left ventriculography", 7.12, "Medicine", "diagnostic_cardiology", 0),
    ("93454", "Catheter placement in coronary artery for coronary angiography imaging supervision and interpretation", 4.89, "Medicine", "diagnostic_cardiology", 0),
    ("93455", "Catheter placement in coronary artery for coronary angiography with catheter placement in bypass grafts", 5.23, "Medicine", "diagnostic_cardiology", 0),
    ("93456", "Catheter placement in coronary artery for coronary angiography with right heart catheterization", 6.34, "Medicine", "diagnostic_cardiology", 0),
    ("93457", "Catheter placement in coronary artery for coronary angiography with bypass graft angiography and right heart catheterization", 6.89, "Medicine", "diagnostic_cardiology", 0),
    ("93458", "Catheter placement in coronary artery for coronary angiography with left heart catheterization including intraprocedural injection for left ventriculography", 7.23, "Medicine", "diagnostic_cardiology", 0),
    ("93459", "Catheter placement in coronary artery for coronary angiography with bypass graft angiography and left heart catheterization", 7.56, "Medicine", "diagnostic_cardiology", 0),
    ("93460", "Catheter placement in coronary artery for coronary angiography with right and left heart catheterization", 8.12, "Medicine", "diagnostic_cardiology", 0),
    ("93461", "Catheter placement in coronary artery for coronary angiography with bypass graft angiography and right and left heart catheterization", 8.67, "Medicine", "diagnostic_cardiology", 0),
    ("93462", "Left heart catheterization by transseptal puncture through intact septum", 3.45, "Medicine", "diagnostic_cardiology", 0),
    ("93463", "Pharmacologic agent administration during cardiac catheterization", 0.89, "Medicine", "diagnostic_cardiology", 0),
    ("93464", "Physiologic exercise study during cardiac catheterization", 1.23, "Medicine", "diagnostic_cardiology", 0),
    ("93530", "Right heart catheterization for congenital cardiac anomalies", 5.67, "Medicine", "diagnostic_cardiology", 0),
    ("93531", "Combined right heart catheterization and retrograde left heart catheterization for congenital cardiac anomalies", 7.89, "Medicine", "diagnostic_cardiology", 0),
    ("93532", "Combined right heart catheterization and transseptal left heart catheterization through intact septum for congenital cardiac anomalies", 8.34, "Medicine", "diagnostic_cardiology", 0),
    ("93533", "Combined right heart catheterization and transseptal left heart catheterization through existing septal opening for congenital cardiac anomalies", 7.56, "Medicine", "diagnostic_cardiology", 0),
    ("93561", "Indicator dilution studies injection procedure for cardiac output measurement", 0.89, "Medicine", "diagnostic_cardiology", 0),
    ("93562", "Indicator dilution studies subsequent measurement of cardiac output", 0.45, "Medicine", "diagnostic_cardiology", 0),
    ("93563", "Injection procedure during cardiac catheterization including imaging supervision for selective opacification of aortic root", 1.23, "Medicine", "diagnostic_cardiology", 0),
    ("93564", "Injection procedure during cardiac catheterization including imaging supervision for selective opacification of pulmonary vasculature", 1.34, "Medicine", "diagnostic_cardiology", 0),
    ("93565", "Injection procedure during cardiac catheterization for supravalvular aortography", 1.12, "Medicine", "diagnostic_cardiology", 0),
    ("93566", "Injection procedure during cardiac catheterization for selective right ventricular angiography", 1.23, "Medicine", "diagnostic_cardiology", 0),
    ("93567", "Injection procedure during cardiac catheterization for supravalvular aortography", 1.34, "Medicine", "diagnostic_cardiology", 0),
    ("93568", "Injection procedure during cardiac catheterization for pulmonary angiography", 1.45, "Medicine", "diagnostic_cardiology", 0),
    ("93571", "Intravascular Doppler velocity and/or pressure derived coronary flow reserve measurement during coronary angiography", 2.34, "Medicine", "diagnostic_cardiology", 0),
    ("93572", "Intravascular Doppler velocity and/or pressure each additional vessel", 1.12, "Medicine", "diagnostic_cardiology", 0),
    ("93580", "Percutaneous transcatheter closure of congenital interatrial communication", 16.78, "Medicine", "interventional_cardiology", 90),
    ("93581", "Percutaneous transcatheter closure of a congenital ventricular septal defect", 18.34, "Medicine", "interventional_cardiology", 90),
    ("93582", "Percutaneous transcatheter closure of patent ductus arteriosus", 14.56, "Medicine", "interventional_cardiology", 90),
    ("93583", "Percutaneous transcatheter septal reduction therapy", 16.89, "Medicine", "interventional_cardiology", 90),
    ("93590", "Percutaneous transcatheter closure of paravalvular leak; initial occlusion device", 18.56, "Medicine", "interventional_cardiology", 90),
    ("93591", "Percutaneous transcatheter closure of paravalvular leak; each additional occlusion device", 6.78, "Medicine", "interventional_cardiology", 90),
    ("93592", "Percutaneous transcatheter closure of paravalvular leak with imaging guidance", 4.56, "Medicine", "interventional_cardiology", 90),
]
for code, desc, rvu, cat, spec, glob in cardio_misc:
    new_codes[code] = make_cpt(code, desc, cat=cat, spec=spec, rvu=rvu, glob=glob, family="diagnostic_cardiology")

# ============================================================
# 5. ADDITIONAL GI (100+ codes)
# ============================================================

gi_codes = [
    ("91110", "Gastrointestinal tract imaging intraluminal (eg capsule endoscopy) esophagus through ileum with interpretation and report", 3.45, "Medicine", "gastroenterology", 0, "capsule_endoscopy"),
    ("91111", "Gastrointestinal tract imaging intraluminal colon with interpretation and report", 3.67, "Medicine", "gastroenterology", 0, "capsule_endoscopy"),
    ("91112", "Gastrointestinal tract imaging intraluminal esophagus with interpretation and report", 2.89, "Medicine", "gastroenterology", 0, "capsule_endoscopy"),
    ("91117", "Colon motility study minimum 6 hours continuous recording including provocative testing", 2.34, "Medicine", "gastroenterology", 0, "motility"),
    ("91120", "Rectal sensation tone and compliance test", 1.23, "Medicine", "gastroenterology", 0, "motility"),
    ("91122", "Anorectal manometry", 1.56, "Medicine", "gastroenterology", 0, "motility"),
    ("91132", "Electrogastrography diagnostic transcutaneous", 1.12, "Medicine", "gastroenterology", 0, "motility"),
    ("91133", "Electrogastrography diagnostic transcutaneous with provocative testing", 1.45, "Medicine", "gastroenterology", 0, "motility"),
    ("91200", "Liver elastography without imaging via vibration-controlled transient elastography", 0.89, "Medicine", "gastroenterology", 0, "hepatobiliary"),
    # Hepatobiliary procedures (47000-47999)
    ("47000", "Biopsy of liver needle percutaneous", 2.56, "Surgery", "gastroenterology", 0, "hepatobiliary"),
    ("47001", "Biopsy of liver needle when done for indicated purpose at time of other major procedure", 1.23, "Surgery", "gastroenterology", 0, "hepatobiliary"),
    ("47010", "Hepatotomy for open drainage of abscess or cyst 1 or 2 stages", 16.78, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47015", "Laparotomy with aspiration and/or injection of hepatic parasitic cyst or abscess", 14.56, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47100", "Biopsy of liver wedge", 8.34, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47120", "Hepatectomy resection of liver partial lobectomy", 28.67, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47122", "Hepatectomy resection of liver trisegmentectomy", 38.45, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47125", "Hepatectomy resection of liver total left lobectomy", 32.12, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47130", "Hepatectomy resection of liver total right lobectomy", 36.78, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47133", "Donor hepatectomy from living donor including cold preservation", 40.23, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47135", "Liver allotransplantation orthotopic partial or whole from cadaver or living donor any age any method", 55.67, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47136", "Liver allotransplantation heterotopic partial or whole from cadaver or living donor any age any method", 52.34, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47140", "Donor hepatectomy from living donor left lateral segment only without recipient hepatectomy", 35.67, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47141", "Donor hepatectomy from living donor total right lobe without recipient hepatectomy", 38.45, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47142", "Donor hepatectomy from living donor total right lobe with recipient hepatectomy", 45.23, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47300", "Marsupialization of cyst or abscess of liver", 12.34, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47350", "Management of liver hemorrhage simple suture of liver wound or injury", 14.56, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47360", "Management of liver hemorrhage complex suture of liver wound or injury with or without hepatic artery ligation", 22.34, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47361", "Management of liver hemorrhage exploration of hepatic wound extensive debridement coagulation and/or suture with or without packing of liver", 26.78, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47362", "Management of liver hemorrhage re-exploration of hepatic wound for removal of packing", 12.56, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47370", "Laparoscopy surgical ablation of 1 or more liver tumors radiofrequency", 15.67, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47371", "Laparoscopy surgical ablation of 1 or more liver tumors cryosurgery", 16.23, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47379", "Unlisted laparoscopic procedure liver", 0.00, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47380", "Ablation open of 1 or more liver tumors radiofrequency", 14.56, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47381", "Ablation open of 1 or more liver tumors cryosurgery", 15.23, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47382", "Ablation 1 or more liver tumors percutaneous radiofrequency", 8.34, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47383", "Ablation 1 or more liver tumors percutaneous cryoablation", 8.89, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47399", "Unlisted procedure liver", 0.00, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47400", "Hepaticotomy or hepaticostomy with exploration drainage or removal of calculus", 18.34, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47420", "Choledochotomy or choledochostomy with exploration drainage or removal of calculus with or without cholecystotomy", 18.67, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47425", "Choledochotomy or choledochostomy with exploration drainage or removal of calculus with transduodenal sphincterotomy or sphincteroplasty", 22.34, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47460", "Transduodenal sphincterotomy or sphincteroplasty with or without transduodenal extraction of calculus", 16.78, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47480", "Cholecystotomy or cholecystostomy open with exploration drainage or removal of calculus", 14.56, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47490", "Cholecystostomy percutaneous", 6.78, "Surgery", "gastroenterology", 10, "hepatobiliary"),
    ("47500", "Injection procedure for percutaneous transhepatic cholangiography", 3.45, "Surgery", "gastroenterology", 0, "hepatobiliary"),
    ("47505", "Injection procedure for cholangiography through an existing catheter", 1.23, "Surgery", "gastroenterology", 0, "hepatobiliary"),
    ("47510", "Introduction of percutaneous transhepatic catheter for biliary drainage", 5.67, "Surgery", "gastroenterology", 10, "hepatobiliary"),
    ("47511", "Introduction of percutaneous transhepatic stent for internal/external biliary drainage", 7.89, "Surgery", "gastroenterology", 10, "hepatobiliary"),
    ("47525", "Change of percutaneous biliary drainage catheter", 2.34, "Surgery", "gastroenterology", 0, "hepatobiliary"),
    ("47530", "Revision and/or reinsertion of transhepatic tube", 3.56, "Surgery", "gastroenterology", 0, "hepatobiliary"),
    ("47550", "Biliary endoscopy intraoperative with or without biopsy and/or specimen collection", 3.12, "Surgery", "gastroenterology", 0, "hepatobiliary"),
    ("47552", "Biliary endoscopy percutaneous via T-tube or other tract diagnostic with or without collection of specimens", 4.56, "Surgery", "gastroenterology", 0, "hepatobiliary"),
    ("47553", "Biliary endoscopy percutaneous via T-tube or other tract with biopsy", 5.23, "Surgery", "gastroenterology", 0, "hepatobiliary"),
    ("47554", "Biliary endoscopy percutaneous via T-tube or other tract with removal of calculus", 6.78, "Surgery", "gastroenterology", 0, "hepatobiliary"),
    ("47555", "Biliary endoscopy percutaneous via T-tube or other tract with dilation of biliary duct stricture", 6.34, "Surgery", "gastroenterology", 0, "hepatobiliary"),
    ("47556", "Biliary endoscopy percutaneous via T-tube or other tract with stent placement", 7.23, "Surgery", "gastroenterology", 0, "hepatobiliary"),
    ("47560", "Laparoscopy surgical with guided transhepatic cholangiography without biopsy", 5.89, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47561", "Laparoscopy surgical with guided transhepatic cholangiography with biopsy", 6.78, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47562", "Laparoscopy surgical cholecystectomy", 10.56, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47563", "Laparoscopy surgical cholecystectomy with cholangiography", 11.23, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47564", "Laparoscopy surgical cholecystectomy with exploration of common duct", 14.56, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47570", "Laparoscopy surgical cholecystoenterostomy", 12.34, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47579", "Unlisted laparoscopic procedure biliary tract", 0.00, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47600", "Cholecystectomy", 12.89, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47605", "Cholecystectomy with cholangiography", 13.45, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47610", "Cholecystectomy with exploration of common duct", 16.78, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47612", "Cholecystectomy with exploration of common duct with choledochoenterostomy", 20.34, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47620", "Cholecystectomy with exploration of common duct with transduodenal sphincterotomy or sphincteroplasty with or without cholangiography", 22.56, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47700", "Exploration for congenital atresia of bile ducts without repair with or without liver biopsy with or without cholangiography", 14.23, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47701", "Portoenterostomy (eg Kasai procedure)", 28.34, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47711", "Excision of bile duct tumor with repair of bile duct with or without liver biopsy or cholangiography", 26.78, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47712", "Excision of bile duct tumor with repair by reanastomosis and/or transduodenal sphincteroplasty", 28.56, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47715", "Excision of choledochal cyst", 26.34, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47720", "Cholecystoenterostomy direct", 14.56, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47721", "Cholecystoenterostomy with gastroenterostomy", 18.34, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47740", "Cholecystenterostomy Roux-en-Y", 16.78, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47741", "Cholecystenterostomy Roux-en-Y with gastroenterostomy", 20.34, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47760", "Anastomosis of extrahepatic biliary ducts and gastrointestinal tract", 22.56, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47765", "Anastomosis of intrahepatic ducts and gastrointestinal tract", 28.34, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47780", "Anastomosis Roux-en-Y of extrahepatic biliary ducts and gastrointestinal tract", 24.67, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47785", "Anastomosis Roux-en-Y of intrahepatic biliary ducts and gastrointestinal tract", 30.12, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47800", "Reconstruction repair of extrahepatic biliary duct without stent or T-tube", 22.34, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47801", "Placement of choledochal stent", 8.67, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47802", "U-tube hepaticoenterostomy", 24.56, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47900", "Suture of extrahepatic biliary duct for pre-existing injury", 16.78, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    ("47999", "Unlisted procedure biliary tract", 0.00, "Surgery", "gastroenterology", 90, "hepatobiliary"),
    # Pancreas procedures
    ("48000", "Placement of drains peripancreatic for acute pancreatitis", 16.34, "Surgery", "gastroenterology", 90, "pancreas"),
    ("48001", "Placement of drains peripancreatic for acute pancreatitis with cholecystostomy gastrostomy and jejunostomy", 22.56, "Surgery", "gastroenterology", 90, "pancreas"),
    ("48020", "Removal of pancreatic calculus", 18.34, "Surgery", "gastroenterology", 90, "pancreas"),
    ("48100", "Biopsy of pancreas open", 12.56, "Surgery", "gastroenterology", 90, "pancreas"),
    ("48102", "Biopsy of pancreas percutaneous needle", 3.45, "Surgery", "gastroenterology", 0, "pancreas"),
    ("48105", "Resection or debridement of pancreas for necrotizing pancreatitis", 28.67, "Surgery", "gastroenterology", 90, "pancreas"),
    ("48120", "Excision of lesion of pancreas", 22.34, "Surgery", "gastroenterology", 90, "pancreas"),
    ("48140", "Pancreatectomy distal subtotal with or without splenectomy", 24.56, "Surgery", "gastroenterology", 90, "pancreas"),
    ("48145", "Pancreatectomy distal near-total with preservation of duodenum (Child-type procedure)", 28.34, "Surgery", "gastroenterology", 90, "pancreas"),
    ("48146", "Pancreatectomy distal subtotal with autotransplantation of preserved islet cells and target organ", 32.56, "Surgery", "gastroenterology", 90, "pancreas"),
    ("48148", "Excision of ampulla of Vater", 18.67, "Surgery", "gastroenterology", 90, "pancreas"),
    ("48150", "Pancreatectomy proximal subtotal with total duodenectomy partial gastrectomy choledochoenterostomy and gastrojejunostomy (Whipple-type) with pancreatojejunostomy", 42.34, "Surgery", "gastroenterology", 90, "pancreas"),
    ("48152", "Pancreatectomy proximal subtotal with total duodenectomy partial gastrectomy choledochoenterostomy and gastrojejunostomy (Whipple-type) without pancreatojejunostomy", 40.56, "Surgery", "gastroenterology", 90, "pancreas"),
    ("48153", "Pancreatectomy proximal subtotal with near-total duodenectomy choledochoenterostomy and duodenojejunostomy (pylorus-preserving Whipple-type)", 44.78, "Surgery", "gastroenterology", 90, "pancreas"),
    ("48154", "Pancreatectomy total", 45.67, "Surgery", "gastroenterology", 90, "pancreas"),
    ("48155", "Pancreatectomy total with autotransplantation of preserved islet cells", 48.34, "Surgery", "gastroenterology", 90, "pancreas"),
    ("48160", "Pancreatectomy total or subtotal with autotransplantation of pancreas or pancreatic islet cells", 50.23, "Surgery", "gastroenterology", 90, "pancreas"),
    ("48400", "Injection procedure for intraoperative pancreatography", 2.34, "Surgery", "gastroenterology", 0, "pancreas"),
    ("48500", "Marsupialization of pancreatic cyst", 14.56, "Surgery", "gastroenterology", 90, "pancreas"),
    ("48510", "External drainage pseudocyst of pancreas open", 14.89, "Surgery", "gastroenterology", 90, "pancreas"),
    ("48520", "Internal anastomosis of pancreatic cyst to gastrointestinal tract direct", 18.34, "Surgery", "gastroenterology", 90, "pancreas"),
    ("48540", "Internal anastomosis of pancreatic cyst to gastrointestinal tract Roux-en-Y", 22.56, "Surgery", "gastroenterology", 90, "pancreas"),
    ("48545", "Pancreatorrhaphy for injury", 18.67, "Surgery", "gastroenterology", 90, "pancreas"),
    ("48547", "Duodenal exclusion with gastrojejunostomy for pancreatic injury", 22.34, "Surgery", "gastroenterology", 90, "pancreas"),
    ("48548", "Pancreaticojejunostomy side to side anastomosis", 24.56, "Surgery", "gastroenterology", 90, "pancreas"),
    ("48556", "Removal of pancreatic transplant", 18.34, "Surgery", "gastroenterology", 90, "pancreas"),
    ("48999", "Unlisted procedure pancreas", 0.00, "Surgery", "gastroenterology", 90, "pancreas"),
]
for code, desc, rvu, cat, spec, glob, fam in gi_codes:
    new_codes[code] = make_cpt(code, desc, cat=cat, spec=spec, rvu=rvu, glob=glob, family=fam)

# ============================================================
# 6. ADDITIONAL UROLOGY (100+ codes)
# ============================================================

urology_codes = [
    # Cystoscopy (52000-52356)
    ("52000", "Cystourethroscopy", 2.23, 0),
    ("52001", "Cystourethroscopy with irrigation and evacuation of multiple obstructing clots", 3.45, 0),
    ("52005", "Cystourethroscopy with ureteral catheterization with or without irrigation instillation or ureteropyelography", 3.12, 0),
    ("52007", "Cystourethroscopy with ureteral catheterization with brush biopsy of ureter and/or renal pelvis", 3.89, 0),
    ("52010", "Cystourethroscopy with ejaculatory duct catheterization with or without vasotomy or vasography", 4.23, 0),
    ("52204", "Cystourethroscopy with biopsy", 2.89, 0),
    ("52214", "Cystourethroscopy with fulguration of trigone bladder neck prostatic fossa urethra or periurethral glands", 3.56, 0),
    ("52224", "Cystourethroscopy with fulguration or treatment of minor lesion", 3.23, 0),
    ("52234", "Cystourethroscopy with fulguration and/or resection of small bladder tumor 0.5-2.0 cm", 5.67, 0),
    ("52235", "Cystourethroscopy with fulguration and/or resection of medium bladder tumor 2.0-5.0 cm", 7.89, 0),
    ("52240", "Cystourethroscopy with fulguration and/or resection of large bladder tumor", 10.23, 0),
    ("52250", "Cystourethroscopy with insertion of radioactive substance with or without fulguration", 4.56, 0),
    ("52260", "Cystourethroscopy with dilation of bladder for interstitial cystitis", 3.89, 0),
    ("52265", "Cystourethroscopy with dilation of bladder for interstitial cystitis general or conduction anesthesia", 4.34, 0),
    ("52270", "Cystourethroscopy with internal urethrotomy female", 3.12, 0),
    ("52275", "Cystourethroscopy with internal urethrotomy male", 4.56, 0),
    ("52276", "Cystourethroscopy with direct vision internal urethrotomy", 4.89, 0),
    ("52277", "Cystourethroscopy with resection of external sphincter", 5.23, 0),
    ("52281", "Cystourethroscopy with calibration and/or dilation of urethral stricture or stenosis with or without injection", 3.45, 0),
    ("52282", "Cystourethroscopy with insertion of permanent urethral stent", 5.67, 0),
    ("52283", "Cystourethroscopy with steroid injection into stricture", 2.89, 0),
    ("52285", "Cystourethroscopy for treatment of the female urethral syndrome with any or all of the following dilation of urethra internal urethrotomy and/or lysis of urethrovaginal septal fibrosis", 3.78, 0),
    ("52287", "Cystourethroscopy with injection(s) for chemodenervation of the bladder", 3.12, 0),
    ("52290", "Cystourethroscopy with ureteral meatotomy unilateral or bilateral", 4.23, 0),
    ("52300", "Cystourethroscopy with resection or fulguration of orthotopic ureterocele", 5.34, 0),
    ("52301", "Cystourethroscopy with resection or fulguration of ectopic ureterocele", 5.89, 0),
    ("52305", "Cystourethroscopy with incision or resection of orifice of bladder diverticulum", 4.67, 0),
    ("52310", "Cystourethroscopy with removal of foreign body calculus or ureteral stent from urethra or bladder simple", 3.45, 0),
    ("52315", "Cystourethroscopy with removal of foreign body calculus or ureteral stent from urethra or bladder complicated", 5.67, 0),
    ("52317", "Litholapaxy; crushing or fragmentation of calculus and removal of fragments simple", 5.89, 0),
    ("52318", "Litholapaxy; crushing or fragmentation of calculus and removal of fragments complicated", 7.34, 0),
    ("52320", "Cystourethroscopy with removal of ureteral calculus", 6.78, 0),
    ("52325", "Cystourethroscopy with fragmentation of ureteral calculus and removal", 8.23, 0),
    ("52327", "Cystourethroscopy with subureteric injection of implant material", 4.56, 0),
    ("52330", "Cystourethroscopy with manipulation without removal of ureteral calculus", 4.89, 0),
    ("52332", "Cystourethroscopy with insertion of indwelling ureteral stent", 4.23, 0),
    ("52334", "Cystourethroscopy with insertion of ureteral guide wire through kidney to establish a nephrostomy tract", 5.67, 0),
    ("52341", "Cystourethroscopy with treatment of ureteral stricture dilation", 5.23, 0),
    ("52342", "Cystourethroscopy with treatment of ureteropelvic junction stricture dilation", 5.67, 0),
    ("52343", "Cystourethroscopy with treatment of intra-renal stricture dilation", 6.12, 0),
    ("52344", "Cystourethroscopy with ureteroscopy and/or pyeloscopy diagnostic", 5.89, 0),
    ("52345", "Cystourethroscopy with ureteroscopy and/or pyeloscopy with treatment", 7.34, 0),
    ("52346", "Cystourethroscopy with ureteroscopy and treatment of ureteral stricture balloon dilation", 6.78, 0),
    ("52351", "Cystourethroscopy with ureteroscopy and/or pyeloscopy with biopsy and/or fulguration of ureteral or renal pelvic lesion", 7.89, 0),
    ("52352", "Cystourethroscopy with ureteroscopy and/or pyeloscopy with removal or manipulation of calculus", 8.56, 0),
    ("52353", "Cystourethroscopy with ureteroscopy and/or pyeloscopy with lithotripsy", 9.34, 0),
    ("52354", "Cystourethroscopy with ureteroscopy and/or pyeloscopy with biopsy and/or fulguration of renal pelvis lesion", 8.23, 0),
    ("52356", "Cystourethroscopy with ureteroscopy and/or pyeloscopy with lithotripsy including insertion of indwelling ureteral stent", 10.12, 0),
    # TURP and prostate (52601-52700 + 55700-55899)
    ("52601", "Transurethral electrosurgical resection of prostate including control of postoperative bleeding complete vasectomy included", 12.34, 90),
    ("52630", "Transurethral resection residual obstructive tissue after 90 days postoperative", 8.56, 90),
    ("52640", "Transurethral resection of postoperative bladder neck contracture", 5.67, 0),
    ("52647", "Laser vaporization of prostate including control of postoperative bleeding with coagulation", 10.89, 90),
    ("52648", "Laser vaporization of prostate including control of postoperative bleeding with enucleation", 14.23, 90),
    ("52649", "Laser enucleation of the prostate with morcellation including control of postoperative bleeding", 15.67, 90),
    ("52700", "Transurethral drainage of prostatic abscess", 5.23, 0),
    ("55700", "Biopsy prostate needle or punch single or multiple any approach", 2.56, 0),
    ("55705", "Biopsy prostate incisional any approach", 4.89, 0),
    ("55706", "Biopsies prostate needle transperineal stereotactic template guided saturation sampling", 5.34, 0),
    ("55720", "Prostatotomy external drainage of prostatic abscess any approach simple", 6.78, 90),
    ("55725", "Prostatotomy external drainage of prostatic abscess any approach complicated", 8.34, 90),
    ("55801", "Prostatectomy perineal subtotal", 14.56, 90),
    ("55810", "Prostatectomy perineal radical with or without nerve sparing", 20.34, 90),
    ("55812", "Prostatectomy perineal radical with lymph node biopsy limited pelvic lymphadenectomy", 22.56, 90),
    ("55815", "Prostatectomy perineal radical with bilateral pelvic lymphadenectomy including external iliac hypogastric and obturator nodes", 24.78, 90),
    ("55821", "Prostatectomy suprapubic subtotal 1 or 2 stages", 14.23, 90),
    ("55831", "Prostatectomy retropubic subtotal", 14.56, 90),
    ("55840", "Prostatectomy retropubic radical with or without nerve sparing", 21.34, 90),
    ("55842", "Prostatectomy retropubic radical with lymph node biopsy limited pelvic lymphadenectomy", 23.56, 90),
    ("55845", "Prostatectomy retropubic radical with bilateral pelvic lymphadenectomy including external iliac hypogastric and obturator nodes", 25.78, 90),
    ("55860", "Exposure of prostate any approach for insertion of radioactive substance", 6.89, 90),
    ("55862", "Exposure of prostate any approach for insertion of radioactive substance with lymph node biopsy", 8.23, 90),
    ("55865", "Exposure of prostate any approach for insertion of radioactive substance with bilateral pelvic lymphadenectomy", 10.56, 90),
    ("55866", "Laparoscopy surgical prostatectomy retropubic radical including nerve sparing includes robotic", 22.56, 90),
    ("55870", "Electroejaculation", 2.34, 0),
    ("55873", "Cryosurgical ablation of the prostate", 8.67, 90),
    ("55874", "Transperineal placement of biodegradable material peri-prostatic single or multiple injections including image guidance", 3.45, 0),
    ("55875", "Transperineal placement of needles or catheters into prostate for interstitial radioelement application", 6.78, 0),
    ("55876", "Placement of interstitial device for radiation therapy guidance prostate", 3.23, 0),
    ("55880", "Ablation of malignant prostate tissue transrectal by high intensity focused ultrasound", 12.34, 90),
    ("55899", "Unlisted procedure male genital system", 0.00, 0),
]
for item in urology_codes:
    code, desc, rvu, glob = item[0], item[1], item[2], item[3]
    new_codes[code] = make_cpt(code, desc, spec="urology", rvu=rvu, glob=glob, family="urology")

# ============================================================
# 7. PULMONOLOGY (100+ codes)
# ============================================================

pulm_codes = [
    # Bronchoscopy (31615-31654)
    ("31615", "Tracheobronchoscopy through existing tracheostomy incision", 2.34),
    ("31622", "Bronchoscopy rigid or flexible including fluoroscopic guidance diagnostic with cell washing", 3.56),
    ("31623", "Bronchoscopy with brushing or protected brushings", 3.89),
    ("31624", "Bronchoscopy with bronchial alveolar lavage", 3.67),
    ("31625", "Bronchoscopy with bronchial or endobronchial biopsy single or multiple sites", 4.23),
    ("31626", "Bronchoscopy with placement of fiducial markers single or multiple", 4.56),
    ("31627", "Bronchoscopy with computer-assisted image guided navigation", 2.34),
    ("31628", "Bronchoscopy with transbronchial lung biopsy single lobe", 5.12),
    ("31629", "Bronchoscopy with transbronchial lung biopsy each additional lobe", 2.34),
    ("31630", "Bronchoscopy with tracheal dilation or closed reduction of fracture", 4.89),
    ("31631", "Bronchoscopy with tracheal stent placement including dilation", 6.78),
    ("31632", "Bronchoscopy with transbronchial lung biopsy with fluoroscopic guidance single lobe", 5.67),
    ("31633", "Bronchoscopy with transbronchial lung biopsy with fluoroscopic guidance each additional lobe", 2.56),
    ("31634", "Bronchoscopy with balloon occlusion with assessment of air leak with administration of occlusive substance if performed", 5.23),
    ("31635", "Bronchoscopy with removal of foreign body", 5.89),
    ("31636", "Bronchoscopy with placement of bronchial stent including dilation initial bronchus", 7.34),
    ("31637", "Bronchoscopy with placement of bronchial stent each additional major bronchus stented", 3.45),
    ("31638", "Bronchoscopy with revision of tracheal or bronchial stent", 5.67),
    ("31640", "Bronchoscopy with excision of tumor", 6.89),
    ("31641", "Bronchoscopy with destruction of tumor or relief of stenosis by any method other than excision", 6.34),
    ("31643", "Bronchoscopy with placement of catheter for intracavitary radioelement application", 5.12),
    ("31645", "Bronchoscopy with therapeutic aspiration of tracheobronchial tree initial", 3.78),
    ("31646", "Bronchoscopy with therapeutic aspiration of tracheobronchial tree subsequent", 3.23),
    ("31647", "Bronchoscopy with balloon occlusion each additional lobe", 2.89),
    ("31648", "Bronchoscopy with removal of bronchial valve initial", 5.34),
    ("31649", "Bronchoscopy with removal of bronchial valve each additional", 2.67),
    ("31651", "Bronchoscopy with balloon occlusion with bronchial valve placement initial", 7.23),
    ("31652", "Bronchoscopy with endobronchial ultrasound guided transtracheal and/or transbronchial sampling", 6.45),
    ("31653", "Bronchoscopy with endobronchial ultrasound guided transtracheal and/or transbronchial sampling 3+ additional stations", 2.89),
    ("31654", "Bronchoscopy with transendoscopic endobronchial ultrasound during bronchoscopic diagnostic or therapeutic intervention", 2.34),
    # PFTs (94010-94799)
    ("94010", "Spirometry including graphic record total and timed vital capacity expiratory flow rate measurements with or without maximal voluntary ventilation", 0.56),
    ("94011", "Spirometry including graphic record total and timed vital capacity measurement of an infant through 2 years of age", 0.67),
    ("94012", "Measurement of spirometric forced expiratory flows in an infant or child through 2 years of age", 0.78),
    ("94013", "Measurement of lung volumes in an infant or child through 2 years of age", 0.89),
    ("94014", "Patient-initiated spirometric recording per 30-day period of time", 0.45),
    ("94015", "Patient-initiated spirometric recording per 30-day period of time recording", 0.34),
    ("94016", "Patient-initiated spirometric recording per 30-day period of time review and interpretation", 0.23),
    ("94060", "Bronchodilation responsiveness spirometry as in 94010 pre and post bronchodilator administration", 0.78),
    ("94070", "Bronchospasm provocation evaluation spirometric studies before and after with aerosolized agent", 1.23),
    ("94150", "Vital capacity total", 0.23),
    ("94200", "Maximum breathing capacity maximal voluntary ventilation", 0.23),
    ("94250", "Expired gas collection quantitative single procedure", 0.23),
    ("94375", "Respiratory flow volume loop", 0.23),
    ("94400", "Breathing response to CO2", 0.89),
    ("94450", "Breathing response to hypoxia", 0.89),
    ("94452", "High altitude simulation test", 0.78),
    ("94453", "High altitude simulation test interpretation and report", 0.56),
    ("94610", "Intrapulmonary surfactant administration through endotracheal tube", 2.34),
    ("94620", "Pulmonary stress testing simple", 1.12),
    ("94621", "Pulmonary stress testing complex including measurements of CO2 production O2 uptake and electrocardiographic recordings", 2.34),
    ("94640", "Pressurized or nonpressurized inhalation treatment for acute airway obstruction", 0.23),
    ("94642", "Aerosol inhalation of pentamidine for pneumocystis carinii pneumonia treatment or prophylaxis", 0.45),
    ("94644", "Continuous inhalation treatment with aerosol medication for acute airway obstruction first hour", 0.67),
    ("94645", "Continuous inhalation treatment with aerosol medication for acute airway obstruction each additional hour", 0.34),
    ("94660", "Continuous positive airway pressure ventilation CPAP initiation and management", 1.23),
    ("94662", "Continuous negative pressure ventilation CNP initiation and management", 1.34),
    ("94664", "Demonstration and/or evaluation of patient utilization of an aerosol generator compressor nebulizer", 0.12),
    ("94667", "Manipulation chest wall such as cupping pounding and vibrating to facilitate lung function initial demonstration and/or evaluation", 0.56),
    ("94668", "Manipulation chest wall such as cupping pounding and vibrating to facilitate lung function subsequent", 0.34),
    ("94669", "Mechanical chest wall oscillation to facilitate lung function", 0.23),
    ("94680", "Oxygen uptake expired gas analysis rest and exercise direct steady state or steady state predicted", 1.23),
    ("94681", "Oxygen uptake expired gas analysis including CO2 output rest and exercise direct steady state or predicted", 1.45),
    ("94690", "Oxygen uptake expired gas analysis rest and exercise indirect maximum actual or predicted or oxygen consumption", 1.12),
    ("94720", "Carbon monoxide diffusing capacity DLCO", 0.56),
    ("94726", "Plethysmography for determination of lung volumes and when performed airway resistance", 0.45),
    ("94727", "Gas dilution or washout for determination of lung volumes and when performed distribution of ventilation and closing volumes", 0.45),
    ("94728", "Airway resistance by impulse oscillometry", 0.34),
    ("94729", "Diffusing capacity DLCO with adjustment for hemoglobin and/or carboxyhemoglobin", 0.56),
    ("94750", "Pulmonary compliance study lung or thorax", 0.89),
    ("94760", "Noninvasive ear or pulse oximetry for oxygen saturation single determination", 0.12),
    ("94761", "Noninvasive ear or pulse oximetry for oxygen saturation multiple determinations", 0.23),
    ("94762", "Noninvasive ear or pulse oximetry for oxygen saturation continuous overnight monitoring", 0.34),
    ("94770", "Carbon dioxide expired gas determination by infrared analyzer", 0.23),
    ("94772", "Circadian respiratory pattern recording pediatric with interpretation and report", 0.89),
    ("94774", "Pediatric home apnea monitoring event recording including respiratory rate heart rate and oxygen saturation per 30 days", 1.23),
    ("94775", "Pediatric home apnea monitoring event recording including respiratory rate heart rate and oxygen saturation set up and interpretation", 0.78),
    ("94776", "Pediatric home apnea monitoring event recording per 30 days physician review", 0.56),
    ("94777", "Pediatric home apnea monitoring event recording per 30 days download and technical support", 0.23),
    ("94780", "Car seat/bed testing for airway integrity neonatal per T", 0.23),
    ("94781", "Car seat/bed testing for airway integrity neonatal each additional full 60 minutes", 0.12),
    ("94799", "Unlisted pulmonary service or procedure", 0.00),
]
for code, desc, rvu in pulm_codes:
    cat = "Medicine" if int(code) >= 94000 else "Surgery"
    new_codes[code] = make_cpt(code, desc, cat=cat, spec="pulmonology", rvu=rvu, glob=0, family="pulmonology")

# ============================================================
# 8. ADDITIONAL RADIOLOGY (200+ codes)
# ============================================================

radiology_codes = [
    # X-ray head/neck
    ("70030", "Radiologic examination eye for detection of foreign body", 0.34),
    ("70100", "Radiologic examination mandible partial less than 4 views", 0.27),
    ("70110", "Radiologic examination mandible complete minimum of 4 views", 0.32),
    ("70120", "Radiologic examination mastoids less than 3 views per side", 0.27),
    ("70130", "Radiologic examination mastoids complete minimum of 3 views per side", 0.32),
    ("70134", "Radiologic examination internal auditory meati complete", 0.32),
    ("70140", "Radiologic examination facial bones less than 3 views", 0.27),
    ("70150", "Radiologic examination facial bones complete minimum of 3 views", 0.34),
    ("70160", "Radiologic examination nasal bones complete minimum of 3 views", 0.27),
    ("70170", "Radiologic examination dacryocystography", 0.56),
    ("70190", "Radiologic examination optic foramina", 0.34),
    ("70200", "Radiologic examination orbits complete minimum of 4 views", 0.34),
    ("70210", "Radiologic examination sinuses paranasal less than 3 views", 0.22),
    ("70220", "Radiologic examination sinuses paranasal complete minimum of 3 views", 0.27),
    ("70240", "Radiologic examination sella turcica", 0.27),
    ("70250", "Radiologic examination skull less than 4 views", 0.27),
    ("70260", "Radiologic examination skull complete minimum of 4 views", 0.34),
    ("70300", "Radiologic examination teeth single view", 0.12),
    ("70310", "Radiologic examination teeth partial examination less than full mouth", 0.22),
    ("70320", "Radiologic examination teeth complete full mouth", 0.27),
    ("70328", "Radiologic examination temporomandibular joint open and closed mouth unilateral", 0.34),
    ("70330", "Radiologic examination temporomandibular joint open and closed mouth bilateral", 0.42),
    ("70332", "Temporomandibular joint arthrography radiological supervision and interpretation", 0.67),
    ("70336", "Magnetic resonance imaging temporomandibular joint", 1.56),
    ("70350", "Cephalogram orthodontic", 0.22),
    ("70355", "Orthopantogram panoramic", 0.22),
    ("70360", "Radiologic examination neck soft tissue", 0.22),
    ("70370", "Radiologic examination pharynx or larynx including fluoroscopy and/or magnification technique", 0.56),
    ("70371", "Complex dynamic pharyngeal and speech evaluation by cine or video recording", 0.89),
    ("70380", "Radiologic examination salivary gland for calculus", 0.27),
    ("70390", "Sialography radiological supervision and interpretation", 0.67),
    # Spine X-rays
    ("72020", "Radiologic examination spine single view specify level", 0.22),
    ("72040", "Radiologic examination spine cervical 2 or 3 views", 0.27),
    ("72050", "Radiologic examination spine cervical 4 or 5 views", 0.34),
    ("72052", "Radiologic examination spine cervical 6 or more views", 0.42),
    ("72070", "Radiologic examination spine thoracic 2 views", 0.27),
    ("72072", "Radiologic examination spine thoracic 3 views", 0.32),
    ("72074", "Radiologic examination spine thoracic minimum of 4 views", 0.37),
    ("72080", "Radiologic examination spine thoracolumbar junction minimum of 2 views", 0.27),
    ("72081", "Radiologic examination spine entire thoracic and lumbar including skull cervical and sacral if performed AP and lateral", 0.42),
    ("72082", "Radiologic examination spine entire thoracic and lumbar 2 or 3 views", 0.42),
    ("72083", "Radiologic examination spine entire thoracic and lumbar 4 or 5 views", 0.52),
    ("72084", "Radiologic examination spine entire thoracic and lumbar minimum of 6 views", 0.62),
    ("72100", "Radiologic examination spine lumbosacral 2 or 3 views", 0.32),
    ("72110", "Radiologic examination spine lumbosacral minimum of 4 views", 0.42),
    ("72114", "Radiologic examination spine lumbosacral complete including bending views minimum of 6 views", 0.52),
    ("72120", "Radiologic examination spine lumbosacral bending views only 2 or 3 views", 0.32),
    ("72170", "Radiologic examination pelvis 1 or 2 views", 0.22),
    ("72190", "Radiologic examination pelvis complete minimum of 3 views", 0.32),
    ("72200", "Radiologic examination sacroiliac joints less than 3 views", 0.22),
    ("72202", "Radiologic examination sacroiliac joints 3 or more views", 0.27),
    ("72220", "Radiologic examination sacrum and coccyx minimum of 2 views", 0.27),
    # Upper extremity X-rays
    ("73000", "Radiologic examination clavicle complete", 0.22),
    ("73010", "Radiologic examination scapula complete", 0.22),
    ("73020", "Radiologic examination shoulder 1 view", 0.17),
    ("73030", "Radiologic examination shoulder complete minimum of 2 views", 0.22),
    ("73050", "Radiologic examination acromioclavicular joints bilateral with or without weighted distraction", 0.27),
    ("73060", "Radiologic examination humerus minimum of 2 views", 0.22),
    ("73070", "Radiologic examination elbow 2 views", 0.22),
    ("73080", "Radiologic examination elbow complete minimum of 3 views", 0.27),
    ("73090", "Radiologic examination forearm 2 views", 0.22),
    ("73092", "Radiologic examination upper extremity infant minimum of 2 views", 0.22),
    ("73100", "Radiologic examination wrist 2 views", 0.22),
    ("73110", "Radiologic examination wrist complete minimum of 3 views", 0.27),
    ("73120", "Radiologic examination hand 2 views", 0.22),
    ("73130", "Radiologic examination hand minimum of 3 views", 0.27),
    ("73140", "Radiologic examination finger(s) minimum of 2 views", 0.17),
    # Lower extremity X-rays
    ("73500", "Radiologic examination hip unilateral with pelvis when performed 1 view", 0.22),
    ("73501", "Radiologic examination hip unilateral with pelvis when performed 2-3 views", 0.27),
    ("73502", "Radiologic examination hip unilateral with pelvis when performed minimum of 4 views", 0.32),
    ("73503", "Radiologic examination hip bilateral with pelvis when performed 2 views", 0.27),
    ("73521", "Radiologic examination hips bilateral with pelvis when performed 2 views", 0.27),
    ("73522", "Radiologic examination hips bilateral with pelvis when performed 3-4 views", 0.32),
    ("73523", "Radiologic examination hips bilateral with pelvis when performed minimum of 5 views", 0.42),
    ("73551", "Radiologic examination femur 1 view", 0.17),
    ("73552", "Radiologic examination femur minimum of 2 views", 0.22),
    ("73560", "Radiologic examination knee 1 or 2 views", 0.22),
    ("73562", "Radiologic examination knee 3 views", 0.27),
    ("73564", "Radiologic examination knee complete 4 or more views", 0.32),
    ("73565", "Radiologic examination knee both standing AP", 0.22),
    ("73580", "Radiologic examination knee arthrography radiological supervision and interpretation", 0.67),
    ("73590", "Radiologic examination tibia and fibula 2 views", 0.22),
    ("73592", "Radiologic examination lower extremity infant minimum of 2 views", 0.22),
    ("73600", "Radiologic examination ankle 2 views", 0.22),
    ("73610", "Radiologic examination ankle complete minimum of 3 views", 0.27),
    ("73620", "Radiologic examination foot 2 views", 0.22),
    ("73630", "Radiologic examination foot complete minimum of 3 views", 0.27),
    ("73650", "Radiologic examination calcaneus minimum of 2 views", 0.22),
    ("73660", "Radiologic examination toes minimum of 2 views", 0.17),
    # Fluoroscopy
    ("76000", "Fluoroscopy up to 1 hour physician or other qualified health care professional time", 1.12),
    ("76001", "Fluoroscopy physician or other qualified health care professional time more than 1 hour", 2.34),
    ("76010", "Radiologic examination from nose to rectum single view for foreign body", 0.42),
    ("76080", "Radiologic examination abscess fistula or sinus tract study radiological supervision and interpretation", 0.67),
    ("76098", "Radiological examination surgical specimen", 0.34),
    ("76100", "Radiologic examination single plane body section", 0.56),
    ("76101", "Radiologic examination complex motion body section other than with urography", 0.78),
    ("76102", "Radiologic examination complex motion body section other than with urography each additional section", 0.34),
    ("76120", "Cineradiography/videoradiography except where specifically included", 0.56),
    ("76125", "Cineradiography/videoradiography to complement routine examination", 0.34),
    ("76140", "Consultation on X-ray examination made elsewhere written report", 0.56),
    ("76376", "3D rendering with interpretation and reporting of computed tomography MRI ultrasound or other tomographic modality not requiring image postprocessing on an independent workstation", 0.34),
    ("76377", "3D rendering with interpretation and reporting requiring image postprocessing on an independent workstation", 0.56),
    ("76380", "Computed tomography limited or localized follow-up study", 0.89),
    ("76390", "Magnetic resonance spectroscopy", 1.23),
    # Bone density
    ("77080", "Dual-energy X-ray absorptiometry bone density study 1 or more sites axial skeleton", 0.34),
    ("77081", "Dual-energy X-ray absorptiometry bone density study appendicular skeleton peripheral", 0.22),
    ("77085", "Dual-energy X-ray absorptiometry bone density study 1 or more sites axial skeleton including vertebral fracture assessment", 0.52),
    ("77086", "Vertebral fracture assessment via dual-energy X-ray absorptiometry", 0.34),
    # Diagnostic ultrasound
    ("76506", "Echoencephalography B-scan and/or real time with image documentation", 0.67),
    ("76510", "Ophthalmic ultrasound diagnostic B-scan and quantitative A-scan performed during the same patient encounter", 1.12),
    ("76511", "Ophthalmic ultrasound diagnostic quantitative A-scan only", 0.89),
    ("76512", "Ophthalmic ultrasound diagnostic B-scan with or without superimposed non-quantitative A-scan", 0.89),
    ("76513", "Ophthalmic ultrasound diagnostic anterior segment by immersion B-scan or high resolution biomicroscopy", 0.78),
    ("76514", "Ophthalmic ultrasound diagnostic corneal pachymetry unilateral or bilateral determination", 0.23),
    ("76516", "Ophthalmic biometry by ultrasound echography A-scan", 0.45),
    ("76519", "Ophthalmic biometry by ultrasound echography A-scan with intraocular lens power calculation", 0.56),
    ("76529", "Ophthalmic ultrasonic foreign body localization", 0.67),
    ("76536", "Ultrasound soft tissues of head and neck real-time with image documentation", 0.67),
    ("76604", "Ultrasound chest real-time with image documentation", 0.56),
    ("76641", "Ultrasound breast unilateral real-time with image documentation complete", 0.89),
    ("76642", "Ultrasound breast unilateral real-time with image documentation limited", 0.67),
    ("76700", "Ultrasound abdominal real-time with image documentation complete", 0.89),
    ("76705", "Ultrasound abdominal real-time with image documentation limited", 0.67),
    ("76706", "Ultrasound abdominal aorta real-time with image documentation screening study for abdominal aortic aneurysm", 0.56),
    ("76770", "Ultrasound retroperitoneal real-time with image documentation complete", 0.89),
    ("76775", "Ultrasound retroperitoneal real-time with image documentation limited", 0.67),
    ("76776", "Ultrasound transplanted kidney real-time and duplex Doppler with image documentation", 1.12),
    ("76800", "Ultrasound spinal canal and contents", 0.89),
    ("76801", "Ultrasound pregnant uterus real-time with image documentation fetal and maternal evaluation first trimester single or first gestation", 1.23),
    ("76802", "Ultrasound pregnant uterus each additional gestation", 0.67),
    ("76805", "Ultrasound pregnant uterus real-time with image documentation fetal and maternal evaluation after first trimester single or first gestation", 1.34),
    ("76810", "Ultrasound pregnant uterus after first trimester each additional gestation", 0.67),
    ("76811", "Ultrasound pregnant uterus real-time with image documentation fetal and maternal evaluation detailed fetal anatomic examination single or first gestation", 2.34),
    ("76812", "Ultrasound pregnant uterus detailed fetal anatomic examination each additional gestation", 1.23),
    ("76813", "Ultrasound pregnant uterus real-time first trimester fetal nuchal translucency measurement single or first gestation", 1.45),
    ("76814", "Ultrasound pregnant uterus first trimester fetal nuchal translucency measurement each additional gestation", 0.78),
    ("76815", "Ultrasound pregnant uterus real-time with image documentation limited", 0.67),
    ("76816", "Ultrasound pregnant uterus real-time with image documentation follow-up", 0.78),
    ("76817", "Ultrasound pregnant uterus real-time with image documentation transvaginal", 1.12),
    ("76818", "Fetal biophysical profile with non-stress testing", 1.23),
    ("76819", "Fetal biophysical profile without non-stress testing", 0.89),
    ("76820", "Doppler velocimetry fetal umbilical artery", 0.56),
    ("76821", "Doppler velocimetry fetal middle cerebral artery", 0.56),
    ("76825", "Echocardiography fetal real-time with image documentation 2D with or without M-mode recording", 2.12),
    ("76826", "Echocardiography fetal follow-up or repeat study", 1.34),
    ("76827", "Doppler echocardiography fetal pulsed wave and/or continuous wave with spectral display", 0.56),
    ("76828", "Doppler echocardiography fetal complete", 0.45),
    ("76830", "Ultrasound transvaginal", 0.89),
    ("76831", "Saline infusion sonohysterography SIS including color flow Doppler when performed", 1.23),
    ("76856", "Ultrasound pelvic nonobstetric real-time with image documentation complete", 0.78),
    ("76857", "Ultrasound pelvic nonobstetric real-time with image documentation limited or follow-up", 0.56),
    ("76870", "Ultrasound scrotum and contents", 0.67),
    ("76872", "Ultrasound transrectal", 0.89),
    ("76881", "Ultrasound extremity nonvascular real-time with image documentation complete", 0.78),
    ("76882", "Ultrasound extremity nonvascular real-time with image documentation limited", 0.56),
    ("76885", "Ultrasound infant hips real-time with image documentation dynamic", 0.78),
    ("76886", "Ultrasound infant hips real-time with image documentation limited static", 0.56),
    # CT scans (basic)
    ("70450", "Computed tomography head or brain without contrast material", 1.23),
    ("70460", "Computed tomography head or brain with contrast material", 1.56),
    ("70470", "Computed tomography head or brain without contrast material followed by contrast material and further sections", 1.89),
    ("70480", "Computed tomography orbit sella or posterior fossa or outer middle or inner ear without contrast material", 1.34),
    ("70481", "Computed tomography orbit sella or posterior fossa or outer middle or inner ear with contrast material", 1.56),
    ("70482", "Computed tomography orbit sella or posterior fossa without contrast followed by contrast", 1.89),
    ("70486", "Computed tomography maxillofacial area without contrast material", 1.23),
    ("70487", "Computed tomography maxillofacial area with contrast material", 1.45),
    ("70488", "Computed tomography maxillofacial area without contrast followed by contrast", 1.78),
    ("70490", "Computed tomography soft tissue neck without contrast material", 1.23),
    ("70491", "Computed tomography soft tissue neck with contrast material", 1.45),
    ("70492", "Computed tomography soft tissue neck without contrast followed by contrast", 1.78),
    ("71250", "Computed tomography thorax without contrast material", 1.34),
    ("71260", "Computed tomography thorax with contrast material", 1.56),
    ("71270", "Computed tomography thorax without contrast followed by contrast", 1.89),
    ("71271", "Computed tomography thorax low dose for lung cancer screening", 1.12),
    ("72125", "Computed tomography cervical spine without contrast material", 1.34),
    ("72126", "Computed tomography cervical spine with contrast material", 1.56),
    ("72127", "Computed tomography cervical spine without contrast followed by contrast", 1.89),
    ("72128", "Computed tomography thoracic spine without contrast material", 1.34),
    ("72129", "Computed tomography thoracic spine with contrast material", 1.56),
    ("72130", "Computed tomography thoracic spine without contrast followed by contrast", 1.89),
    ("72131", "Computed tomography lumbar spine without contrast material", 1.34),
    ("72132", "Computed tomography lumbar spine with contrast material", 1.56),
    ("72133", "Computed tomography lumbar spine without contrast followed by contrast", 1.89),
    ("72192", "Computed tomography pelvis without contrast material", 1.34),
    ("72193", "Computed tomography pelvis with contrast material", 1.56),
    ("72194", "Computed tomography pelvis without contrast followed by contrast", 1.89),
    ("73200", "Computed tomography upper extremity without contrast material", 1.12),
    ("73201", "Computed tomography upper extremity with contrast material", 1.34),
    ("73202", "Computed tomography upper extremity without contrast followed by contrast", 1.67),
    ("73700", "Computed tomography lower extremity without contrast material", 1.12),
    ("73701", "Computed tomography lower extremity with contrast material", 1.34),
    ("73702", "Computed tomography lower extremity without contrast followed by contrast", 1.67),
    ("74150", "Computed tomography abdomen without contrast material", 1.34),
    ("74160", "Computed tomography abdomen with contrast material", 1.56),
    ("74170", "Computed tomography abdomen without contrast followed by contrast", 1.89),
    ("74176", "Computed tomography abdomen and pelvis without contrast material", 1.56),
    ("74177", "Computed tomography abdomen and pelvis with contrast material", 1.78),
    ("74178", "Computed tomography abdomen and pelvis without contrast followed by contrast", 2.12),
]
for code, desc, rvu in radiology_codes:
    new_codes[code] = make_cpt(code, desc, cat="Radiology", spec="radiology", rvu=rvu, glob=0, family="radiology")

# ============================================================
# 9. PM&R / PAIN (150+ codes)
# ============================================================

pain_codes = [
    # Epidural injections
    ("62320", "Injection including imaging guidance of diagnostic or therapeutic substance not including neurolytic substances interlaminar epidural or subarachnoid cervical or thoracic", 3.45, "epidural"),
    ("62321", "Injection including imaging guidance of diagnostic or therapeutic substance not including neurolytic substances interlaminar epidural or subarachnoid cervical or thoracic with imaging", 3.78, "epidural"),
    ("62322", "Injection including imaging guidance of diagnostic or therapeutic substance not including neurolytic substances interlaminar epidural or subarachnoid lumbar or sacral", 2.89, "epidural"),
    ("62323", "Injection including imaging guidance of diagnostic or therapeutic substance not including neurolytic substances interlaminar epidural or subarachnoid lumbar or sacral with imaging", 3.12, "epidural"),
    ("62324", "Injection including fluoroscopic guidance of diagnostic or therapeutic substance epidural cervical or thoracic transforaminal", 3.56, "epidural"),
    ("62325", "Injection including fluoroscopic guidance diagnostic or therapeutic epidural cervical or thoracic transforaminal each additional level", 1.78, "epidural"),
    ("62326", "Injection including fluoroscopic guidance of diagnostic or therapeutic substance epidural lumbar or sacral transforaminal", 3.12, "epidural"),
    ("62327", "Injection including fluoroscopic guidance diagnostic or therapeutic epidural lumbar or sacral transforaminal each additional level", 1.56, "epidural"),
    # Facet joint injections
    ("64490", "Injection including fluoroscopic guidance diagnostic or therapeutic agent paravertebral facet joint or facet joint nerve cervical or thoracic single level", 2.89, "facet_injection"),
    ("64491", "Injection paravertebral facet joint or facet joint nerve cervical or thoracic second level", 1.23, "facet_injection"),
    ("64492", "Injection paravertebral facet joint or facet joint nerve cervical or thoracic third and any additional levels", 1.12, "facet_injection"),
    ("64493", "Injection including fluoroscopic guidance diagnostic or therapeutic agent paravertebral facet joint or facet joint nerve lumbar or sacral single level", 2.56, "facet_injection"),
    ("64494", "Injection paravertebral facet joint or facet joint nerve lumbar or sacral second level", 1.12, "facet_injection"),
    ("64495", "Injection paravertebral facet joint or facet joint nerve lumbar or sacral third and any additional levels", 1.00, "facet_injection"),
    # Nerve blocks
    ("64400", "Injection anesthetic agent trigeminal nerve any division or branch", 1.56, "nerve_block"),
    ("64402", "Injection anesthetic agent facial nerve", 1.34, "nerve_block"),
    ("64405", "Injection anesthetic agent greater occipital nerve", 1.23, "nerve_block"),
    ("64408", "Injection anesthetic agent vagus nerve", 1.45, "nerve_block"),
    ("64410", "Injection anesthetic agent phrenic nerve", 1.34, "nerve_block"),
    ("64412", "Injection anesthetic agent spinal accessory nerve", 1.34, "nerve_block"),
    ("64413", "Injection anesthetic agent cervical plexus", 1.56, "nerve_block"),
    ("64415", "Injection anesthetic agent brachial plexus single", 2.12, "nerve_block"),
    ("64416", "Injection anesthetic agent brachial plexus continuous infusion by catheter", 2.89, "nerve_block"),
    ("64417", "Injection anesthetic agent axillary nerve", 1.89, "nerve_block"),
    ("64418", "Injection anesthetic agent suprascapular nerve", 1.45, "nerve_block"),
    ("64420", "Injection anesthetic agent intercostal nerve single", 1.23, "nerve_block"),
    ("64421", "Injection anesthetic agent intercostal nerves multiple regional block", 1.89, "nerve_block"),
    ("64425", "Injection anesthetic agent ilioinguinal iliohypogastric nerves", 1.56, "nerve_block"),
    ("64430", "Injection anesthetic agent pudendal nerve", 1.56, "nerve_block"),
    ("64435", "Injection anesthetic agent paracervical (uterine) nerve", 1.34, "nerve_block"),
    ("64445", "Injection anesthetic agent sciatic nerve single", 2.12, "nerve_block"),
    ("64446", "Injection anesthetic agent sciatic nerve continuous infusion by catheter", 2.89, "nerve_block"),
    ("64447", "Injection anesthetic agent femoral nerve single", 1.89, "nerve_block"),
    ("64448", "Injection anesthetic agent femoral nerve continuous infusion by catheter", 2.67, "nerve_block"),
    ("64449", "Injection anesthetic agent lumbar plexus posterior approach psoas compartment", 2.34, "nerve_block"),
    ("64450", "Injection anesthetic agent other peripheral nerve or branch", 1.23, "nerve_block"),
    ("64451", "Injection anesthetic agent nerves innervating the sacroiliac joint", 2.12, "nerve_block"),
    ("64454", "Injection anesthetic agent genicular nerve branches", 1.89, "nerve_block"),
    ("64455", "Injection anesthetic agent plantar common digital nerves", 1.12, "nerve_block"),
    # Neurolytic blocks
    ("64600", "Destruction by neurolytic agent trigeminal nerve supraoribtal supratrochlear or infraorbital", 3.45, "neurolytic"),
    ("64605", "Destruction by neurolytic agent trigeminal nerve second and third division branches at foramen ovale", 5.23, "neurolytic"),
    ("64610", "Destruction by neurolytic agent trigeminal nerve second and third division at foramen ovale under radiologic monitoring", 6.78, "neurolytic"),
    ("64620", "Destruction by neurolytic agent intercostal nerve", 2.34, "neurolytic"),
    ("64624", "Destruction by neurolytic agent genicular nerve branches", 3.56, "neurolytic"),
    ("64625", "Destruction by neurolytic agent of nerves innervating the sacroiliac joint", 3.89, "neurolytic"),
    ("64630", "Destruction by neurolytic agent pudendal nerve", 3.12, "neurolytic"),
    ("64633", "Destruction by neurolytic agent paravertebral facet joint nerve cervical or thoracic single level", 3.78, "neurolytic"),
    ("64634", "Destruction by neurolytic agent paravertebral facet joint nerve cervical or thoracic each additional level", 1.89, "neurolytic"),
    ("64635", "Destruction by neurolytic agent paravertebral facet joint nerve lumbar or sacral single level", 3.45, "neurolytic"),
    ("64636", "Destruction by neurolytic agent paravertebral facet joint nerve lumbar or sacral each additional level", 1.67, "neurolytic"),
    ("64640", "Destruction by neurolytic agent other peripheral nerve or branch", 2.89, "neurolytic"),
    ("64680", "Destruction by neurolytic agent celiac plexus with or without radiologic monitoring", 4.56, "neurolytic"),
    ("64681", "Destruction by neurolytic agent superior hypogastric plexus with or without radiologic monitoring", 4.23, "neurolytic"),
    # Neurostimulation
    ("63650", "Percutaneous implantation of neurostimulator electrode array epidural", 5.67, "neurostimulation"),
    ("63655", "Laminectomy for implantation of neurostimulator electrode array epidural", 12.34, "neurostimulation"),
    ("63661", "Removal of spinal neurostimulator electrode percutaneous array including fluoroscopy", 3.45, "neurostimulation"),
    ("63662", "Removal of spinal neurostimulator electrode plate/paddle including fluoroscopy", 8.67, "neurostimulation"),
    ("63663", "Revision including replacement of spinal neurostimulator electrode percutaneous array", 5.89, "neurostimulation"),
    ("63664", "Revision including replacement of spinal neurostimulator electrode plate/paddle", 10.23, "neurostimulation"),
    ("63685", "Insertion or replacement of spinal neurostimulator pulse generator or receiver direct or inductive coupling", 4.56, "neurostimulation"),
    ("63688", "Revision or removal of implanted spinal neurostimulator pulse generator or receiver", 3.89, "neurostimulation"),
    ("64553", "Percutaneous implantation of neurostimulator electrode array cranial nerve", 4.23, "neurostimulation"),
    ("64555", "Percutaneous implantation of neurostimulator electrode array peripheral nerve excludes sacral nerve", 3.89, "neurostimulation"),
    ("64561", "Percutaneous implantation of neurostimulator electrode array sacral nerve", 4.56, "neurostimulation"),
    ("64568", "Open implantation of cranial nerve neurostimulator electrode array and pulse generator", 12.34, "neurostimulation"),
    ("64569", "Revision or replacement of cranial nerve neurostimulator electrode array and/or pulse generator", 8.56, "neurostimulation"),
    ("64570", "Removal of cranial nerve neurostimulator electrode array and pulse generator", 6.78, "neurostimulation"),
    ("64575", "Open implantation of neurostimulator electrode array peripheral nerve excludes sacral nerve", 6.89, "neurostimulation"),
    ("64580", "Open implantation of neurostimulator electrode array sacral nerve", 7.23, "neurostimulation"),
    ("64581", "Open implantation of neurostimulator electrode array peripheral nerve", 7.56, "neurostimulation"),
    ("64585", "Revision or removal of peripheral neurostimulator electrode array", 4.23, "neurostimulation"),
    ("64590", "Insertion or replacement of peripheral or gastric neurostimulator pulse generator or receiver", 3.89, "neurostimulation"),
    ("64595", "Revision or removal of peripheral or gastric neurostimulator pulse generator or receiver", 3.12, "neurostimulation"),
    # PT/OT/Rehab codes
    ("97010", "Application of a modality hot or cold packs", 0.00, "pt_ot"),
    ("97012", "Application of a modality traction mechanical", 0.00, "pt_ot"),
    ("97014", "Application of a modality electrical stimulation unattended", 0.00, "pt_ot"),
    ("97016", "Application of a modality vasopneumatic devices", 0.00, "pt_ot"),
    ("97018", "Application of a modality paraffin bath", 0.00, "pt_ot"),
    ("97022", "Application of a modality whirlpool", 0.00, "pt_ot"),
    ("97024", "Application of a modality diathermy", 0.00, "pt_ot"),
    ("97026", "Application of a modality infrared", 0.00, "pt_ot"),
    ("97028", "Application of a modality ultraviolet", 0.00, "pt_ot"),
    ("97032", "Application of a modality electrical stimulation manual each 15 minutes", 0.45, "pt_ot"),
    ("97033", "Application of a modality iontophoresis each 15 minutes", 0.45, "pt_ot"),
    ("97034", "Application of a modality contrast baths each 15 minutes", 0.34, "pt_ot"),
    ("97035", "Application of a modality ultrasound each 15 minutes", 0.34, "pt_ot"),
    ("97036", "Application of a modality Hubbard tank each 15 minutes", 0.56, "pt_ot"),
    ("97039", "Unlisted modality", 0.00, "pt_ot"),
    ("97110", "Therapeutic procedure one or more areas each 15 minutes therapeutic exercises to develop strength and endurance flexibility and range of motion", 0.56, "pt_ot"),
    ("97112", "Therapeutic procedure one or more areas each 15 minutes neuromuscular reeducation of movement balance coordination kinesthetic sense posture and/or proprioception", 0.56, "pt_ot"),
    ("97113", "Therapeutic procedure one or more areas each 15 minutes aquatic therapy with therapeutic exercises", 0.56, "pt_ot"),
    ("97116", "Therapeutic procedure one or more areas each 15 minutes gait training", 0.56, "pt_ot"),
    ("97124", "Therapeutic procedure one or more areas each 15 minutes massage including effleurage petrissage and/or tapotement", 0.56, "pt_ot"),
    ("97129", "Therapeutic interventions that focus on cognitive function each 15 minutes initial", 0.56, "pt_ot"),
    ("97130", "Therapeutic interventions that focus on cognitive function each additional 15 minutes", 0.45, "pt_ot"),
    ("97139", "Unlisted therapeutic procedure", 0.00, "pt_ot"),
    ("97140", "Manual therapy techniques one or more regions each 15 minutes", 0.56, "pt_ot"),
    ("97150", "Therapeutic procedure group 2 or more individuals", 0.34, "pt_ot"),
    ("97161", "Physical therapy evaluation low complexity", 1.23, "pt_ot"),
    ("97162", "Physical therapy evaluation moderate complexity", 1.56, "pt_ot"),
    ("97163", "Physical therapy evaluation high complexity", 1.89, "pt_ot"),
    ("97164", "Physical therapy re-evaluation", 1.12, "pt_ot"),
    ("97165", "Occupational therapy evaluation low complexity", 1.23, "pt_ot"),
    ("97166", "Occupational therapy evaluation moderate complexity", 1.56, "pt_ot"),
    ("97167", "Occupational therapy evaluation high complexity", 1.89, "pt_ot"),
    ("97168", "Occupational therapy re-evaluation", 1.12, "pt_ot"),
    ("97530", "Therapeutic activities direct one-on-one patient contact each 15 minutes", 0.56, "pt_ot"),
    ("97533", "Sensory integrative techniques direct one-on-one patient contact each 15 minutes", 0.56, "pt_ot"),
    ("97535", "Self-care/home management training direct one-on-one patient contact each 15 minutes", 0.56, "pt_ot"),
    ("97537", "Community/work reintegration training direct one-on-one patient contact each 15 minutes", 0.56, "pt_ot"),
    ("97542", "Wheelchair management/propulsion training each 15 minutes", 0.56, "pt_ot"),
    ("97545", "Work hardening/conditioning initial 2 hours", 2.34, "pt_ot"),
    ("97546", "Work hardening/conditioning each additional hour", 0.89, "pt_ot"),
    ("97597", "Debridement open wound first 20 sq cm", 1.23, "pt_ot"),
    ("97598", "Debridement open wound each additional 20 sq cm", 0.56, "pt_ot"),
    ("97602", "Removal of devitalized tissue from wound selective debridement", 0.34, "pt_ot"),
    ("97605", "Negative pressure wound therapy including topical applications dressing assessment and instructions per session wound surface area up to 50 sq cm", 0.56, "pt_ot"),
    ("97606", "Negative pressure wound therapy wound surface area greater than 50 sq cm", 0.67, "pt_ot"),
    ("97610", "Low frequency non-contact non-thermal ultrasound per visit", 0.56, "pt_ot"),
    ("97750", "Physical performance test or measurement with written report each 15 minutes", 0.56, "pt_ot"),
    ("97755", "Assistive technology assessment direct one-on-one contact with written report each 15 minutes", 0.56, "pt_ot"),
    ("97760", "Orthotic management and training initial encounter each 15 minutes", 0.56, "pt_ot"),
    ("97761", "Prosthetic training initial encounter each 15 minutes", 0.56, "pt_ot"),
    ("97763", "Orthotic/prosthetic management and/or training subsequent encounter each 15 minutes", 0.56, "pt_ot"),
    ("97799", "Unlisted physical medicine/rehabilitation service or procedure", 0.00, "pt_ot"),
    # Chiropractic/Manipulation
    ("98925", "Osteopathic manipulative treatment 1-2 body regions", 0.67, "manipulation"),
    ("98926", "Osteopathic manipulative treatment 3-4 body regions", 0.89, "manipulation"),
    ("98927", "Osteopathic manipulative treatment 5-6 body regions", 1.12, "manipulation"),
    ("98928", "Osteopathic manipulative treatment 7-8 body regions", 1.34, "manipulation"),
    ("98929", "Osteopathic manipulative treatment 9-10 body regions", 1.56, "manipulation"),
    ("98940", "Chiropractic manipulative treatment spinal 1-2 regions", 0.67, "manipulation"),
    ("98941", "Chiropractic manipulative treatment spinal 3-4 regions", 0.89, "manipulation"),
    ("98942", "Chiropractic manipulative treatment spinal 5 regions", 1.12, "manipulation"),
    ("98943", "Chiropractic manipulative treatment extraspinal 1 or more regions", 0.56, "manipulation"),
    # Acupuncture
    ("97810", "Acupuncture 1 or more needles without electrical stimulation initial 15 minutes", 0.89, "acupuncture"),
    ("97811", "Acupuncture 1 or more needles without electrical stimulation each additional 15 minutes", 0.45, "acupuncture"),
    ("97813", "Acupuncture 1 or more needles with electrical stimulation initial 15 minutes", 1.12, "acupuncture"),
    ("97814", "Acupuncture 1 or more needles with electrical stimulation each additional 15 minutes", 0.56, "acupuncture"),
]
for code, desc, rvu, fam in pain_codes:
    cat = "Medicine" if int(code) >= 90000 or fam in ["pt_ot", "manipulation", "acupuncture"] else "Surgery"
    new_codes[code] = make_cpt(code, desc, cat=cat, spec="pain_management" if fam not in ["pt_ot", "manipulation", "acupuncture"] else "physical_medicine", rvu=rvu, glob=0, family=fam)

# ============================================================
# LOAD, MERGE, AND SAVE
# ============================================================

try:
    with open(DB_PATH, 'r') as f:
        db = json.load(f)
    
    before = len(db)
    added = 0
    for code, entry in new_codes.items():
        if code not in db:
            db[code] = entry
            added += 1
    
    with open(DB_PATH, 'w') as f:
        json.dump(db, f, indent=2)
    
    # Verify
    with open(DB_PATH, 'r') as f:
        verify = json.load(f)
    
    print(f"CPT Part 2: Before={before}, Added={added}, After={len(verify)}")
    print(f"JSON valid: {len(verify) > 0}")
    
except Exception as e:
    print(f"ERROR: {e}")
    import traceback
    traceback.print_exc()
