#!/usr/bin/env python3
"""Expand ICD-10 database Part 2: E00-E89, F01-F99, G00-G99, H00-H95, I00-I99."""
import json
import os

DB_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'icd10_database.json')

def make_icd10(code, desc, system, cpt_assoc=None):
    return {
        "code": code,
        "description": desc,
        "system": system,
        "common_cpt_associations": cpt_assoc or []
    }

new_codes = {}

# ============================================================
# E00-E89: ENDOCRINE/METABOLIC (300 codes)
# ============================================================

endocrine = [
    # Thyroid disorders (E00-E07)
    ("E00.0", "Congenital iodine-deficiency syndrome, neurological type", "endocrine"),
    ("E00.1", "Congenital iodine-deficiency syndrome, myxedematous type", "endocrine"),
    ("E00.2", "Congenital iodine-deficiency syndrome, mixed type", "endocrine"),
    ("E00.9", "Congenital iodine-deficiency syndrome, unspecified", "endocrine"),
    ("E01.0", "Iodine-deficiency related diffuse (endemic) goiter", "endocrine"),
    ("E01.1", "Iodine-deficiency related multinodular (endemic) goiter", "endocrine"),
    ("E01.2", "Iodine-deficiency related (endemic) goiter, unspecified", "endocrine"),
    ("E01.8", "Other iodine-deficiency related thyroid disorders", "endocrine"),
    ("E02", "Subclinical iodine-deficiency hypothyroidism", "endocrine"),
    ("E03.0", "Congenital hypothyroidism with diffuse goiter", "endocrine"),
    ("E03.1", "Congenital hypothyroidism without goiter", "endocrine"),
    ("E03.2", "Hypothyroidism due to medicaments and other exogenous substances", "endocrine"),
    ("E03.3", "Postinfectious hypothyroidism", "endocrine"),
    ("E03.4", "Atrophy of thyroid (acquired)", "endocrine"),
    ("E03.5", "Myxedema coma", "endocrine"),
    ("E03.8", "Other specified hypothyroidism", "endocrine"),
    ("E03.9", "Hypothyroidism, unspecified", "endocrine", ["84439"]),
    ("E04.0", "Nontoxic diffuse goiter", "endocrine", ["84436"]),
    ("E04.1", "Nontoxic single thyroid nodule", "endocrine", ["60100"]),
    ("E04.2", "Nontoxic multinodular goiter", "endocrine", ["60100"]),
    ("E04.8", "Other specified nontoxic goiter", "endocrine"),
    ("E04.9", "Nontoxic goiter, unspecified", "endocrine"),
    ("E05.00", "Thyrotoxicosis with diffuse goiter without thyrotoxic crisis", "endocrine", ["84436"]),
    ("E05.01", "Thyrotoxicosis with diffuse goiter with thyrotoxic crisis", "endocrine"),
    ("E05.10", "Thyrotoxicosis with toxic single thyroid nodule without thyrotoxic crisis", "endocrine"),
    ("E05.11", "Thyrotoxicosis with toxic single thyroid nodule with thyrotoxic crisis", "endocrine"),
    ("E05.20", "Thyrotoxicosis with toxic multinodular goiter without thyrotoxic crisis", "endocrine"),
    ("E05.21", "Thyrotoxicosis with toxic multinodular goiter with thyrotoxic crisis", "endocrine"),
    ("E05.30", "Thyrotoxicosis from ectopic thyroid tissue without thyrotoxic crisis", "endocrine"),
    ("E05.31", "Thyrotoxicosis from ectopic thyroid tissue with thyrotoxic crisis", "endocrine"),
    ("E05.40", "Thyrotoxicosis factitia without thyrotoxic crisis", "endocrine"),
    ("E05.41", "Thyrotoxicosis factitia with thyrotoxic crisis", "endocrine"),
    ("E05.80", "Other thyrotoxicosis without thyrotoxic crisis", "endocrine"),
    ("E05.81", "Other thyrotoxicosis with thyrotoxic crisis", "endocrine"),
    ("E05.90", "Thyrotoxicosis, unspecified without thyrotoxic crisis", "endocrine"),
    ("E05.91", "Thyrotoxicosis, unspecified with thyrotoxic crisis", "endocrine"),
    ("E06.0", "Acute thyroiditis", "endocrine"),
    ("E06.1", "Subacute thyroiditis", "endocrine"),
    ("E06.2", "Chronic thyroiditis with transient thyrotoxicosis", "endocrine"),
    ("E06.3", "Autoimmune thyroiditis", "endocrine", ["86376"]),
    ("E06.4", "Drug-induced thyroiditis", "endocrine"),
    ("E06.5", "Other chronic thyroiditis", "endocrine"),
    ("E06.9", "Thyroiditis, unspecified", "endocrine"),
    ("E07.0", "Hypersecretion of calcitonin", "endocrine"),
    ("E07.1", "Dyshormogenetic goiter", "endocrine"),
    ("E07.81", "Sick-euthyroid syndrome", "endocrine"),
    ("E07.89", "Other specified disorders of thyroid", "endocrine"),
    ("E07.9", "Disorder of thyroid, unspecified", "endocrine"),
    # Diabetes mellitus (E08-E13)
    ("E08.00", "Diabetes mellitus due to underlying condition with hyperosmolar nonketotic hyperglycemic coma", "endocrine"),
    ("E08.01", "Diabetes mellitus due to underlying condition with ketoacidosis", "endocrine"),
    ("E08.10", "Diabetes mellitus due to underlying condition with ketoacidosis without coma", "endocrine"),
    ("E08.11", "Diabetes mellitus due to underlying condition with ketoacidosis with coma", "endocrine"),
    ("E08.21", "Diabetes mellitus due to underlying condition with diabetic nephropathy", "endocrine", ["82570"]),
    ("E08.22", "Diabetes mellitus due to underlying condition with diabetic chronic kidney disease", "endocrine", ["82570"]),
    ("E08.29", "Diabetes mellitus due to underlying condition with other diabetic kidney complication", "endocrine"),
    ("E08.311", "Diabetes mellitus due to underlying condition with unspecified diabetic retinopathy with macular edema", "endocrine", ["92134"]),
    ("E08.319", "Diabetes mellitus due to underlying condition with unspecified diabetic retinopathy without macular edema", "endocrine", ["92134"]),
    ("E08.321", "Diabetes mellitus due to underlying condition with mild nonproliferative retinopathy with macular edema", "endocrine", ["92134"]),
    ("E08.329", "Diabetes mellitus due to underlying condition with mild nonproliferative retinopathy without macular edema", "endocrine", ["92134"]),
    ("E08.331", "Diabetes mellitus due to underlying condition with moderate nonproliferative retinopathy with macular edema", "endocrine", ["92134"]),
    ("E08.339", "Diabetes mellitus due to underlying condition with moderate nonproliferative retinopathy without macular edema", "endocrine", ["92134"]),
    ("E08.341", "Diabetes mellitus due to underlying condition with severe nonproliferative retinopathy with macular edema", "endocrine", ["92134"]),
    ("E08.349", "Diabetes mellitus due to underlying condition with severe nonproliferative retinopathy without macular edema", "endocrine", ["92134"]),
    ("E08.351", "Diabetes mellitus due to underlying condition with proliferative diabetic retinopathy with macular edema", "endocrine", ["92134"]),
    ("E08.359", "Diabetes mellitus due to underlying condition with proliferative diabetic retinopathy without macular edema", "endocrine", ["92134"]),
    ("E08.36", "Diabetes mellitus due to underlying condition with diabetic cataract", "endocrine", ["66984"]),
    ("E08.39", "Diabetes mellitus due to underlying condition with other diabetic ophthalmic complication", "endocrine"),
    ("E08.40", "Diabetes mellitus due to underlying condition with diabetic neuropathy, unspecified", "endocrine", ["95900"]),
    ("E08.41", "Diabetes mellitus due to underlying condition with diabetic mononeuropathy", "endocrine", ["95900"]),
    ("E08.42", "Diabetes mellitus due to underlying condition with diabetic polyneuropathy", "endocrine", ["95900"]),
    ("E08.43", "Diabetes mellitus due to underlying condition with diabetic autonomic neuropathy", "endocrine", ["95921"]),
    ("E08.44", "Diabetes mellitus due to underlying condition with diabetic amyotrophy", "endocrine", ["95900"]),
    ("E08.49", "Diabetes mellitus due to underlying condition with other diabetic neurological complication", "endocrine"),
    ("E08.51", "Diabetes mellitus due to underlying condition with diabetic peripheral angiopathy without gangrene", "endocrine", ["93922"]),
    ("E08.52", "Diabetes mellitus due to underlying condition with diabetic peripheral angiopathy with gangrene", "endocrine", ["11004"]),
    ("E08.59", "Diabetes mellitus due to underlying condition with other circulatory complications", "endocrine"),
    ("E08.610", "Diabetes mellitus due to underlying condition with diabetic neuropathic arthropathy", "endocrine"),
    ("E08.618", "Diabetes mellitus due to underlying condition with other diabetic arthropathy", "endocrine"),
    ("E08.620", "Diabetes mellitus due to underlying condition with diabetic dermatitis", "endocrine"),
    ("E08.621", "Diabetes mellitus due to underlying condition with foot ulcer", "endocrine", ["11042"]),
    ("E08.622", "Diabetes mellitus due to underlying condition with other skin ulcer", "endocrine", ["11042"]),
    ("E08.628", "Diabetes mellitus due to underlying condition with other skin complications", "endocrine"),
    ("E08.630", "Diabetes mellitus due to underlying condition with periodontal disease", "endocrine"),
    ("E08.638", "Diabetes mellitus due to underlying condition with other oral complications", "endocrine"),
    ("E08.641", "Diabetes mellitus due to underlying condition with hypoglycemia with coma", "endocrine"),
    ("E08.649", "Diabetes mellitus due to underlying condition with hypoglycemia without coma", "endocrine"),
    ("E08.65", "Diabetes mellitus due to underlying condition with hyperglycemia", "endocrine", ["82947"]),
    ("E08.69", "Diabetes mellitus due to underlying condition with other specified complication", "endocrine"),
    ("E08.8", "Diabetes mellitus due to underlying condition with unspecified complications", "endocrine"),
    ("E08.9", "Diabetes mellitus due to underlying condition without complications", "endocrine", ["82947"]),
    ("E09.00", "Drug or chemical induced diabetes mellitus with hyperosmolar nonketotic hyperglycemic coma", "endocrine"),
    ("E09.01", "Drug or chemical induced diabetes mellitus with ketoacidosis", "endocrine"),
    ("E09.10", "Drug or chemical induced diabetes mellitus with ketoacidosis without coma", "endocrine"),
    ("E09.11", "Drug or chemical induced diabetes mellitus with ketoacidosis with coma", "endocrine"),
    ("E09.21", "Drug or chemical induced diabetes mellitus with diabetic nephropathy", "endocrine", ["82570"]),
    ("E09.22", "Drug or chemical induced diabetes mellitus with diabetic chronic kidney disease", "endocrine", ["82570"]),
    ("E09.29", "Drug or chemical induced diabetes mellitus with other diabetic kidney complication", "endocrine"),
    ("E09.311", "Drug or chemical induced diabetes mellitus with unspecified diabetic retinopathy with macular edema", "endocrine", ["92134"]),
    ("E09.319", "Drug or chemical induced diabetes mellitus with unspecified diabetic retinopathy without macular edema", "endocrine", ["92134"]),
    ("E09.321", "Drug or chemical induced diabetes mellitus with mild nonproliferative retinopathy with macular edema", "endocrine", ["92134"]),
    ("E09.329", "Drug or chemical induced diabetes mellitus with mild nonproliferative retinopathy without macular edema", "endocrine", ["92134"]),
    ("E09.331", "Drug or chemical induced diabetes mellitus with moderate nonproliferative retinopathy with macular edema", "endocrine", ["92134"]),
    ("E09.339", "Drug or chemical induced diabetes mellitus with moderate nonproliferative retinopathy without macular edema", "endocrine", ["92134"]),
    ("E09.341", "Drug or chemical induced diabetes mellitus with severe nonproliferative retinopathy with macular edema", "endocrine", ["92134"]),
    ("E09.349", "Drug or chemical induced diabetes mellitus with severe nonproliferative retinopathy without macular edema", "endocrine", ["92134"]),
    ("E09.351", "Drug or chemical induced diabetes mellitus with proliferative diabetic retinopathy with macular edema", "endocrine", ["92134"]),
    ("E09.359", "Drug or chemical induced diabetes mellitus with proliferative diabetic retinopathy without macular edema", "endocrine", ["92134"]),
    ("E09.36", "Drug or chemical induced diabetes mellitus with diabetic cataract", "endocrine", ["66984"]),
    ("E09.39", "Drug or chemical induced diabetes mellitus with other diabetic ophthalmic complication", "endocrine"),
    ("E09.40", "Drug or chemical induced diabetes mellitus with neurological complications with diabetic neuropathy", "endocrine", ["95900"]),
    ("E09.41", "Drug or chemical induced diabetes mellitus with neurological complications with diabetic mononeuropathy", "endocrine", ["95900"]),
    ("E09.42", "Drug or chemical induced diabetes mellitus with neurological complications with diabetic polyneuropathy", "endocrine", ["95900"]),
    ("E09.43", "Drug or chemical induced diabetes mellitus with neurological complications with diabetic autonomic neuropathy", "endocrine", ["95921"]),
    ("E09.44", "Drug or chemical induced diabetes mellitus with neurological complications with diabetic amyotrophy", "endocrine", ["95900"]),
    ("E09.49", "Drug or chemical induced diabetes mellitus with neurological complications with other diabetic neurological complication", "endocrine"),
    ("E09.51", "Drug or chemical induced diabetes mellitus with diabetic peripheral angiopathy without gangrene", "endocrine", ["93922"]),
    ("E09.52", "Drug or chemical induced diabetes mellitus with diabetic peripheral angiopathy with gangrene", "endocrine", ["11004"]),
    ("E09.59", "Drug or chemical induced diabetes mellitus with other circulatory complications", "endocrine"),
    ("E09.610", "Drug or chemical induced diabetes mellitus with diabetic neuropathic arthropathy", "endocrine"),
    ("E09.618", "Drug or chemical induced diabetes mellitus with other diabetic arthropathy", "endocrine"),
    ("E09.620", "Drug or chemical induced diabetes mellitus with diabetic dermatitis", "endocrine"),
    ("E09.621", "Drug or chemical induced diabetes mellitus with foot ulcer", "endocrine", ["11042"]),
    ("E09.622", "Drug or chemical induced diabetes mellitus with other skin ulcer", "endocrine", ["11042"]),
    ("E09.628", "Drug or chemical induced diabetes mellitus with other skin complications", "endocrine"),
    ("E09.630", "Drug or chemical induced diabetes mellitus with periodontal disease", "endocrine"),
    ("E09.638", "Drug or chemical induced diabetes mellitus with other oral complications", "endocrine"),
    ("E09.641", "Drug or chemical induced diabetes mellitus with hypoglycemia with coma", "endocrine"),
    ("E09.649", "Drug or chemical induced diabetes mellitus with hypoglycemia without coma", "endocrine"),
    ("E09.65", "Drug or chemical induced diabetes mellitus with hyperglycemia", "endocrine", ["82947"]),
    ("E09.69", "Drug or chemical induced diabetes mellitus with other specified complication", "endocrine"),
    ("E09.8", "Drug or chemical induced diabetes mellitus with unspecified complications", "endocrine"),
    ("E09.9", "Drug or chemical induced diabetes mellitus without complications", "endocrine", ["82947"]),
    ("E10.10", "Type 1 diabetes mellitus with ketoacidosis without coma", "endocrine", ["82962"]),
    ("E10.11", "Type 1 diabetes mellitus with ketoacidosis with coma", "endocrine", ["82962"]),
    ("E10.21", "Type 1 diabetes mellitus with diabetic nephropathy", "endocrine", ["82570"]),
    ("E10.22", "Type 1 diabetes mellitus with diabetic chronic kidney disease", "endocrine", ["82570"]),
    ("E10.29", "Type 1 diabetes mellitus with other diabetic kidney complication", "endocrine"),
    ("E10.311", "Type 1 diabetes mellitus with unspecified diabetic retinopathy with macular edema", "endocrine", ["92134"]),
    ("E10.319", "Type 1 diabetes mellitus with unspecified diabetic retinopathy without macular edema", "endocrine", ["92134"]),
    ("E10.321", "Type 1 diabetes mellitus with mild nonproliferative diabetic retinopathy with macular edema", "endocrine", ["92134"]),
    ("E10.329", "Type 1 diabetes mellitus with mild nonproliferative diabetic retinopathy without macular edema", "endocrine", ["92134"]),
    ("E10.331", "Type 1 diabetes mellitus with moderate nonproliferative diabetic retinopathy with macular edema", "endocrine", ["92134"]),
    ("E10.339", "Type 1 diabetes mellitus with moderate nonproliferative diabetic retinopathy without macular edema", "endocrine", ["92134"]),
    ("E10.341", "Type 1 diabetes mellitus with severe nonproliferative diabetic retinopathy with macular edema", "endocrine", ["92134"]),
    ("E10.349", "Type 1 diabetes mellitus with severe nonproliferative diabetic retinopathy without macular edema", "endocrine", ["92134"]),
    ("E10.351", "Type 1 diabetes mellitus with proliferative diabetic retinopathy with macular edema", "endocrine", ["92134"]),
    ("E10.359", "Type 1 diabetes mellitus with proliferative diabetic retinopathy without macular edema", "endocrine", ["92134"]),
    ("E10.36", "Type 1 diabetes mellitus with diabetic cataract", "endocrine", ["66984"]),
    ("E10.39", "Type 1 diabetes mellitus with other diabetic ophthalmic complication", "endocrine"),
    ("E10.40", "Type 1 diabetes mellitus with diabetic neuropathy, unspecified", "endocrine", ["95900"]),
    ("E10.41", "Type 1 diabetes mellitus with diabetic mononeuropathy", "endocrine", ["95900"]),
    ("E10.42", "Type 1 diabetes mellitus with diabetic polyneuropathy", "endocrine", ["95900"]),
    ("E10.43", "Type 1 diabetes mellitus with diabetic autonomic neuropathy", "endocrine", ["95921"]),
    ("E10.44", "Type 1 diabetes mellitus with diabetic amyotrophy", "endocrine", ["95900"]),
    ("E10.49", "Type 1 diabetes mellitus with other diabetic neurological complication", "endocrine"),
    ("E10.51", "Type 1 diabetes mellitus with diabetic peripheral angiopathy without gangrene", "endocrine", ["93922"]),
    ("E10.52", "Type 1 diabetes mellitus with diabetic peripheral angiopathy with gangrene", "endocrine", ["11004"]),
    ("E10.59", "Type 1 diabetes mellitus with other circulatory complications", "endocrine"),
    ("E10.610", "Type 1 diabetes mellitus with diabetic neuropathic arthropathy", "endocrine"),
    ("E10.618", "Type 1 diabetes mellitus with other diabetic arthropathy", "endocrine"),
    ("E10.620", "Type 1 diabetes mellitus with diabetic dermatitis", "endocrine"),
    ("E10.621", "Type 1 diabetes mellitus with foot ulcer", "endocrine", ["11042"]),
    ("E10.622", "Type 1 diabetes mellitus with other skin ulcer", "endocrine", ["11042"]),
    ("E10.628", "Type 1 diabetes mellitus with other skin complications", "endocrine"),
    ("E10.630", "Type 1 diabetes mellitus with periodontal disease", "endocrine"),
    ("E10.638", "Type 1 diabetes mellitus with other oral complications", "endocrine"),
    ("E10.641", "Type 1 diabetes mellitus with hypoglycemia with coma", "endocrine"),
    ("E10.649", "Type 1 diabetes mellitus with hypoglycemia without coma", "endocrine"),
    ("E10.65", "Type 1 diabetes mellitus with hyperglycemia", "endocrine", ["82947"]),
    ("E10.69", "Type 1 diabetes mellitus with other specified complication", "endocrine"),
    ("E10.8", "Type 1 diabetes mellitus with unspecified complications", "endocrine"),
    ("E10.9", "Type 1 diabetes mellitus without complications", "endocrine", ["82947"]),
    ("E11.00", "Type 2 diabetes mellitus with hyperosmolar nonketotic hyperglycemic coma", "endocrine"),
    ("E11.01", "Type 2 diabetes mellitus with ketoacidosis", "endocrine"),
    ("E11.21", "Type 2 diabetes mellitus with diabetic nephropathy", "endocrine", ["82570"]),
    ("E11.22", "Type 2 diabetes mellitus with diabetic chronic kidney disease", "endocrine", ["82570"]),
    ("E11.29", "Type 2 diabetes mellitus with other diabetic kidney complication", "endocrine"),
    ("E11.311", "Type 2 diabetes mellitus with unspecified diabetic retinopathy with macular edema", "endocrine", ["92134"]),
    ("E11.319", "Type 2 diabetes mellitus with unspecified diabetic retinopathy without macular edema", "endocrine", ["92134"]),
    ("E11.321", "Type 2 diabetes mellitus with mild nonproliferative diabetic retinopathy with macular edema", "endocrine", ["92134"]),
    ("E11.329", "Type 2 diabetes mellitus with mild nonproliferative diabetic retinopathy without macular edema", "endocrine", ["92134"]),
    ("E11.331", "Type 2 diabetes mellitus with moderate nonproliferative diabetic retinopathy with macular edema", "endocrine", ["92134"]),
    ("E11.339", "Type 2 diabetes mellitus with moderate nonproliferative diabetic retinopathy without macular edema", "endocrine", ["92134"]),
    ("E11.341", "Type 2 diabetes mellitus with severe nonproliferative diabetic retinopathy with macular edema", "endocrine", ["92134"]),
    ("E11.349", "Type 2 diabetes mellitus with severe nonproliferative diabetic retinopathy without macular edema", "endocrine", ["92134"]),
    ("E11.351", "Type 2 diabetes mellitus with proliferative diabetic retinopathy with macular edema", "endocrine", ["92134"]),
    ("E11.359", "Type 2 diabetes mellitus with proliferative diabetic retinopathy without macular edema", "endocrine", ["92134"]),
    ("E11.36", "Type 2 diabetes mellitus with diabetic cataract", "endocrine", ["66984"]),
    ("E11.39", "Type 2 diabetes mellitus with other diabetic ophthalmic complication", "endocrine"),
    ("E11.40", "Type 2 diabetes mellitus with diabetic neuropathy, unspecified", "endocrine", ["95900"]),
    ("E11.41", "Type 2 diabetes mellitus with diabetic mononeuropathy", "endocrine", ["95900"]),
    ("E11.42", "Type 2 diabetes mellitus with diabetic polyneuropathy", "endocrine", ["95900"]),
    ("E11.43", "Type 2 diabetes mellitus with diabetic autonomic neuropathy", "endocrine", ["95921"]),
    ("E11.44", "Type 2 diabetes mellitus with diabetic amyotrophy", "endocrine", ["95900"]),
    ("E11.49", "Type 2 diabetes mellitus with other diabetic neurological complication", "endocrine"),
    ("E11.51", "Type 2 diabetes mellitus with diabetic peripheral angiopathy without gangrene", "endocrine", ["93922"]),
    ("E11.52", "Type 2 diabetes mellitus with diabetic peripheral angiopathy with gangrene", "endocrine", ["11004"]),
    ("E11.59", "Type 2 diabetes mellitus with other circulatory complications", "endocrine"),
    ("E11.610", "Type 2 diabetes mellitus with diabetic neuropathic arthropathy", "endocrine"),
    ("E11.618", "Type 2 diabetes mellitus with other diabetic arthropathy", "endocrine"),
    ("E11.620", "Type 2 diabetes mellitus with diabetic dermatitis", "endocrine"),
    ("E11.621", "Type 2 diabetes mellitus with foot ulcer", "endocrine", ["11042"]),
    ("E11.622", "Type 2 diabetes mellitus with other skin ulcer", "endocrine", ["11042"]),
    ("E11.628", "Type 2 diabetes mellitus with other skin complications", "endocrine"),
    ("E11.630", "Type 2 diabetes mellitus with periodontal disease", "endocrine"),
    ("E11.638", "Type 2 diabetes mellitus with other oral complications", "endocrine"),
    ("E11.641", "Type 2 diabetes mellitus with hypoglycemia with coma", "endocrine"),
    ("E11.649", "Type 2 diabetes mellitus with hypoglycemia without coma", "endocrine"),
    ("E11.65", "Type 2 diabetes mellitus with hyperglycemia", "endocrine", ["82947"]),
    ("E11.69", "Type 2 diabetes mellitus with other specified complication", "endocrine"),
    ("E11.8", "Type 2 diabetes mellitus with unspecified complications", "endocrine"),
    ("E11.9", "Type 2 diabetes mellitus without complications", "endocrine", ["82947"]),
    ("E13.00", "Other specified diabetes mellitus with hyperosmolar nonketotic hyperglycemic coma", "endocrine"),
    ("E13.01", "Other specified diabetes mellitus with ketoacidosis", "endocrine"),
    ("E13.10", "Other specified diabetes mellitus with ketoacidosis without coma", "endocrine"),
    ("E13.11", "Other specified diabetes mellitus with ketoacidosis with coma", "endocrine"),
    ("E13.21", "Other specified diabetes mellitus with diabetic nephropathy", "endocrine", ["82570"]),
    ("E13.22", "Other specified diabetes mellitus with diabetic chronic kidney disease", "endocrine", ["82570"]),
    ("E13.29", "Other specified diabetes mellitus with other diabetic kidney complication", "endocrine"),
    ("E13.311", "Other specified diabetes mellitus with unspecified diabetic retinopathy with macular edema", "endocrine", ["92134"]),
    ("E13.319", "Other specified diabetes mellitus with unspecified diabetic retinopathy without macular edema", "endocrine", ["92134"]),
    ("E13.321", "Other specified diabetes mellitus with mild nonproliferative diabetic retinopathy with macular edema", "endocrine", ["92134"]),
    ("E13.329", "Other specified diabetes mellitus with mild nonproliferative diabetic retinopathy without macular edema", "endocrine", ["92134"]),
    ("E13.331", "Other specified diabetes mellitus with moderate nonproliferative diabetic retinopathy with macular edema", "endocrine", ["92134"]),
    ("E13.339", "Other specified diabetes mellitus with moderate nonproliferative diabetic retinopathy without macular edema", "endocrine", ["92134"]),
    ("E13.341", "Other specified diabetes mellitus with severe nonproliferative diabetic retinopathy with macular edema", "endocrine", ["92134"]),
    ("E13.349", "Other specified diabetes mellitus with severe nonproliferative diabetic retinopathy without macular edema", "endocrine", ["92134"]),
    ("E13.351", "Other specified diabetes mellitus with proliferative diabetic retinopathy with macular edema", "endocrine", ["92134"]),
    ("E13.359", "Other specified diabetes mellitus with proliferative diabetic retinopathy without macular edema", "endocrine", ["92134"]),
    ("E13.36", "Other specified diabetes mellitus with diabetic cataract", "endocrine", ["66984"]),
    ("E13.39", "Other specified diabetes mellitus with other diabetic ophthalmic complication", "endocrine"),
    ("E13.40", "Other specified diabetes mellitus with diabetic neuropathy, unspecified", "endocrine", ["95900"]),
    ("E13.41", "Other specified diabetes mellitus with diabetic mononeuropathy", "endocrine", ["95900"]),
    ("E13.42", "Other specified diabetes mellitus with diabetic polyneuropathy", "endocrine", ["95900"]),
    ("E13.43", "Other specified diabetes mellitus with diabetic autonomic neuropathy", "endocrine", ["95921"]),
    ("E13.44", "Other specified diabetes mellitus with diabetic amyotrophy", "endocrine", ["95900"]),
    ("E13.49", "Other specified diabetes mellitus with other diabetic neurological complication", "endocrine"),
    ("E13.51", "Other specified diabetes mellitus with diabetic peripheral angiopathy without gangrene", "endocrine", ["93922"]),
    ("E13.52", "Other specified diabetes mellitus with diabetic peripheral angiopathy with gangrene", "endocrine", ["11004"]),
    ("E13.59", "Other specified diabetes mellitus with other circulatory complications", "endocrine"),
    ("E13.610", "Other specified diabetes mellitus with diabetic neuropathic arthropathy", "endocrine"),
    ("E13.618", "Other specified diabetes mellitus with other diabetic arthropathy", "endocrine"),
    ("E13.620", "Other specified diabetes mellitus with diabetic dermatitis", "endocrine"),
    ("E13.621", "Other specified diabetes mellitus with foot ulcer", "endocrine", ["11042"]),
    ("E13.622", "Other specified diabetes mellitus with other skin ulcer", "endocrine", ["11042"]),
    ("E13.628", "Other specified diabetes mellitus with other skin complications", "endocrine"),
    ("E13.630", "Other specified diabetes mellitus with periodontal disease", "endocrine"),
    ("E13.638", "Other specified diabetes mellitus with other oral complications", "endocrine"),
    ("E13.641", "Other specified diabetes mellitus with hypoglycemia with coma", "endocrine"),
    ("E13.649", "Other specified diabetes mellitus with hypoglycemia without coma", "endocrine"),
    ("E13.65", "Other specified diabetes mellitus with hyperglycemia", "endocrine", ["82947"]),
    ("E13.69", "Other specified diabetes mellitus with other specified complication", "endocrine"),
    ("E13.8", "Other specified diabetes mellitus with unspecified complications", "endocrine"),
    ("E13.9", "Other specified diabetes mellitus without complications", "endocrine", ["82947"]),
    # Other endocrine disorders (E15-E35)
    ("E15", "Nondiabetic hypoglycemic coma", "endocrine"),
    ("E16.0", "Drug-induced hypoglycemia without coma", "endocrine"),
    ("E16.1", "Other hypoglycemia", "endocrine"),
    ("E16.2", "Hypoglycemia, unspecified", "endocrine"),
    ("E16.3", "Increased secretion of glucagon", "endocrine"),
    ("E16.4", "Abnormal secretion of gastrin", "endocrine"),
    ("E16.8", "Other specified disorders of pancreatic internal secretion", "endocrine"),
    ("E16.9", "Disorder of pancreatic internal secretion, unspecified", "endocrine"),
    ("E20.0", "Idiopathic hypoparathyroidism", "endocrine", ["83970"]),
    ("E20.1", "Pseudohypoparathyroidism", "endocrine", ["83970"]),
    ("E20.8", "Other hypoparathyroidism", "endocrine", ["83970"]),
    ("E20.9", "Hypoparathyroidism, unspecified", "endocrine", ["83970"]),
    ("E21.0", "Primary hyperparathyroidism", "endocrine", ["83970"]),
    ("E21.1", "Secondary hyperparathyroidism, not elsewhere classified", "endocrine", ["83970"]),
    ("E21.2", "Other hyperparathyroidism", "endocrine", ["83970"]),
    ("E21.3", "Hyperparathyroidism, unspecified", "endocrine", ["83970"]),
    ("E21.4", "Other specified disorders of parathyroid gland", "endocrine"),
    ("E21.5", "Disorder of parathyroid gland, unspecified", "endocrine"),
    ("E22.0", "Acromegaly and pituitary gigantism", "endocrine", ["83003"]),
    ("E22.1", "Hyperprolactinemia", "endocrine", ["84146"]),
    ("E22.2", "Syndrome of inappropriate secretion of antidiuretic hormone", "endocrine"),
    ("E22.8", "Other hyperfunction of pituitary gland", "endocrine"),
    ("E22.9", "Hyperfunction of pituitary gland, unspecified", "endocrine"),
    ("E23.0", "Hypopituitarism", "endocrine", ["83003"]),
    ("E23.1", "Drug-induced hypopituitarism", "endocrine", ["83003"]),
    ("E23.2", "Diabetes insipidus", "endocrine", ["82930"]),
    ("E23.3", "Hypothalamic dysfunction, not elsewhere classified", "endocrine"),
    ("E23.6", "Other disorders of pituitary gland", "endocrine"),
    ("E23.7", "Disorder of pituitary gland, unspecified", "endocrine"),
    ("E24.0", "Pituitary-dependent Cushing's disease", "endocrine", ["82533"]),
    ("E24.1", "Nelson's syndrome", "endocrine", ["82533"]),
    ("E24.2", "Drug-induced Cushing's syndrome", "endocrine", ["82533"]),
    ("E24.3", "Ectopic ACTH syndrome", "endocrine", ["82024"]),
    ("E24.4", "Alcohol-induced pseudo-Cushing's syndrome", "endocrine"),
    ("E24.8", "Other Cushing's syndrome", "endocrine", ["82533"]),
    ("E24.9", "Cushing's syndrome, unspecified", "endocrine", ["82533"]),
    ("E25.0", "Congenital adrenogenital disorders associated with enzyme deficiency", "endocrine"),
    ("E25.8", "Other adrenogenital disorders", "endocrine"),
    ("E25.9", "Adrenogenital disorder, unspecified", "endocrine"),
    ("E26.01", "Conn's syndrome", "endocrine", ["82088"]),
    ("E26.02", "Glucocorticoid-remediable aldosteronism", "endocrine", ["82088"]),
    ("E26.09", "Other primary hyperaldosteronism", "endocrine", ["82088"]),
    ("E26.1", "Secondary hyperaldosteronism", "endocrine", ["82088"]),
    ("E26.81", "Bartter's syndrome", "endocrine"),
    ("E26.89", "Other hyperaldosteronism", "endocrine", ["82088"]),
    ("E26.9", "Hyperaldosteronism, unspecified", "endocrine", ["82088"]),
    ("E27.0", "Other adrenocortical overactivity", "endocrine"),
    ("E27.1", "Primary adrenocortical insufficiency", "endocrine", ["82533"]),
    ("E27.2", "Addisonian crisis", "endocrine"),
    ("E27.3", "Drug-induced adrenocortical insufficiency", "endocrine", ["82533"]),
    ("E27.40", "Unspecified adrenocortical insufficiency", "endocrine", ["82533"]),
    ("E27.49", "Other adrenocortical insufficiency", "endocrine", ["82533"]),
    ("E27.5", "Adrenomedullary hyperfunction", "endocrine"),
    ("E27.8", "Other specified disorders of adrenal gland", "endocrine"),
    ("E27.9", "Disorder of adrenal gland, unspecified", "endocrine"),
    ("E28.0", "Estrogen excess", "endocrine"),
    ("E28.1", "Androgen excess", "endocrine"),
    ("E28.2", "Polycystic ovarian syndrome", "endocrine", ["83002"]),
    ("E28.310", "Symptomatic premature menopause", "endocrine"),
    ("E28.319", "Asymptomatic premature menopause", "endocrine"),
    ("E28.39", "Other primary ovarian failure", "endocrine"),
    ("E28.8", "Other ovarian dysfunction", "endocrine"),
    ("E28.9", "Ovarian dysfunction, unspecified", "endocrine"),
    ("E29.0", "Testicular hyperfunction", "endocrine"),
    ("E29.1", "Testicular hypofunction", "endocrine", ["84402"]),
    ("E29.8", "Other testicular dysfunction", "endocrine"),
    ("E29.9", "Testicular dysfunction, unspecified", "endocrine"),
    ("E30.0", "Delayed puberty", "endocrine"),
    ("E30.1", "Precocious puberty", "endocrine"),
    ("E30.8", "Other disorders of puberty", "endocrine"),
    ("E30.9", "Disorder of puberty, unspecified", "endocrine"),
    ("E31.0", "Autoimmune polyglandular failure", "endocrine"),
    ("E31.1", "Polyglandular hyperfunction", "endocrine"),
    ("E31.8", "Other polyglandular dysfunction", "endocrine"),
    ("E31.9", "Polyglandular dysfunction, unspecified", "endocrine"),
    ("E32.0", "Persistent hyperplasia of thymus", "endocrine"),
    ("E32.1", "Abscess of thymus", "endocrine"),
    ("E32.8", "Other diseases of thymus", "endocrine"),
    ("E32.9", "Disease of thymus, unspecified", "endocrine"),
    ("E34.0", "Carcinoid syndrome", "endocrine"),
    ("E34.1", "Other hypersecretion of intestinal hormones", "endocrine"),
    ("E34.2", "Ectopic hormone secretion, not elsewhere classified", "endocrine"),
    ("E34.3", "Short stature due to endocrine disorder", "endocrine"),
    ("E34.4", "Constitutional tall stature", "endocrine"),
    ("E34.50", "Androgen insensitivity syndrome, unspecified", "endocrine"),
    ("E34.51", "Complete androgen insensitivity syndrome", "endocrine"),
    ("E34.52", "Partial androgen insensitivity syndrome", "endocrine"),
    ("E34.8", "Other specified endocrine disorders", "endocrine"),
    ("E34.9", "Endocrine disorder, unspecified", "endocrine"),
    ("E35", "Disorders of endocrine glands in diseases classified elsewhere", "endocrine"),
]
for item in endocrine:
    if len(item) == 3:
        code, desc, system = item
        cpt = None
    else:
        code, desc, system, cpt = item
    new_codes[code] = make_icd10(code, desc, system, cpt)

# ============================================================
# F01-F99: MENTAL/BEHAVIORAL (200 codes)
# ============================================================

mental_behavioral = [
    # Dementia (F01-F03)
    ("F01.50", "Vascular dementia without behavioral disturbance", "mental"),
    ("F01.51", "Vascular dementia with behavioral disturbance", "mental"),
    ("F02.80", "Dementia in other diseases classified elsewhere without behavioral disturbance", "mental"),
    ("F02.81", "Dementia in other diseases classified elsewhere with behavioral disturbance", "mental"),
    ("F03.90", "Unspecified dementia without behavioral disturbance", "mental"),
    ("F03.91", "Unspecified dementia with behavioral disturbance", "mental"),
    # Mental disorders due to substance use (F10-F19)
    ("F10.10", "Alcohol abuse, uncomplicated", "mental", ["80320"]),
    ("F10.11", "Alcohol abuse, in remission", "mental"),
    ("F10.12", "Alcohol abuse with intoxication, uncomplicated", "mental", ["80320"]),
    ("F10.120", "Alcohol abuse with intoxication, uncomplicated", "mental", ["80320"]),
    ("F10.121", "Alcohol abuse with intoxication delirium", "mental"),
    ("F10.129", "Alcohol abuse with intoxication, unspecified", "mental", ["80320"]),
    ("F10.14", "Alcohol abuse with alcohol-induced mood disorder", "mental"),
    ("F10.150", "Alcohol abuse with alcohol-induced psychotic disorder with delusions", "mental"),
    ("F10.151", "Alcohol abuse with alcohol-induced psychotic disorder with hallucinations", "mental"),
    ("F10.159", "Alcohol abuse with alcohol-induced psychotic disorder, unspecified", "mental"),
    ("F10.180", "Alcohol abuse with alcohol-induced anxiety disorder", "mental"),
    ("F10.181", "Alcohol abuse with alcohol-induced sexual dysfunction", "mental"),
    ("F10.182", "Alcohol abuse with alcohol-induced sleep disorder", "mental"),
    ("F10.188", "Alcohol abuse with other alcohol-induced disorder", "mental"),
    ("F10.19", "Alcohol abuse with unspecified alcohol-induced disorder", "mental"),
    ("F10.20", "Alcohol dependence, uncomplicated", "mental", ["80320"]),
    ("F10.21", "Alcohol dependence, in remission", "mental"),
    ("F10.220", "Alcohol dependence with intoxication, uncomplicated", "mental", ["80320"]),
    ("F10.221", "Alcohol dependence with intoxication delirium", "mental"),
    ("F10.229", "Alcohol dependence with intoxication, unspecified", "mental", ["80320"]),
    ("F10.230", "Alcohol dependence with withdrawal, uncomplicated", "mental"),
    ("F10.231", "Alcohol dependence with withdrawal delirium", "mental"),
    ("F10.232", "Alcohol dependence with withdrawal with perceptual disturbance", "mental"),
    ("F10.239", "Alcohol dependence with withdrawal, unspecified", "mental"),
    ("F10.24", "Alcohol dependence with alcohol-induced mood disorder", "mental"),
    ("F10.250", "Alcohol dependence with alcohol-induced psychotic disorder with delusions", "mental"),
    ("F10.251", "Alcohol dependence with alcohol-induced psychotic disorder with hallucinations", "mental"),
    ("F10.259", "Alcohol dependence with alcohol-induced psychotic disorder, unspecified", "mental"),
    ("F10.26", "Alcohol dependence with alcohol-induced persisting amnestic disorder", "mental"),
    ("F10.27", "Alcohol dependence with alcohol-induced persisting dementia", "mental"),
    ("F10.280", "Alcohol dependence with alcohol-induced anxiety disorder", "mental"),
    ("F10.281", "Alcohol dependence with alcohol-induced sexual dysfunction", "mental"),
    ("F10.282", "Alcohol dependence with alcohol-induced sleep disorder", "mental"),
    ("F10.288", "Alcohol dependence with other alcohol-induced disorder", "mental"),
    ("F10.29", "Alcohol dependence with unspecified alcohol-induced disorder", "mental"),
    ("F10.920", "Alcohol use, unspecified with intoxication, uncomplicated", "mental", ["80320"]),
    ("F10.921", "Alcohol use, unspecified with intoxication delirium", "mental"),
    ("F10.929", "Alcohol use, unspecified with intoxication, unspecified", "mental", ["80320"]),
    ("F10.930", "Alcohol use, unspecified with withdrawal, uncomplicated", "mental"),
    ("F10.931", "Alcohol use, unspecified with withdrawal delirium", "mental"),
    ("F10.932", "Alcohol use, unspecified with withdrawal with perceptual disturbance", "mental"),
    ("F10.939", "Alcohol use, unspecified with withdrawal, unspecified", "mental"),
    ("F10.94", "Alcohol use, unspecified with alcohol-induced mood disorder", "mental"),
    ("F10.950", "Alcohol use, unspecified with alcohol-induced psychotic disorder with delusions", "mental"),
    ("F10.951", "Alcohol use, unspecified with alcohol-induced psychotic disorder with hallucinations", "mental"),
    ("F10.959", "Alcohol use, unspecified with alcohol-induced psychotic disorder, unspecified", "mental"),
    ("F10.96", "Alcohol use, unspecified with alcohol-induced persisting amnestic disorder", "mental"),
    ("F10.97", "Alcohol use, unspecified with alcohol-induced persisting dementia", "mental"),
    ("F10.980", "Alcohol use, unspecified with alcohol-induced anxiety disorder", "mental"),
    ("F10.981", "Alcohol use, unspecified with alcohol-induced sexual dysfunction", "mental"),
    ("F10.982", "Alcohol use, unspecified with alcohol-induced sleep disorder", "mental"),
    ("F10.988", "Alcohol use, unspecified with other alcohol-induced disorder", "mental"),
    ("F10.99", "Alcohol use, unspecified with unspecified alcohol-induced disorder", "mental"),
    ("F11.10", "Opioid abuse, uncomplicated", "mental", ["80307"]),
    ("F11.11", "Opioid abuse, in remission", "mental"),
    ("F11.120", "Opioid abuse with intoxication, uncomplicated", "mental", ["80307"]),
    ("F11.121", "Opioid abuse with intoxication delirium", "mental"),
    ("F11.122", "Opioid abuse with intoxication with perceptual disturbance", "mental"),
    ("F11.129", "Opioid abuse with intoxication, unspecified", "mental", ["80307"]),
    ("F11.13", "Opioid abuse with withdrawal", "mental"),
    ("F11.14", "Opioid abuse with opioid-induced mood disorder", "mental"),
    ("F11.150", "Opioid abuse with opioid-induced psychotic disorder with delusions", "mental"),
    ("F11.151", "Opioid abuse with opioid-induced psychotic disorder with hallucinations", "mental"),
    ("F11.159", "Opioid abuse with opioid-induced psychotic disorder, unspecified", "mental"),
    ("F11.181", "Opioid abuse with opioid-induced sexual dysfunction", "mental"),
    ("F11.182", "Opioid abuse with opioid-induced sleep disorder", "mental"),
    ("F11.188", "Opioid abuse with other opioid-induced disorder", "mental"),
    ("F11.19", "Opioid abuse with unspecified opioid-induced disorder", "mental"),
    ("F11.20", "Opioid dependence, uncomplicated", "mental", ["80307"]),
    ("F11.21", "Opioid dependence, in remission", "mental"),
    ("F11.220", "Opioid dependence with intoxication, uncomplicated", "mental", ["80307"]),
    ("F11.221", "Opioid dependence with intoxication delirium", "mental"),
    ("F11.222", "Opioid dependence with intoxication with perceptual disturbance", "mental"),
    ("F11.229", "Opioid dependence with intoxication, unspecified", "mental", ["80307"]),
    ("F11.23", "Opioid dependence with withdrawal", "mental"),
    ("F11.24", "Opioid dependence with opioid-induced mood disorder", "mental"),
    ("F11.250", "Opioid dependence with opioid-induced psychotic disorder with delusions", "mental"),
    ("F11.251", "Opioid dependence with opioid-induced psychotic disorder with hallucinations", "mental"),
    ("F11.259", "Opioid dependence with opioid-induced psychotic disorder, unspecified", "mental"),
    ("F11.281", "Opioid dependence with opioid-induced sexual dysfunction", "mental"),
    ("F11.282", "Opioid dependence with opioid-induced sleep disorder", "mental"),
    ("F11.288", "Opioid dependence with other opioid-induced disorder", "mental"),
    ("F11.29", "Opioid dependence with unspecified opioid-induced disorder", "mental"),
    ("F11.90", "Opioid use, unspecified, uncomplicated", "mental", ["80307"]),
    ("F11.920", "Opioid use, unspecified with intoxication, uncomplicated", "mental", ["80307"]),
    ("F11.921", "Opioid use, unspecified with intoxication delirium", "mental"),
    ("F11.922", "Opioid use, unspecified with intoxication with perceptual disturbance", "mental"),
    ("F11.929", "Opioid use, unspecified with intoxication, unspecified", "mental", ["80307"]),
    ("F11.93", "Opioid use, unspecified with withdrawal", "mental"),
    ("F11.94", "Opioid use, unspecified with opioid-induced mood disorder", "mental"),
    ("F11.950", "Opioid use, unspecified with opioid-induced psychotic disorder with delusions", "mental"),
    ("F11.951", "Opioid use, unspecified with opioid-induced psychotic disorder with hallucinations", "mental"),
    ("F11.959", "Opioid use, unspecified with opioid-induced psychotic disorder, unspecified", "mental"),
    ("F11.981", "Opioid use, unspecified with opioid-induced sexual dysfunction", "mental"),
    ("F11.982", "Opioid use, unspecified with opioid-induced sleep disorder", "mental"),
    ("F11.988", "Opioid use, unspecified with other opioid-induced disorder", "mental"),
    ("F11.99", "Opioid use, unspecified with unspecified opioid-induced disorder", "mental"),
    ("F12.10", "Cannabis abuse, uncomplicated", "mental", ["80305"]),
    ("F12.11", "Cannabis abuse, in remission", "mental"),
    ("F12.120", "Cannabis abuse with intoxication, uncomplicated", "mental", ["80305"]),
    ("F12.121", "Cannabis abuse with intoxication delirium", "mental"),
    ("F12.122", "Cannabis abuse with intoxication with perceptual disturbance", "mental"),
    ("F12.129", "Cannabis abuse with intoxication, unspecified", "mental", ["80305"]),
    ("F12.13", "Cannabis abuse with withdrawal", "mental"),
    ("F12.150", "Cannabis abuse with psychotic disorder with delusions", "mental"),
    ("F12.151", "Cannabis abuse with psychotic disorder with hallucinations", "mental"),
    ("F12.159", "Cannabis abuse with psychotic disorder, unspecified", "mental"),
    ("F12.180", "Cannabis abuse with cannabis-induced anxiety disorder", "mental"),
    ("F12.188", "Cannabis abuse with other cannabis-induced disorder", "mental"),
    ("F12.19", "Cannabis abuse with unspecified cannabis-induced disorder", "mental"),
    ("F12.20", "Cannabis dependence, uncomplicated", "mental", ["80305"]),
    ("F12.21", "Cannabis dependence, in remission", "mental"),
    ("F12.220", "Cannabis dependence with intoxication, uncomplicated", "mental", ["80305"]),
    ("F12.221", "Cannabis dependence with intoxication delirium", "mental"),
    ("F12.222", "Cannabis dependence with intoxication with perceptual disturbance", "mental"),
    ("F12.229", "Cannabis dependence with intoxication, unspecified", "mental", ["80305"]),
    ("F12.23", "Cannabis dependence with withdrawal", "mental"),
    ("F12.250", "Cannabis dependence with psychotic disorder with delusions", "mental"),
    ("F12.251", "Cannabis dependence with psychotic disorder with hallucinations", "mental"),
    ("F12.259", "Cannabis dependence with psychotic disorder, unspecified", "mental"),
    ("F12.280", "Cannabis dependence with cannabis-induced anxiety disorder", "mental"),
    ("F12.288", "Cannabis dependence with other cannabis-induced disorder", "mental"),
    ("F12.29", "Cannabis dependence with unspecified cannabis-induced disorder", "mental"),
    ("F12.90", "Cannabis use, unspecified, uncomplicated", "mental", ["80305"]),
    ("F12.920", "Cannabis use, unspecified with intoxication, uncomplicated", "mental", ["80305"]),
    ("F12.921", "Cannabis use, unspecified with intoxication delirium", "mental"),
    ("F12.922", "Cannabis use, unspecified with intoxication with perceptual disturbance", "mental"),
    ("F12.929", "Cannabis use, unspecified with intoxication, unspecified", "mental", ["80305"]),
    ("F12.93", "Cannabis use, unspecified with withdrawal", "mental"),
    ("F12.950", "Cannabis use, unspecified with psychotic disorder with delusions", "mental"),
    ("F12.951", "Cannabis use, unspecified with psychotic disorder with hallucinations", "mental"),
    ("F12.959", "Cannabis use, unspecified with psychotic disorder, unspecified", "mental"),
    ("F12.980", "Cannabis use, unspecified with anxiety disorder", "mental"),
    ("F12.988", "Cannabis use, unspecified with other cannabis-induced disorder", "mental"),
    ("F12.99", "Cannabis use, unspecified with unspecified cannabis-induced disorder", "mental"),
    ("F13.10", "Sedative, hypnotic or anxiolytic abuse, uncomplicated", "mental", ["80346"]),
    ("F13.11", "Sedative, hypnotic or anxiolytic abuse, in remission", "mental"),
    ("F13.120", "Sedative, hypnotic or anxiolytic abuse with intoxication, uncomplicated", "mental", ["80346"]),
    ("F13.121", "Sedative, hypnotic or anxiolytic abuse with intoxication delirium", "mental"),
    ("F13.129", "Sedative, hypnotic or anxiolytic abuse with intoxication, unspecified", "mental", ["80346"]),
    ("F13.14", "Sedative, hypnotic or anxiolytic abuse with sedative, hypnotic or anxiolytic-induced mood disorder", "mental"),
    ("F13.150", "Sedative, hypnotic or anxiolytic abuse with sedative, hypnotic or anxiolytic-induced psychotic disorder with delusions", "mental"),
    ("F13.151", "Sedative, hypnotic or anxiolytic abuse with sedative, hypnotic or anxiolytic-induced psychotic disorder with hallucinations", "mental"),
    ("F13.159", "Sedative, hypnotic or anxiolytic abuse with sedative, hypnotic or anxiolytic-induced psychotic disorder, unspecified", "mental"),
    ("F13.180", "Sedative, hypnotic or anxiolytic abuse with sedative, hypnotic or anxiolytic-induced anxiety disorder", "mental"),
    ("F13.181", "Sedative, hypnotic or anxiolytic abuse with sedative, hypnotic or anxiolytic-induced sexual dysfunction", "mental"),
    ("F13.182", "Sedative, hypnotic or anxiolytic abuse with sedative, hypnotic or anxiolytic-induced sleep disorder", "mental"),
    ("F13.188", "Sedative, hypnotic or anxiolytic abuse with other sedative, hypnotic or anxiolytic-induced disorder", "mental"),
    ("F13.19", "Sedative, hypnotic or anxiolytic abuse with unspecified sedative, hypnotic or anxiolytic-induced disorder", "mental"),
    ("F13.20", "Sedative, hypnotic or anxiolytic dependence, uncomplicated", "mental", ["80346"]),
    ("F13.21", "Sedative, hypnotic or anxiolytic dependence, in remission", "mental"),
    ("F13.220", "Sedative, hypnotic or anxiolytic dependence with intoxication, uncomplicated", "mental", ["80346"]),
    ("F13.221", "Sedative, hypnotic or anxiolytic dependence with intoxication delirium", "mental"),
    ("F13.229", "Sedative, hypnotic or anxiolytic dependence with intoxication, unspecified", "mental", ["80346"]),
    ("F13.230", "Sedative, hypnotic or anxiolytic dependence with withdrawal, uncomplicated", "mental"),
    ("F13.231", "Sedative, hypnotic or anxiolytic dependence with withdrawal delirium", "mental"),
    ("F13.232", "Sedative, hypnotic or anxiolytic dependence with withdrawal with perceptual disturbance", "mental"),
    ("F13.239", "Sedative, hypnotic or anxiolytic dependence with withdrawal, unspecified", "mental"),
    ("F13.24", "Sedative, hypnotic or anxiolytic dependence with sedative, hypnotic or anxiolytic-induced mood disorder", "mental"),
    ("F13.250", "Sedative, hypnotic or anxiolytic dependence with sedative, hypnotic or anxiolytic-induced psychotic disorder with delusions", "mental"),
    ("F13.251", "Sedative, hypnotic or anxiolytic dependence with sedative, hypnotic or anxiolytic-induced psychotic disorder with hallucinations", "mental"),
    ("F13.259", "Sedative, hypnotic or anxiolytic dependence with sedative, hypnotic or anxiolytic-induced psychotic disorder, unspecified", "mental"),
    ("F13.26", "Sedative, hypnotic or anxiolytic dependence with sedative, hypnotic or anxiolytic-induced persisting amnestic disorder", "mental"),
    ("F13.27", "Sedative, hypnotic or anxiolytic dependence with sedative, hypnotic or anxiolytic-induced persisting dementia", "mental"),
    ("F13.280", "Sedative, hypnotic or anxiolytic dependence with sedative, hypnotic or anxiolytic-induced anxiety disorder", "mental"),
    ("F13.281", "Sedative, hypnotic or anxiolytic dependence with sedative, hypnotic or anxiolytic-induced sexual dysfunction", "mental"),
    ("F13.282", "Sedative, hypnotic or anxiolytic dependence with sedative, hypnotic or anxiolytic-induced sleep disorder", "mental"),
    ("F13.288", "Sedative, hypnotic or anxiolytic dependence with other sedative, hypnotic or anxiolytic-induced disorder", "mental"),
    ("F13.29", "Sedative, hypnotic or anxiolytic dependence with unspecified sedative, hypnotic or anxiolytic-induced disorder", "mental"),
    ("F14.10", "Cocaine abuse, uncomplicated", "mental", ["80353"]),
    ("F14.11", "Cocaine abuse, in remission", "mental"),
    ("F14.120", "Cocaine abuse with intoxication, uncomplicated", "mental", ["80353"]),
    ("F14.121", "Cocaine abuse with intoxication with delirium", "mental"),
    ("F14.122", "Cocaine abuse with intoxication with perceptual disturbance", "mental"),
    ("F14.129", "Cocaine abuse with intoxication, unspecified", "mental", ["80353"]),
    ("F14.13", "Cocaine abuse with withdrawal", "mental"),
    ("F14.14", "Cocaine abuse with cocaine-induced mood disorder", "mental"),
    ("F14.150", "Cocaine abuse with cocaine-induced psychotic disorder with delusions", "mental"),
    ("F14.151", "Cocaine abuse with cocaine-induced psychotic disorder with hallucinations", "mental"),
    ("F14.159", "Cocaine abuse with cocaine-induced psychotic disorder, unspecified", "mental"),
    ("F14.180", "Cocaine abuse with cocaine-induced anxiety disorder", "mental"),
    ("F14.181", "Cocaine abuse with cocaine-induced sexual dysfunction", "mental"),
    ("F14.182", "Cocaine abuse with cocaine-induced sleep disorder", "mental"),
    ("F14.188", "Cocaine abuse with other cocaine-induced disorder", "mental"),
    ("F14.19", "Cocaine abuse with unspecified cocaine-induced disorder", "mental"),
    ("F14.20", "Cocaine dependence, uncomplicated", "mental", ["80353"]),
    ("F14.21", "Cocaine dependence, in remission", "mental"),
    ("F14.220", "Cocaine dependence with intoxication, uncomplicated", "mental", ["80353"]),
    ("F14.221", "Cocaine dependence with intoxication delirium", "mental"),
    ("F14.222", "Cocaine dependence with intoxication with perceptual disturbance", "mental"),
    ("F14.229", "Cocaine dependence with intoxication, unspecified", "mental", ["80353"]),
    ("F14.23", "Cocaine dependence with withdrawal", "mental"),
    ("F14.24", "Cocaine dependence with cocaine-induced mood disorder", "mental"),
    ("F14.250", "Cocaine dependence with cocaine-induced psychotic disorder with delusions", "mental"),
    ("F14.251", "Cocaine dependence with cocaine-induced psychotic disorder with hallucinations", "mental"),
    ("F14.259", "Cocaine dependence with cocaine-induced psychotic disorder, unspecified", "mental"),
    ("F14.280", "Cocaine dependence with cocaine-induced anxiety disorder", "mental"),
    ("F14.281", "Cocaine dependence with cocaine-induced sexual dysfunction", "mental"),
    ("F14.282", "Cocaine dependence with cocaine-induced sleep disorder", "mental"),
    ("F14.288", "Cocaine dependence with other cocaine-induced disorder", "mental"),
    ("F14.29", "Cocaine dependence with unspecified cocaine-induced disorder", "mental"),
    ("F15.10", "Other stimulant abuse, uncomplicated", "mental", ["80324"]),
    ("F15.11", "Other stimulant abuse, in remission", "mental"),
    ("F15.120", "Other stimulant abuse with intoxication, uncomplicated", "mental", ["80324"]),
    ("F15.121", "Other stimulant abuse with intoxication delirium", "mental"),
    ("F15.122", "Other stimulant abuse with intoxication with perceptual disturbance", "mental"),
    ("F15.129", "Other stimulant abuse with intoxication, unspecified", "mental", ["80324"]),
    ("F15.13", "Other stimulant abuse with withdrawal", "mental"),
    ("F15.14", "Other stimulant abuse with stimulant-induced mood disorder", "mental"),
    ("F15.150", "Other stimulant abuse with stimulant-induced psychotic disorder with delusions", "mental"),
    ("F15.151", "Other stimulant abuse with stimulant-induced psychotic disorder with hallucinations", "mental"),
    ("F15.159", "Other stimulant abuse with stimulant-induced psychotic disorder, unspecified", "mental"),
    ("F15.180", "Other stimulant abuse with stimulant-induced anxiety disorder", "mental"),
    ("F15.181", "Other stimulant abuse with stimulant-induced sexual dysfunction", "mental"),
    ("F15.182", "Other stimulant abuse with stimulant-induced sleep disorder", "mental"),
    ("F15.188", "Other stimulant abuse with other stimulant-induced disorder", "mental"),
    ("F15.19", "Other stimulant abuse with unspecified stimulant-induced disorder", "mental"),
    ("F15.20", "Other stimulant dependence, uncomplicated", "mental", ["80324"]),
    ("F15.21", "Other stimulant dependence, in remission", "mental"),
    ("F15.220", "Other stimulant dependence with intoxication, uncomplicated", "mental", ["80324"]),
    ("F15.221", "Other stimulant dependence with intoxication delirium", "mental"),
    ("F15.222", "Other stimulant dependence with intoxication with perceptual disturbance", "mental"),
    ("F15.229", "Other stimulant dependence with intoxication, unspecified", "mental", ["80324"]),
    ("F15.23", "Other stimulant dependence with withdrawal", "mental"),
    ("F15.24", "Other stimulant dependence with stimulant-induced mood disorder", "mental"),
    ("F15.250", "Other stimulant dependence with stimulant-induced psychotic disorder with delusions", "mental"),
    ("F15.251", "Other stimulant dependence with stimulant-induced psychotic disorder with hallucinations", "mental"),
    ("F15.259", "Other stimulant dependence with stimulant-induced psychotic disorder, unspecified", "mental"),
    ("F15.280", "Other stimulant dependence with stimulant-induced anxiety disorder", "mental"),
    ("F15.281", "Other stimulant dependence with stimulant-induced sexual dysfunction", "mental"),
    ("F15.282", "Other stimulant dependence with stimulant-induced sleep disorder", "mental"),
    ("F15.288", "Other stimulant dependence with other stimulant-induced disorder", "mental"),
    ("F15.29", "Other stimulant dependence with unspecified stimulant-induced disorder", "mental"),
    # Mood disorders (F30-F39)
    ("F30.10", "Manic episode without psychotic symptoms, unspecified", "mental"),
    ("F30.11", "Manic episode without psychotic symptoms, mild", "mental"),
    ("F30.12", "Manic episode without psychotic symptoms, moderate", "mental"),
    ("F30.13", "Manic episode without psychotic symptoms, severe", "mental"),
    ("F30.2", "Manic episode, severe with psychotic symptoms", "mental"),
    ("F30.3", "Manic episode in partial remission", "mental"),
    ("F30.4", "Manic episode in full remission", "mental"),
    ("F30.8", "Other manic episodes", "mental"),
    ("F30.9", "Manic episode, unspecified", "mental"),
    ("F31.0", "Bipolar disorder, current episode hypomanic", "mental"),
    ("F31.10", "Bipolar disorder, current episode manic without psychotic features, unspecified", "mental"),
    ("F31.11", "Bipolar disorder, current episode manic without psychotic features, mild", "mental"),
    ("F31.12", "Bipolar disorder, current episode manic without psychotic features, moderate", "mental"),
    ("F31.13", "Bipolar disorder, current episode manic without psychotic features, severe", "mental"),
    ("F31.2", "Bipolar disorder, current episode manic severe with psychotic features", "mental"),
    ("F31.30", "Bipolar disorder, current episode depressed, mild or moderate severity, unspecified", "mental"),
    ("F31.31", "Bipolar disorder, current episode depressed, mild", "mental"),
    ("F31.32", "Bipolar disorder, current episode depressed, moderate", "mental"),
    ("F31.4", "Bipolar disorder, current episode depressed, severe, without psychotic features", "mental"),
    ("F31.5", "Bipolar disorder, current episode depressed, severe, with psychotic features", "mental"),
    ("F31.60", "Bipolar disorder, current episode mixed, unspecified", "mental"),
    ("F31.61", "Bipolar disorder, current episode mixed, mild", "mental"),
    ("F31.62", "Bipolar disorder, current episode mixed, moderate", "mental"),
    ("F31.63", "Bipolar disorder, current episode mixed, severe, without psychotic features", "mental"),
    ("F31.64", "Bipolar disorder, current episode mixed, severe, with psychotic features", "mental"),
    ("F31.70", "Bipolar disorder, currently in remission, most recent episode unspecified", "mental"),
    ("F31.71", "Bipolar disorder, in partial remission, most recent episode hypomanic", "mental"),
    ("F31.72", "Bipolar disorder, in full remission, most recent episode hypomanic", "mental"),
    ("F31.73", "Bipolar disorder, in partial remission, most recent episode manic", "mental"),
    ("F31.74", "Bipolar disorder, in full remission, most recent episode manic", "mental"),
    ("F31.75", "Bipolar disorder, in partial remission, most recent episode depressed", "mental"),
    ("F31.76", "Bipolar disorder, in full remission, most recent episode depressed", "mental"),
    ("F31.77", "Bipolar disorder, in partial remission, most recent episode mixed", "mental"),
    ("F31.78", "Bipolar disorder, in full remission, most recent episode mixed", "mental"),
    ("F31.81", "Bipolar II disorder", "mental"),
    ("F31.89", "Other bipolar disorder", "mental"),
    ("F31.9", "Bipolar disorder, unspecified", "mental"),
    ("F32.0", "Major depressive disorder, single episode, mild", "mental"),
    ("F32.1", "Major depressive disorder, single episode, moderate", "mental"),
    ("F32.2", "Major depressive disorder, single episode, severe without psychotic features", "mental"),
    ("F32.3", "Major depressive disorder, single episode, severe with psychotic features", "mental"),
    ("F32.4", "Major depressive disorder, single episode, in partial remission", "mental"),
    ("F32.5", "Major depressive disorder, single episode, in full remission", "mental"),
    ("F32.8", "Other depressive episodes", "mental"),
    ("F32.9", "Major depressive disorder, single episode, unspecified", "mental"),
    ("F33.0", "Major depressive disorder, recurrent, mild", "mental"),
    ("F33.1", "Major depressive disorder, recurrent, moderate", "mental"),
    ("F33.2", "Major depressive disorder, recurrent severe without psychotic features", "mental"),
    ("F33.3", "Major depressive disorder, recurrent, severe with psychotic symptoms", "mental"),
    ("F33.40", "Major depressive disorder, recurrent, in remission, unspecified", "mental"),
    ("F33.41", "Major depressive disorder, recurrent, in partial remission", "mental"),
    ("F33.42", "Major depressive disorder, recurrent, in full remission", "mental"),
    ("F33.8", "Other recurrent depressive disorders", "mental"),
    ("F33.9", "Major depressive disorder, recurrent, unspecified", "mental"),
    ("F34.0", "Cyclothymic disorder", "mental"),
    ("F34.1", "Dysthymic disorder", "mental"),
    ("F34.8", "Other persistent mood disorders", "mental"),
    ("F34.9", "Persistent mood disorder, unspecified", "mental"),
    ("F39", "Unspecified mood disorder", "mental"),
]
for item in mental_behavioral:
    if len(item) == 3:
        code, desc, system = item
        cpt = None
    else:
        code, desc, system, cpt = item
    new_codes[code] = make_icd10(code, desc, system, cpt)

# ============================================================
# SAVE TO DATABASE
# ============================================================

try:
    with open(DB_PATH, 'r') as f:
        db = json.load(f)
    
    before = len(db)
    added = 0
    for code, entry in new_codes.items():
        if code not in db:
            db[code] = entry
            added += 1
    
    with open(DB_PATH, 'w') as f:
        json.dump(db, f, indent=2)
    
    # Verify
    with open(DB_PATH, 'r') as f:
        verify = json.load(f)
    
    print(f"ICD-10 Part 2: Before={before}, Added={added}, After={len(verify)}")
    print(f"JSON valid: {len(verify) > 0}")
    
except Exception as e:
    print(f"ERROR: {e}")
    import traceback
    traceback.print_exc()