#!/usr/bin/env python3
"""Expand CPT database with 2,000+ new codes across missing specialties."""
import json

with open('cpt_database.json', 'r') as f:
    db = json.load(f)

initial = len(db)
print(f"Starting CPT count: {initial}")

def add(code, desc, cat, subcat, spec, wrvu, gp=10, bilateral=False, addon=False, 
        cosurg=False, asst=False, tier=3, family="unclassified", inclusive=None,
        never_primary=None, modifiers=None, estimated=True):
    if code in db:
        return
    db[code] = {
        "code": code,
        "description": desc,
        "category": cat,
        "subcategory": subcat,
        "specialty": spec,
        "work_rvu": wrvu,
        "global_period_days": gp,
        "bilateral_eligible": bilateral,
        "addon_code": addon,
        "cosurgeon_eligible": cosurg,
        "assistant_allowed": asst,
        "hierarchy_tier": tier,
        "code_family": family,
        "inclusive_of": inclusive or [],
        "never_primary_with": never_primary or [],
        "typical_modifiers": modifiers or [],
        "estimated": estimated
    }

# ============================================================
# FRACTURE CODES - Clavicle
# ============================================================
add("23500", "Closed treatment of clavicular fracture without manipulation", "Surgery", "Musculoskeletal", "orthopedics", 3.62, 90)
add("23505", "Closed treatment of clavicular fracture with manipulation", "Surgery", "Musculoskeletal", "orthopedics", 5.27, 90)
add("23515", "Open treatment of clavicular fracture with internal fixation", "Surgery", "Musculoskeletal", "orthopedics", 11.63, 90, asst=True)
add("23520", "Closed treatment of sternoclavicular dislocation without manipulation", "Surgery", "Musculoskeletal", "orthopedics", 3.50, 90)
add("23525", "Closed treatment of sternoclavicular dislocation with manipulation", "Surgery", "Musculoskeletal", "orthopedics", 5.00, 90)
add("23530", "Open treatment of sternoclavicular dislocation", "Surgery", "Musculoskeletal", "orthopedics", 10.50, 90, asst=True)
add("23532", "Open treatment of sternoclavicular dislocation with fascial graft", "Surgery", "Musculoskeletal", "orthopedics", 12.00, 90, asst=True)
add("23540", "Closed treatment of acromioclavicular dislocation without manipulation", "Surgery", "Musculoskeletal", "orthopedics", 3.22, 90)
add("23545", "Closed treatment of acromioclavicular dislocation with manipulation", "Surgery", "Musculoskeletal", "orthopedics", 4.80, 90)
add("23550", "Open treatment of acromioclavicular dislocation", "Surgery", "Musculoskeletal", "orthopedics", 10.08, 90, asst=True)

# Humerus shaft fractures
add("24500", "Closed treatment of humeral shaft fracture without manipulation", "Surgery", "Musculoskeletal", "orthopedics", 3.98, 90)
add("24505", "Closed treatment of humeral shaft fracture with manipulation", "Surgery", "Musculoskeletal", "orthopedics", 6.45, 90)
add("24515", "Open treatment of humeral shaft fracture with plate/screws", "Surgery", "Musculoskeletal", "orthopedics", 14.88, 90, asst=True)
add("24516", "Open treatment of humeral shaft fracture with intramedullary implant", "Surgery", "Musculoskeletal", "orthopedics", 13.50, 90, asst=True)
add("24530", "Closed treatment of supracondylar fracture without manipulation", "Surgery", "Musculoskeletal", "orthopedics", 4.50, 90)
add("24535", "Closed treatment of supracondylar fracture with manipulation", "Surgery", "Musculoskeletal", "orthopedics", 7.20, 90)
add("24538", "Percutaneous skeletal fixation of supracondylar fracture", "Surgery", "Musculoskeletal", "orthopedics", 10.50, 90)
add("24545", "Open treatment of supracondylar or transcondylar humeral fracture", "Surgery", "Musculoskeletal", "orthopedics", 15.25, 90, asst=True)
add("24546", "Open treatment of supracondylar or transcondylar humeral fracture with ICBG", "Surgery", "Musculoskeletal", "orthopedics", 17.00, 90, asst=True)
add("24560", "Closed treatment of humeral epicondylar fracture without manipulation", "Surgery", "Musculoskeletal", "orthopedics", 3.50, 90)
add("24565", "Closed treatment of humeral epicondylar fracture with manipulation", "Surgery", "Musculoskeletal", "orthopedics", 5.50, 90)
add("24566", "Percutaneous skeletal fixation of humeral epicondylar fracture", "Surgery", "Musculoskeletal", "orthopedics", 8.50, 90)
add("24575", "Open treatment of humeral epicondylar fracture with internal fixation", "Surgery", "Musculoskeletal", "orthopedics", 12.30, 90, asst=True)
add("24576", "Closed treatment of humeral condylar fracture without manipulation", "Surgery", "Musculoskeletal", "orthopedics", 4.00, 90)
add("24577", "Closed treatment of humeral condylar fracture with manipulation", "Surgery", "Musculoskeletal", "orthopedics", 6.80, 90)
add("24579", "Open treatment of humeral condylar fracture with internal fixation", "Surgery", "Musculoskeletal", "orthopedics", 14.50, 90, asst=True)

# Both bones forearm
add("25500", "Closed treatment of radial shaft fracture without manipulation", "Surgery", "Musculoskeletal", "orthopedics", 3.52, 90)
add("25505", "Closed treatment of radial shaft fracture with manipulation", "Surgery", "Musculoskeletal", "orthopedics", 5.88, 90)
add("25515", "Open treatment of radial shaft fracture with internal fixation", "Surgery", "Musculoskeletal", "orthopedics", 12.47, 90, asst=True)
add("25520", "Closed treatment of radial shaft fracture with insertion of intramedullary implant", "Surgery", "Musculoskeletal", "orthopedics", 8.50, 90)
add("25525", "Open treatment of radial shaft fracture with plate/screws", "Surgery", "Musculoskeletal", "orthopedics", 13.00, 90, asst=True)
add("25526", "Open treatment of radial shaft fracture with internal fixation of 2 fragments", "Surgery", "Musculoskeletal", "orthopedics", 14.50, 90, asst=True)
add("25530", "Closed treatment of ulnar shaft fracture without manipulation", "Surgery", "Musculoskeletal", "orthopedics", 3.50, 90)
add("25535", "Closed treatment of ulnar shaft fracture with manipulation", "Surgery", "Musculoskeletal", "orthopedics", 5.70, 90)
add("25545", "Open treatment of ulnar shaft fracture with plate/screws", "Surgery", "Musculoskeletal", "orthopedics", 12.00, 90, asst=True)
add("25560", "Closed treatment of radial and ulnar shaft fractures without manipulation", "Surgery", "Musculoskeletal", "orthopedics", 4.80, 90)
add("25565", "Closed treatment of radial and ulnar shaft fractures with manipulation", "Surgery", "Musculoskeletal", "orthopedics", 7.50, 90)
add("25574", "Open treatment of radial and ulnar shaft fractures with internal fixation of radius", "Surgery", "Musculoskeletal", "orthopedics", 14.00, 90, asst=True)
add("25575", "Open treatment of radial and ulnar shaft fractures with internal fixation of both", "Surgery", "Musculoskeletal", "orthopedics", 16.50, 90, asst=True)

# Phalanges
add("26720", "Closed treatment of phalangeal shaft fracture without manipulation", "Surgery", "Musculoskeletal", "orthopedics", 2.10, 90)
add("26725", "Closed treatment of phalangeal shaft fracture with manipulation", "Surgery", "Musculoskeletal", "orthopedics", 3.50, 90)
add("26727", "Percutaneous skeletal fixation of unstable phalangeal shaft fracture", "Surgery", "Musculoskeletal", "orthopedics", 5.80, 90)
add("26735", "Open treatment of phalangeal shaft fracture with internal fixation", "Surgery", "Musculoskeletal", "orthopedics", 7.45, 90)
add("26740", "Closed treatment of articular fracture of finger without manipulation", "Surgery", "Musculoskeletal", "orthopedics", 2.30, 90)
add("26742", "Closed treatment of articular fracture of finger with manipulation", "Surgery", "Musculoskeletal", "orthopedics", 3.80, 90)
add("26746", "Open treatment of articular fracture of finger with internal fixation", "Surgery", "Musculoskeletal", "orthopedics", 8.00, 90)
add("26750", "Closed treatment of distal phalangeal fracture without manipulation", "Surgery", "Musculoskeletal", "orthopedics", 1.80, 90)
add("26755", "Closed treatment of distal phalangeal fracture with manipulation", "Surgery", "Musculoskeletal", "orthopedics", 2.90, 90)
add("26756", "Percutaneous skeletal fixation of distal phalangeal fracture", "Surgery", "Musculoskeletal", "orthopedics", 4.50, 90)
add("26765", "Open treatment of distal phalangeal fracture with internal fixation", "Surgery", "Musculoskeletal", "orthopedics", 6.50, 90)
add("26770", "Closed treatment of interphalangeal joint dislocation without anesthesia", "Surgery", "Musculoskeletal", "orthopedics", 2.50, 90)
add("26775", "Closed treatment of interphalangeal joint dislocation with manipulation", "Surgery", "Musculoskeletal", "orthopedics", 3.70, 90)
add("26785", "Open treatment of interphalangeal joint dislocation", "Surgery", "Musculoskeletal", "orthopedics", 7.20, 90)

# Pelvis fractures
add("27193", "Closed treatment of pelvic ring fracture without manipulation", "Surgery", "Musculoskeletal", "orthopedics", 4.00, 90)
add("27194", "Closed treatment of pelvic ring fracture with manipulation", "Surgery", "Musculoskeletal", "orthopedics", 7.50, 90)
add("27197", "Closed treatment of posterior pelvic ring fracture", "Surgery", "Musculoskeletal", "orthopedics", 6.00, 90)
add("27198", "Closed treatment of posterior pelvic ring disruption with manipulation", "Surgery", "Musculoskeletal", "orthopedics", 9.00, 90)
add("27200", "Closed treatment of coccyx fracture", "Surgery", "Musculoskeletal", "orthopedics", 2.10, 90)
add("27202", "Open treatment of coccyx fracture", "Surgery", "Musculoskeletal", "orthopedics", 5.50, 90)
add("27215", "Open treatment of iliac spine fracture", "Surgery", "Musculoskeletal", "orthopedics", 12.00, 90, asst=True)
add("27216", "Percutaneous skeletal fixation of posterior pelvic ring", "Surgery", "Musculoskeletal", "orthopedics", 13.50, 90, asst=True)
add("27217", "Open treatment of anterior pelvic ring fracture with internal fixation", "Surgery", "Musculoskeletal", "orthopedics", 14.80, 90, asst=True)
add("27218", "Open treatment of posterior pelvic ring fracture with internal fixation", "Surgery", "Musculoskeletal", "orthopedics", 18.50, 90, asst=True)
add("27220", "Closed treatment of acetabulum fracture without manipulation", "Surgery", "Musculoskeletal", "orthopedics", 4.50, 90)

# Patella
add("27520", "Closed treatment of patellar fracture without manipulation", "Surgery", "Musculoskeletal", "orthopedics", 3.30, 90)
add("27524", "Open treatment of patellar fracture with internal fixation", "Surgery", "Musculoskeletal", "orthopedics", 10.50, 90, asst=True)
add("27530", "Closed treatment of tibial fracture proximal without manipulation", "Surgery", "Musculoskeletal", "orthopedics", 4.00, 90)
add("27532", "Closed treatment of tibial fracture proximal with manipulation", "Surgery", "Musculoskeletal", "orthopedics", 6.50, 90)
add("27535", "Open treatment of tibial fracture proximal with internal fixation", "Surgery", "Musculoskeletal", "orthopedics", 14.00, 90, asst=True)
add("27536", "Open treatment of tibial fracture proximal bicondylar with internal fixation", "Surgery", "Musculoskeletal", "orthopedics", 18.00, 90, asst=True)
add("27538", "Closed treatment of intercondylar spine fracture of tibia", "Surgery", "Musculoskeletal", "orthopedics", 5.00, 90)
add("27540", "Open treatment of intercondylar spine fracture of tibia", "Surgery", "Musculoskeletal", "orthopedics", 10.00, 90, asst=True)
add("27550", "Closed treatment of knee dislocation without anesthesia", "Surgery", "Musculoskeletal", "orthopedics", 4.50, 90)
add("27552", "Closed treatment of knee dislocation with anesthesia", "Surgery", "Musculoskeletal", "orthopedics", 6.50, 90)
add("27556", "Open treatment of knee dislocation", "Surgery", "Musculoskeletal", "orthopedics", 15.00, 90, asst=True)
add("27560", "Closed treatment of patellar dislocation without anesthesia", "Surgery", "Musculoskeletal", "orthopedics", 2.80, 90)
add("27562", "Closed treatment of patellar dislocation with anesthesia", "Surgery", "Musculoskeletal", "orthopedics", 4.00, 90)
add("27566", "Open treatment of patellar dislocation", "Surgery", "Musculoskeletal", "orthopedics", 9.50, 90, asst=True)

# Ankle malleolus
add("27760", "Closed treatment of medial malleolus fracture without manipulation", "Surgery", "Musculoskeletal", "orthopedics", 3.20, 90)
add("27762", "Closed treatment of medial malleolus fracture with manipulation", "Surgery", "Musculoskeletal", "orthopedics", 5.40, 90)
add("27766", "Open treatment of medial malleolus fracture with internal fixation", "Surgery", "Musculoskeletal", "orthopedics", 10.60, 90, asst=True)
add("27780", "Closed treatment of proximal fibula fracture without manipulation", "Surgery", "Musculoskeletal", "orthopedics", 2.70, 90)
add("27781", "Closed treatment of proximal fibula fracture with manipulation", "Surgery", "Musculoskeletal", "orthopedics", 4.50, 90)
add("27784", "Open treatment of proximal fibula fracture with internal fixation", "Surgery", "Musculoskeletal", "orthopedics", 9.00, 90, asst=True)
add("27786", "Closed treatment of distal fibula fracture without manipulation", "Surgery", "Musculoskeletal", "orthopedics", 2.90, 90)
add("27788", "Closed treatment of distal fibula fracture with manipulation", "Surgery", "Musculoskeletal", "orthopedics", 5.00, 90)
add("27792", "Open treatment of distal fibula fracture with internal fixation", "Surgery", "Musculoskeletal", "orthopedics", 10.30, 90, asst=True)
add("27808", "Closed treatment of bimalleolar ankle fracture without manipulation", "Surgery", "Musculoskeletal", "orthopedics", 4.50, 90)
add("27810", "Closed treatment of bimalleolar ankle fracture with manipulation", "Surgery", "Musculoskeletal", "orthopedics", 6.80, 90)
add("27814", "Open treatment of bimalleolar ankle fracture with internal fixation", "Surgery", "Musculoskeletal", "orthopedics", 14.00, 90, asst=True)
add("27816", "Closed treatment of trimalleolar ankle fracture without manipulation", "Surgery", "Musculoskeletal", "orthopedics", 5.50, 90)
add("27818", "Closed treatment of trimalleolar ankle fracture with manipulation", "Surgery", "Musculoskeletal", "orthopedics", 7.50, 90)
add("27822", "Open treatment of trimalleolar ankle fracture with internal fixation medial and lateral", "Surgery", "Musculoskeletal", "orthopedics", 16.50, 90, asst=True)
add("27823", "Open treatment of trimalleolar ankle fracture with internal fixation including posterior lip", "Surgery", "Musculoskeletal", "orthopedics", 18.00, 90, asst=True)
add("27824", "Closed treatment of distal tibiofibular joint dislocation without manipulation", "Surgery", "Musculoskeletal", "orthopedics", 4.00, 90)
add("27825", "Closed treatment of distal tibiofibular joint dislocation with manipulation", "Surgery", "Musculoskeletal", "orthopedics", 6.00, 90)
add("27826", "Open treatment of distal tibiofibular joint dislocation", "Surgery", "Musculoskeletal", "orthopedics", 11.50, 90, asst=True)
add("27827", "Open treatment of distal tibiofibular joint dislocation with fixation", "Surgery", "Musculoskeletal", "orthopedics", 13.00, 90, asst=True)
add("27828", "Open treatment of distal tibiofibular joint dislocation with internal fixation and repair", "Surgery", "Musculoskeletal", "orthopedics", 15.00, 90, asst=True)

# Metatarsal fractures
add("28470", "Closed treatment of metatarsal fracture without manipulation", "Surgery", "Musculoskeletal", "orthopedics", 2.10, 90)
add("28475", "Closed treatment of metatarsal fracture with manipulation", "Surgery", "Musculoskeletal", "orthopedics", 3.50, 90)
add("28476", "Percutaneous skeletal fixation of metatarsal fracture", "Surgery", "Musculoskeletal", "orthopedics", 5.80, 90)
add("28485", "Open treatment of metatarsal fracture with internal fixation", "Surgery", "Musculoskeletal", "orthopedics", 8.50, 90)

# Calcaneus fractures
add("28400", "Closed treatment of calcaneal fracture without manipulation", "Surgery", "Musculoskeletal", "orthopedics", 3.00, 90)
add("28405", "Closed treatment of calcaneal fracture with manipulation", "Surgery", "Musculoskeletal", "orthopedics", 5.50, 90)
add("28406", "Percutaneous skeletal fixation of calcaneal fracture", "Surgery", "Musculoskeletal", "orthopedics", 9.00, 90)
add("28415", "Open treatment of calcaneal fracture with internal fixation", "Surgery", "Musculoskeletal", "orthopedics", 16.50, 90, asst=True)
add("28420", "Open treatment of calcaneal fracture with bone graft", "Surgery", "Musculoskeletal", "orthopedics", 18.00, 90, asst=True)

# Talus fractures
add("28430", "Closed treatment of talus fracture without manipulation", "Surgery", "Musculoskeletal", "orthopedics", 3.20, 90)
add("28435", "Closed treatment of talus fracture with manipulation", "Surgery", "Musculoskeletal", "orthopedics", 5.80, 90)
add("28445", "Open treatment of talus fracture with internal fixation", "Surgery", "Musculoskeletal", "orthopedics", 15.00, 90, asst=True)

# Toe phalanx fractures
add("28490", "Closed treatment of fracture great toe phalanx without manipulation", "Surgery", "Musculoskeletal", "orthopedics", 1.50, 90)
add("28495", "Closed treatment of fracture great toe phalanx with manipulation", "Surgery", "Musculoskeletal", "orthopedics", 2.70, 90)
add("28496", "Percutaneous skeletal fixation of fracture great toe phalanx", "Surgery", "Musculoskeletal", "orthopedics", 4.50, 90)
add("28505", "Open treatment of fracture great toe phalanx with internal fixation", "Surgery", "Musculoskeletal", "orthopedics", 6.50, 90)
add("28510", "Closed treatment of fracture phalanx other than great toe without manipulation", "Surgery", "Musculoskeletal", "orthopedics", 1.20, 90)
add("28515", "Closed treatment of fracture phalanx other than great toe with manipulation", "Surgery", "Musculoskeletal", "orthopedics", 2.30, 90)
add("28525", "Open treatment of fracture phalanx other than great toe", "Surgery", "Musculoskeletal", "orthopedics", 5.50, 90)

# ============================================================
# CASTING CODES 29000-29280
# ============================================================
add("29000", "Application of hip spica body cast bilateral", "Surgery", "Musculoskeletal", "orthopedics", 4.50, 0)
add("29010", "Application of Risser jacket body cast", "Surgery", "Musculoskeletal", "orthopedics", 4.00, 0)
add("29015", "Application of hip spica body cast one leg", "Surgery", "Musculoskeletal", "orthopedics", 3.80, 0)
add("29020", "Application of turnbuckle jacket body cast", "Surgery", "Musculoskeletal", "orthopedics", 4.20, 0)
add("29025", "Application of body cast shoulder to hips", "Surgery", "Musculoskeletal", "orthopedics", 3.50, 0)
add("29035", "Application of body cast shoulder to hips with head", "Surgery", "Musculoskeletal", "orthopedics", 4.50, 0)
add("29040", "Application of body cast shoulder to hips with one thigh", "Surgery", "Musculoskeletal", "orthopedics", 4.00, 0)
add("29044", "Application of body cast with 1 thigh and head Minerva type", "Surgery", "Musculoskeletal", "orthopedics", 5.00, 0)
add("29046", "Application of body cast with both thighs", "Surgery", "Musculoskeletal", "orthopedics", 5.20, 0)
add("29049", "Application of figure-of-eight cast", "Surgery", "Musculoskeletal", "orthopedics", 1.50, 0)
add("29055", "Application of shoulder spica cast", "Surgery", "Musculoskeletal", "orthopedics", 3.80, 0)
add("29058", "Application of plaster Velpeau", "Surgery", "Musculoskeletal", "orthopedics", 2.50, 0)
add("29065", "Application of long arm cast shoulder to hand", "Surgery", "Musculoskeletal", "orthopedics", 2.50, 0)
add("29075", "Application of short arm cast forearm to hand", "Surgery", "Musculoskeletal", "orthopedics", 1.80, 0)
add("29085", "Application of hand and lower forearm cast", "Surgery", "Musculoskeletal", "orthopedics", 1.50, 0)
add("29086", "Application of finger cast", "Surgery", "Musculoskeletal", "orthopedics", 1.00, 0)
add("29105", "Application of long arm splint shoulder to hand", "Surgery", "Musculoskeletal", "orthopedics", 1.80, 0)
add("29125", "Application of short arm splint forearm to hand static", "Surgery", "Musculoskeletal", "orthopedics", 1.20, 0)
add("29126", "Application of short arm splint forearm to hand dynamic", "Surgery", "Musculoskeletal", "orthopedics", 1.40, 0)
add("29130", "Application of finger splint static", "Surgery", "Musculoskeletal", "orthopedics", 0.70, 0)
add("29131", "Application of finger splint dynamic", "Surgery", "Musculoskeletal", "orthopedics", 0.80, 0)
add("29200", "Strapping of chest", "Surgery", "Musculoskeletal", "orthopedics", 1.00, 0)
add("29240", "Strapping of shoulder", "Surgery", "Musculoskeletal", "orthopedics", 1.20, 0)
add("29260", "Strapping of elbow or wrist", "Surgery", "Musculoskeletal", "orthopedics", 1.00, 0)
add("29280", "Strapping of hand or finger", "Surgery", "Musculoskeletal", "orthopedics", 0.80, 0)

# Lower extremity casts
add("29305", "Application of hip spica cast one leg", "Surgery", "Musculoskeletal", "orthopedics", 4.50, 0)
add("29325", "Application of hip spica cast one and one-half", "Surgery", "Musculoskeletal", "orthopedics", 5.00, 0)
add("29345", "Application of long leg cast thigh to toes", "Surgery", "Musculoskeletal", "orthopedics", 2.80, 0)
add("29355", "Application of long leg cast walker or ambulatory type", "Surgery", "Musculoskeletal", "orthopedics", 2.50, 0)
add("29358", "Application of long leg cast brace", "Surgery", "Musculoskeletal", "orthopedics", 2.80, 0)
add("29365", "Application of cylinder cast thigh to ankle", "Surgery", "Musculoskeletal", "orthopedics", 2.30, 0)
add("29405", "Application of short leg cast below knee to toes", "Surgery", "Musculoskeletal", "orthopedics", 1.80, 0)
add("29425", "Application of short leg cast walking", "Surgery", "Musculoskeletal", "orthopedics", 1.60, 0)
add("29435", "Application of patellar tendon bearing cast", "Surgery", "Musculoskeletal", "orthopedics", 2.20, 0)
add("29440", "Adding walker to previously applied cast", "Surgery", "Musculoskeletal", "orthopedics", 0.60, 0)
add("29445", "Application of rigid total contact leg cast", "Surgery", "Musculoskeletal", "orthopedics", 2.50, 0)
add("29450", "Application of clubfoot cast with manipulation", "Surgery", "Musculoskeletal", "orthopedics", 3.00, 0)
add("29505", "Application of long leg splint thigh to ankle or toes", "Surgery", "Musculoskeletal", "orthopedics", 1.80, 0)
add("29515", "Application of short leg splint calf to foot", "Surgery", "Musculoskeletal", "orthopedics", 1.20, 0)

# Cast removal/repair
add("29700", "Removal or bivalving of gauntlet boot or body cast", "Surgery", "Musculoskeletal", "orthopedics", 0.80, 0)
add("29705", "Removal or bivalving of full arm or full leg cast", "Surgery", "Musculoskeletal", "orthopedics", 0.70, 0)
add("29710", "Removal or bivalving of shoulder or hip spica body cast", "Surgery", "Musculoskeletal", "orthopedics", 1.00, 0)
add("29720", "Repair of spica body cast or jacket", "Surgery", "Musculoskeletal", "orthopedics", 0.80, 0)
add("29730", "Windowing of cast", "Surgery", "Musculoskeletal", "orthopedics", 0.50, 0)
add("29740", "Wedging of cast", "Surgery", "Musculoskeletal", "orthopedics", 1.00, 0)
add("29750", "Wedging of clubfoot cast", "Surgery", "Musculoskeletal", "orthopedics", 1.20, 0)

# ============================================================
# STRAPPING CODES 29500-29590
# ============================================================
add("29500", "Strapping of hip", "Surgery", "Musculoskeletal", "orthopedics", 1.20, 0)
add("29505", "Strapping of knee", "Surgery", "Musculoskeletal", "orthopedics", 1.00, 0)
add("29515", "Strapping of ankle and/or foot", "Surgery", "Musculoskeletal", "orthopedics", 1.00, 0)
add("29520", "Strapping of hip", "Surgery", "Musculoskeletal", "orthopedics", 1.20, 0)
add("29530", "Strapping of knee", "Surgery", "Musculoskeletal", "orthopedics", 1.00, 0)
add("29540", "Strapping of ankle", "Surgery", "Musculoskeletal", "orthopedics", 0.90, 0)
add("29550", "Strapping of toes", "Surgery", "Musculoskeletal", "orthopedics", 0.70, 0)
add("29580", "Application of Unna boot", "Surgery", "Musculoskeletal", "orthopedics", 1.20, 0)
add("29581", "Application of multi-layer compression system below knee", "Surgery", "Musculoskeletal", "orthopedics", 1.00, 0)
add("29584", "Application of multi-layer compression system upper arm and forearm", "Surgery", "Musculoskeletal", "orthopedics", 1.00, 0)

# ============================================================
# ARTHROSCOPY - Shoulder
# ============================================================
add("29805", "Arthroscopy shoulder diagnostic", "Surgery", "Musculoskeletal", "orthopedics", 6.50, 90)
add("29806", "Arthroscopy shoulder surgical capsulorrhaphy", "Surgery", "Musculoskeletal", "orthopedics", 15.00, 90, asst=True)
add("29807", "Arthroscopy shoulder surgical repair of SLAP lesion", "Surgery", "Musculoskeletal", "orthopedics", 13.50, 90, asst=True)
add("29819", "Arthroscopy shoulder surgical with removal of loose body", "Surgery", "Musculoskeletal", "orthopedics", 8.50, 90)
add("29820", "Arthroscopy shoulder surgical synovectomy partial", "Surgery", "Musculoskeletal", "orthopedics", 7.80, 90)
add("29821", "Arthroscopy shoulder surgical synovectomy complete", "Surgery", "Musculoskeletal", "orthopedics", 9.00, 90)
add("29822", "Arthroscopy shoulder surgical debridement limited", "Surgery", "Musculoskeletal", "orthopedics", 8.20, 90)
add("29823", "Arthroscopy shoulder surgical debridement extensive", "Surgery", "Musculoskeletal", "orthopedics", 9.50, 90)
add("29824", "Arthroscopy shoulder surgical distal claviculectomy", "Surgery", "Musculoskeletal", "orthopedics", 10.00, 90)
add("29825", "Arthroscopy shoulder surgical lysis of adhesions", "Surgery", "Musculoskeletal", "orthopedics", 8.80, 90)
add("29826", "Arthroscopy shoulder surgical decompression of subacromial space", "Surgery", "Musculoskeletal", "orthopedics", 9.50, 90)
add("29827", "Arthroscopy shoulder surgical rotator cuff repair", "Surgery", "Musculoskeletal", "orthopedics", 16.00, 90, asst=True)
add("29828", "Arthroscopy shoulder surgical biceps tenodesis", "Surgery", "Musculoskeletal", "orthopedics", 10.50, 90)

# Arthroscopy - Elbow
add("29830", "Arthroscopy elbow diagnostic", "Surgery", "Musculoskeletal", "orthopedics", 5.50, 90)
add("29834", "Arthroscopy elbow surgical with removal of loose body", "Surgery", "Musculoskeletal", "orthopedics", 7.50, 90)
add("29835", "Arthroscopy elbow surgical synovectomy partial", "Surgery", "Musculoskeletal", "orthopedics", 7.00, 90)
add("29836", "Arthroscopy elbow surgical synovectomy complete", "Surgery", "Musculoskeletal", "orthopedics", 8.50, 90)
add("29837", "Arthroscopy elbow surgical debridement limited", "Surgery", "Musculoskeletal", "orthopedics", 7.20, 90)
add("29838", "Arthroscopy elbow surgical debridement extensive", "Surgery", "Musculoskeletal", "orthopedics", 8.80, 90)

# Arthroscopy - Wrist
add("29840", "Arthroscopy wrist diagnostic", "Surgery", "Musculoskeletal", "orthopedics", 5.00, 90)
add("29843", "Arthroscopy wrist surgical for infection", "Surgery", "Musculoskeletal", "orthopedics", 7.50, 90)
add("29844", "Arthroscopy wrist surgical synovectomy partial", "Surgery", "Musculoskeletal", "orthopedics", 6.80, 90)
add("29845", "Arthroscopy wrist surgical synovectomy complete", "Surgery", "Musculoskeletal", "orthopedics", 8.00, 90)
add("29846", "Arthroscopy wrist surgical excision or repair of triangular fibrocartilage", "Surgery", "Musculoskeletal", "orthopedics", 9.50, 90)
add("29847", "Arthroscopy wrist surgical internal fixation for fracture", "Surgery", "Musculoskeletal", "orthopedics", 10.00, 90)
add("29848", "Arthroscopy wrist endoscopic carpal tunnel release", "Surgery", "Musculoskeletal", "orthopedics", 8.00, 90)

# Arthroscopy - Hip
add("29860", "Arthroscopy hip diagnostic", "Surgery", "Musculoskeletal", "orthopedics", 7.50, 90)
add("29861", "Arthroscopy hip surgical with removal of loose body", "Surgery", "Musculoskeletal", "orthopedics", 10.50, 90)
add("29862", "Arthroscopy hip surgical debridement or shaving", "Surgery", "Musculoskeletal", "orthopedics", 11.00, 90)
add("29863", "Arthroscopy hip surgical with femoroplasty", "Surgery", "Musculoskeletal", "orthopedics", 13.50, 90, asst=True)
add("29866", "Arthroscopy hip surgical osteochondral autograft", "Surgery", "Musculoskeletal", "orthopedics", 14.00, 90, asst=True)
add("29867", "Arthroscopy hip surgical osteochondral allograft", "Surgery", "Musculoskeletal", "orthopedics", 14.50, 90, asst=True)
add("29868", "Arthroscopy hip surgical labral repair", "Surgery", "Musculoskeletal", "orthopedics", 15.50, 90, asst=True)

# Arthroscopy - Knee (additional)
add("29870", "Arthroscopy knee diagnostic", "Surgery", "Musculoskeletal", "orthopedics", 4.50, 90)
add("29871", "Arthroscopy knee surgical for infection drainage", "Surgery", "Musculoskeletal", "orthopedics", 6.50, 90)
add("29873", "Arthroscopy knee surgical lateral release", "Surgery", "Musculoskeletal", "orthopedics", 6.00, 90)
add("29874", "Arthroscopy knee surgical removal of loose body", "Surgery", "Musculoskeletal", "orthopedics", 7.00, 90)
add("29875", "Arthroscopy knee surgical synovectomy limited", "Surgery", "Musculoskeletal", "orthopedics", 6.50, 90)
add("29876", "Arthroscopy knee surgical synovectomy major", "Surgery", "Musculoskeletal", "orthopedics", 8.00, 90)
add("29877", "Arthroscopy knee surgical debridement/shaving", "Surgery", "Musculoskeletal", "orthopedics", 7.50, 90)
add("29879", "Arthroscopy knee surgical abrasion arthroplasty", "Surgery", "Musculoskeletal", "orthopedics", 8.00, 90)
add("29880", "Arthroscopy knee surgical meniscectomy medial and lateral", "Surgery", "Musculoskeletal", "orthopedics", 8.50, 90)
add("29881", "Arthroscopy knee surgical meniscectomy medial or lateral", "Surgery", "Musculoskeletal", "orthopedics", 7.50, 90)
add("29882", "Arthroscopy knee surgical meniscus repair medial or lateral", "Surgery", "Musculoskeletal", "orthopedics", 10.00, 90)
add("29883", "Arthroscopy knee surgical meniscus repair medial and lateral", "Surgery", "Musculoskeletal", "orthopedics", 12.00, 90)
add("29884", "Arthroscopy knee surgical lysis of adhesions", "Surgery", "Musculoskeletal", "orthopedics", 7.00, 90)
add("29885", "Arthroscopy knee surgical drilling for osteochondritis dissecans", "Surgery", "Musculoskeletal", "orthopedics", 8.50, 90)
add("29886", "Arthroscopy knee surgical drilling for intact osteochondritis dissecans", "Surgery", "Musculoskeletal", "orthopedics", 8.00, 90)
add("29887", "Arthroscopy knee surgical drilling for osteochondritis with internal fixation", "Surgery", "Musculoskeletal", "orthopedics", 10.00, 90)
add("29888", "Arthroscopically aided anterior cruciate ligament repair", "Surgery", "Musculoskeletal", "orthopedics", 16.50, 90, asst=True)
add("29889", "Arthroscopically aided posterior cruciate ligament repair", "Surgery", "Musculoskeletal", "orthopedics", 18.00, 90, asst=True)

# Arthroscopy - Ankle
add("29891", "Arthroscopy ankle surgical excision of osteochondral defect", "Surgery", "Musculoskeletal", "orthopedics", 9.50, 90)
add("29892", "Arthroscopically aided repair of large osteochondritis dissecans ankle", "Surgery", "Musculoskeletal", "orthopedics", 11.00, 90)
add("29893", "Endoscopic plantar fasciotomy", "Surgery", "Musculoskeletal", "orthopedics", 6.50, 90)
add("29894", "Arthroscopy ankle surgical with removal of loose body", "Surgery", "Musculoskeletal", "orthopedics", 8.00, 90)
add("29895", "Arthroscopy ankle surgical synovectomy partial", "Surgery", "Musculoskeletal", "orthopedics", 7.50, 90)
add("29897", "Arthroscopy ankle surgical debridement limited", "Surgery", "Musculoskeletal", "orthopedics", 7.80, 90)
add("29898", "Arthroscopy ankle surgical debridement extensive", "Surgery", "Musculoskeletal", "orthopedics", 9.00, 90)

# ============================================================
# ELECTROPHYSIOLOGY 93600-93662
# ============================================================
add("93600", "Bundle of His recording", "Medicine", "Cardiovascular", "cardiology", 3.50, 0)
add("93602", "Intra-atrial recording", "Medicine", "Cardiovascular", "cardiology", 2.80, 0)
add("93603", "Right ventricular recording", "Medicine", "Cardiovascular", "cardiology", 2.80, 0)
add("93609", "Intraventricular and/or intra-atrial mapping of tachycardia", "Medicine", "Cardiovascular", "cardiology", 5.00, 0)
add("93610", "Intra-atrial pacing", "Medicine", "Cardiovascular", "cardiology", 2.50, 0)
add("93612", "Intraventricular pacing", "Medicine", "Cardiovascular", "cardiology", 2.50, 0)
add("93613", "Intracardiac electrophysiologic 3-dimensional mapping", "Medicine", "Cardiovascular", "cardiology", 7.50, 0)
add("93615", "Esophageal recording of atrial electrogram", "Medicine", "Cardiovascular", "cardiology", 1.50, 0)
add("93616", "Esophageal recording of atrial electrogram with pacing", "Medicine", "Cardiovascular", "cardiology", 2.20, 0)
add("93618", "Induction of arrhythmia by electrical pacing", "Medicine", "Cardiovascular", "cardiology", 3.80, 0)
add("93619", "Comprehensive EP testing without arrhythmia induction", "Medicine", "Cardiovascular", "cardiology", 8.50, 0)
add("93620", "Comprehensive EP testing with arrhythmia induction", "Medicine", "Cardiovascular", "cardiology", 10.50, 0)
add("93621", "Comprehensive EP testing with left atrial pacing add-on", "Medicine", "Cardiovascular", "cardiology", 2.50, 0, addon=True)
add("93622", "Comprehensive EP testing with left atrial recording add-on", "Medicine", "Cardiovascular", "cardiology", 2.50, 0, addon=True)
add("93623", "Programmed stimulation and pacing after IV drug infusion", "Medicine", "Cardiovascular", "cardiology", 2.00, 0, addon=True)
add("93624", "Electrophysiologic follow-up study with pacing", "Medicine", "Cardiovascular", "cardiology", 5.00, 0)
add("93631", "Intra-operative epicardial and endocardial pacing and mapping", "Medicine", "Cardiovascular", "cardiology", 8.00, 0)
add("93640", "Electrophysiologic evaluation of single chamber pacing cardioverter-defibrillator", "Medicine", "Cardiovascular", "cardiology", 3.50, 0)
add("93641", "Electrophysiologic evaluation of single chamber transvenous ICD with arrhythmia induction", "Medicine", "Cardiovascular", "cardiology", 5.50, 0)
add("93642", "Electrophysiologic evaluation of single chamber transvenous ICD with reprogramming", "Medicine", "Cardiovascular", "cardiology", 4.50, 0)
add("93644", "Electrophysiologic evaluation of subcutaneous ICD", "Medicine", "Cardiovascular", "cardiology", 5.00, 0)
add("93650", "Intracardiac catheter ablation of atrioventricular node function", "Medicine", "Cardiovascular", "cardiology", 12.00, 0, asst=True)
add("93653", "Comprehensive EP evaluation with ablation of supraventricular tachycardia", "Medicine", "Cardiovascular", "cardiology", 15.00, 0, asst=True)
add("93654", "Comprehensive EP evaluation with ablation of ventricular tachycardia", "Medicine", "Cardiovascular", "cardiology", 18.00, 0, asst=True)
add("93655", "Intracardiac catheter ablation additional SVT mechanism add-on", "Medicine", "Cardiovascular", "cardiology", 5.00, 0, addon=True)
add("93656", "Comprehensive EP evaluation with ablation of atrial fibrillation pulmonary vein isolation", "Medicine", "Cardiovascular", "cardiology", 20.00, 0, asst=True)
add("93657", "Additional linear or focal intracardiac catheter ablation add-on", "Medicine", "Cardiovascular", "cardiology", 5.00, 0, addon=True)
add("93660", "Evaluation of patient activated cardiac event recorder", "Medicine", "Cardiovascular", "cardiology", 1.50, 0)
add("93662", "Intracardiac echocardiography during EP procedure add-on", "Medicine", "Cardiovascular", "cardiology", 3.00, 0, addon=True)

# ============================================================
# PACEMAKER/ICD 33206-33275
# ============================================================
add("33206", "Insertion of new or replacement permanent pacemaker atrial electrode", "Surgery", "Cardiovascular", "cardiology", 7.50, 90, asst=True)
add("33207", "Insertion of new or replacement permanent pacemaker ventricular electrode", "Surgery", "Cardiovascular", "cardiology", 7.50, 90, asst=True)
add("33208", "Insertion of new or replacement permanent pacemaker atrial and ventricular electrodes", "Surgery", "Cardiovascular", "cardiology", 9.50, 90, asst=True)
add("33210", "Insertion of temporary transvenous single chamber cardiac electrode", "Surgery", "Cardiovascular", "cardiology", 4.00, 0)
add("33211", "Insertion of temporary transvenous dual chamber cardiac electrode", "Surgery", "Cardiovascular", "cardiology", 5.50, 0)
add("33212", "Insertion of pacemaker pulse generator only single chamber", "Surgery", "Cardiovascular", "cardiology", 6.00, 90)
add("33213", "Insertion of pacemaker pulse generator only dual chamber", "Surgery", "Cardiovascular", "cardiology", 7.00, 90)
add("33214", "Upgrade of pacemaker system single chamber to dual chamber", "Surgery", "Cardiovascular", "cardiology", 8.50, 90, asst=True)
add("33215", "Repositioning of previously implanted transvenous pacemaker electrode", "Surgery", "Cardiovascular", "cardiology", 5.50, 90)
add("33216", "Insertion of single transvenous electrode permanent pacemaker or ICD", "Surgery", "Cardiovascular", "cardiology", 6.50, 90, asst=True)
add("33217", "Insertion of 2 transvenous electrodes permanent pacemaker or ICD", "Surgery", "Cardiovascular", "cardiology", 8.50, 90, asst=True)
add("33218", "Repair of single transvenous electrode for pacemaker or ICD", "Surgery", "Cardiovascular", "cardiology", 6.00, 90)
add("33220", "Repair of 2 transvenous electrodes for pacemaker or ICD", "Surgery", "Cardiovascular", "cardiology", 7.50, 90)
add("33221", "Insertion of pacemaker pulse generator CRT", "Surgery", "Cardiovascular", "cardiology", 8.00, 90, asst=True)
add("33222", "Relocation of skin pocket for pacemaker", "Surgery", "Cardiovascular", "cardiology", 5.00, 90)
add("33223", "Relocation of skin pocket for ICD", "Surgery", "Cardiovascular", "cardiology", 6.00, 90)
add("33224", "Insertion of LV electrode for biventricular pacing", "Surgery", "Cardiovascular", "cardiology", 9.50, 90, asst=True)
add("33225", "Insertion of LV electrode at time of ICD insertion add-on", "Surgery", "Cardiovascular", "cardiology", 5.50, 0, addon=True)
add("33226", "Repositioning of previously implanted LV electrode", "Surgery", "Cardiovascular", "cardiology", 7.00, 90)
add("33227", "Removal and replacement of pacemaker pulse generator single chamber", "Surgery", "Cardiovascular", "cardiology", 5.00, 90)
add("33228", "Removal and replacement of pacemaker pulse generator dual chamber", "Surgery", "Cardiovascular", "cardiology", 5.50, 90)
add("33229", "Removal and replacement of pacemaker pulse generator CRT", "Surgery", "Cardiovascular", "cardiology", 6.00, 90)
add("33230", "Insertion of ICD pulse generator with existing dual leads", "Surgery", "Cardiovascular", "cardiology", 8.00, 90, asst=True)
add("33231", "Insertion of ICD pulse generator with existing single lead", "Surgery", "Cardiovascular", "cardiology", 7.00, 90, asst=True)
add("33233", "Removal of permanent pacemaker pulse generator", "Surgery", "Cardiovascular", "cardiology", 4.50, 90)
add("33234", "Removal of transvenous pacemaker electrode single lead", "Surgery", "Cardiovascular", "cardiology", 6.00, 90)
add("33235", "Removal of transvenous pacemaker electrode dual lead", "Surgery", "Cardiovascular", "cardiology", 7.50, 90)
add("33236", "Removal of permanent epicardial pacemaker", "Surgery", "Cardiovascular", "cardiology", 8.00, 90, asst=True)
add("33237", "Removal of permanent transvenous electrode by thoracotomy", "Surgery", "Cardiovascular", "cardiology", 15.00, 90, asst=True)
add("33238", "Removal of permanent transvenous electrode by thoracotomy", "Surgery", "Cardiovascular", "cardiology", 16.00, 90, asst=True)
add("33240", "Insertion of ICD pulse generator only with existing leads", "Surgery", "Cardiovascular", "cardiology", 7.50, 90, asst=True)
add("33241", "Removal of ICD pulse generator only", "Surgery", "Cardiovascular", "cardiology", 5.50, 90)
add("33243", "Removal of ICD electrode by thoracotomy", "Surgery", "Cardiovascular", "cardiology", 16.50, 90, asst=True)
add("33244", "Removal of ICD electrode by transvenous extraction", "Surgery", "Cardiovascular", "cardiology", 10.50, 90)
add("33249", "Insertion or replacement of ICD single or dual chamber", "Surgery", "Cardiovascular", "cardiology", 12.50, 90, asst=True)
add("33250", "Operative ablation of supraventricular arrhythmogenic focus", "Surgery", "Cardiovascular", "cardiology", 20.00, 90, asst=True)
add("33251", "Operative ablation of supraventricular arrhythmogenic focus with cardiopulmonary bypass", "Surgery", "Cardiovascular", "cardiology", 25.00, 90, asst=True)
add("33254", "Operative tissue ablation for atrial fibrillation limited", "Surgery", "Cardiovascular", "cardiology", 22.00, 90, asst=True)
add("33255", "Operative tissue ablation for atrial fibrillation extensive", "Surgery", "Cardiovascular", "cardiology", 25.00, 90, asst=True)
add("33256", "Operative tissue ablation for atrial fibrillation with bypass add-on", "Surgery", "Cardiovascular", "cardiology", 15.00, 0, addon=True)
add("33257", "Operative tissue ablation for atrial fibrillation without bypass add-on", "Surgery", "Cardiovascular", "cardiology", 12.00, 0, addon=True)
add("33258", "Operative tissue ablation for atrial fibrillation endoscopic", "Surgery", "Cardiovascular", "cardiology", 20.00, 90, asst=True)
add("33259", "Operative tissue ablation for atrial fibrillation extensive with bypass", "Surgery", "Cardiovascular", "cardiology", 28.00, 90, asst=True)
add("33261", "Operative ablation of ventricular arrhythmogenic focus", "Surgery", "Cardiovascular", "cardiology", 22.00, 90, asst=True)
add("33262", "Removal and replacement of ICD pulse generator single", "Surgery", "Cardiovascular", "cardiology", 6.00, 90)
add("33263", "Removal and replacement of ICD pulse generator dual", "Surgery", "Cardiovascular", "cardiology", 7.00, 90)
add("33264", "Removal and replacement of ICD pulse generator CRT", "Surgery", "Cardiovascular", "cardiology", 8.00, 90)
add("33270", "Insertion or replacement of subcutaneous ICD", "Surgery", "Cardiovascular", "cardiology", 10.00, 90, asst=True)
add("33271", "Insertion of subcutaneous ICD electrode", "Surgery", "Cardiovascular", "cardiology", 8.00, 90)
add("33272", "Removal of subcutaneous ICD electrode", "Surgery", "Cardiovascular", "cardiology", 6.50, 90)
add("33273", "Repositioning of subcutaneous ICD electrode", "Surgery", "Cardiovascular", "cardiology", 5.50, 90)
add("33274", "Transcatheter insertion of permanent leadless pacemaker", "Surgery", "Cardiovascular", "cardiology", 10.50, 90, asst=True)
add("33275", "Transcatheter removal of permanent leadless pacemaker", "Surgery", "Cardiovascular", "cardiology", 8.50, 90)

# ============================================================
# RADIATION THERAPY 77261-77799
# ============================================================
add("77261", "Therapeutic radiology treatment planning simple", "Radiology", "Radiation Therapy", "radiation_oncology", 1.50, 0)
add("77262", "Therapeutic radiology treatment planning intermediate", "Radiology", "Radiation Therapy", "radiation_oncology", 2.30, 0)
add("77263", "Therapeutic radiology treatment planning complex", "Radiology", "Radiation Therapy", "radiation_oncology", 3.50, 0)
add("77280", "Therapeutic radiology simulation simple", "Radiology", "Radiation Therapy", "radiation_oncology", 1.00, 0)
add("77285", "Therapeutic radiology simulation intermediate", "Radiology", "Radiation Therapy", "radiation_oncology", 1.50, 0)
add("77290", "Therapeutic radiology simulation complex", "Radiology", "Radiation Therapy", "radiation_oncology", 2.20, 0)
add("77293", "Respiratory motion management simulation", "Radiology", "Radiation Therapy", "radiation_oncology", 1.80, 0)
add("77295", "3-dimensional radiotherapy plan", "Radiology", "Radiation Therapy", "radiation_oncology", 6.00, 0)
add("77299", "Unlisted procedure therapeutic radiology clinical treatment planning", "Radiology", "Radiation Therapy", "radiation_oncology", 3.00, 0)
add("77300", "Basic radiation dosimetry calculation", "Radiology", "Radiation Therapy", "radiation_oncology", 0.80, 0)
add("77301", "Intensity modulated radiotherapy plan", "Radiology", "Radiation Therapy", "radiation_oncology", 8.00, 0)
add("77306", "Teletherapy isodose plan simple", "Radiology", "Radiation Therapy", "radiation_oncology", 2.00, 0)
add("77307", "Teletherapy isodose plan complex", "Radiology", "Radiation Therapy", "radiation_oncology", 3.50, 0)
add("77316", "Brachytherapy isodose plan simple", "Radiology", "Radiation Therapy", "radiation_oncology", 2.50, 0)
add("77317", "Brachytherapy isodose plan intermediate", "Radiology", "Radiation Therapy", "radiation_oncology", 4.00, 0)
add("77318", "Brachytherapy isodose plan complex", "Radiology", "Radiation Therapy", "radiation_oncology", 5.50, 0)
add("77321", "Special teletherapy port plan", "Radiology", "Radiation Therapy", "radiation_oncology", 1.50, 0)
add("77331", "Special dosimetry calculation", "Radiology", "Radiation Therapy", "radiation_oncology", 0.50, 0)
add("77332", "Treatment devices simple", "Radiology", "Radiation Therapy", "radiation_oncology", 0.80, 0)
add("77333", "Treatment devices intermediate", "Radiology", "Radiation Therapy", "radiation_oncology", 1.20, 0)
add("77334", "Treatment devices complex", "Radiology", "Radiation Therapy", "radiation_oncology", 1.80, 0)
add("77336", "Continuing medical physics consultation per week of therapy", "Radiology", "Radiation Therapy", "radiation_oncology", 0.80, 0)
add("77338", "Multi-leaf collimator device for IMRT", "Radiology", "Radiation Therapy", "radiation_oncology", 1.00, 0)
add("77370", "Computed tomography guidance for radiation treatment", "Radiology", "Radiation Therapy", "radiation_oncology", 0.80, 0)
add("77371", "Radiation treatment delivery stereotactic radiosurgery cranial", "Radiology", "Radiation Therapy", "radiation_oncology", 10.00, 0)
add("77372", "Radiation treatment delivery stereotactic radiosurgery linear accelerator based", "Radiology", "Radiation Therapy", "radiation_oncology", 8.00, 0)
add("77373", "Stereotactic body radiation therapy treatment delivery", "Radiology", "Radiation Therapy", "radiation_oncology", 7.00, 0)
add("77385", "Intensity modulated radiation treatment delivery simple", "Radiology", "Radiation Therapy", "radiation_oncology", 2.50, 0)
add("77386", "Intensity modulated radiation treatment delivery complex", "Radiology", "Radiation Therapy", "radiation_oncology", 3.50, 0)
add("77387", "Guidance for localization of target volume", "Radiology", "Radiation Therapy", "radiation_oncology", 0.80, 0)
add("77401", "Radiation treatment delivery superficial voltage", "Radiology", "Radiation Therapy", "radiation_oncology", 0.50, 0)
add("77402", "Radiation treatment delivery simple", "Radiology", "Radiation Therapy", "radiation_oncology", 1.00, 0)
add("77407", "Radiation treatment delivery intermediate", "Radiology", "Radiation Therapy", "radiation_oncology", 1.50, 0)
add("77412", "Radiation treatment delivery complex", "Radiology", "Radiation Therapy", "radiation_oncology", 2.00, 0)
add("77417", "Therapeutic radiology port image(s)", "Radiology", "Radiation Therapy", "radiation_oncology", 0.30, 0)
add("77427", "Radiation treatment management 5 treatments", "Radiology", "Radiation Therapy", "radiation_oncology", 3.10, 0)
add("77431", "Radiation therapy management with complete course of therapy", "Radiology", "Radiation Therapy", "radiation_oncology", 4.00, 0)
add("77432", "Stereotactic radiation treatment management of cranial lesion", "Radiology", "Radiation Therapy", "radiation_oncology", 7.00, 0)
add("77435", "Stereotactic body radiation therapy treatment management", "Radiology", "Radiation Therapy", "radiation_oncology", 6.50, 0)
add("77469", "Intraoperative radiation treatment management", "Radiology", "Radiation Therapy", "radiation_oncology", 5.00, 0)
add("77470", "Special treatment procedure", "Radiology", "Radiation Therapy", "radiation_oncology", 2.50, 0)
add("77520", "Proton treatment delivery simple without compensation", "Radiology", "Radiation Therapy", "radiation_oncology", 3.00, 0)
add("77522", "Proton treatment delivery simple with compensation", "Radiology", "Radiation Therapy", "radiation_oncology", 3.50, 0)
add("77523", "Proton treatment delivery intermediate", "Radiology", "Radiation Therapy", "radiation_oncology", 4.50, 0)
add("77525", "Proton treatment delivery complex", "Radiology", "Radiation Therapy", "radiation_oncology", 5.50, 0)
add("77600", "Hyperthermia externally generated superficial", "Radiology", "Radiation Therapy", "radiation_oncology", 2.50, 0)
add("77605", "Hyperthermia externally generated deep", "Radiology", "Radiation Therapy", "radiation_oncology", 3.50, 0)
add("77610", "Hyperthermia generated by interstitial probe", "Radiology", "Radiation Therapy", "radiation_oncology", 4.00, 0)
add("77615", "Hyperthermia generated by intracavitary probe", "Radiology", "Radiation Therapy", "radiation_oncology", 4.00, 0)
add("77750", "Infusion or installation of radioelement solution", "Radiology", "Radiation Therapy", "radiation_oncology", 2.50, 0)
add("77761", "Intracavitary radiation source application simple", "Radiology", "Radiation Therapy", "radiation_oncology", 5.00, 0)
add("77762", "Intracavitary radiation source application intermediate", "Radiology", "Radiation Therapy", "radiation_oncology", 7.00, 0)
add("77763", "Intracavitary radiation source application complex", "Radiology", "Radiation Therapy", "radiation_oncology", 9.00, 0)
add("77767", "Remote afterloading high dose rate brachytherapy 1 channel", "Radiology", "Radiation Therapy", "radiation_oncology", 5.50, 0)
add("77768", "Remote afterloading high dose rate brachytherapy 2-12 channels", "Radiology", "Radiation Therapy", "radiation_oncology", 8.00, 0)
add("77770", "Remote afterloading high dose rate brachytherapy skin surface", "Radiology", "Radiation Therapy", "radiation_oncology", 5.00, 0)
add("77771", "Remote afterloading high dose rate brachytherapy interstitial", "Radiology", "Radiation Therapy", "radiation_oncology", 7.00, 0)
add("77772", "Remote afterloading high dose rate brachytherapy intracavitary", "Radiology", "Radiation Therapy", "radiation_oncology", 8.50, 0)
add("77778", "Interstitial radiation source application complex", "Radiology", "Radiation Therapy", "radiation_oncology", 10.00, 0)
add("77789", "Surface application of low dose rate radionuclide source", "Radiology", "Radiation Therapy", "radiation_oncology", 3.00, 0)
add("77790", "Supervision handling loading of radiation source", "Radiology", "Radiation Therapy", "radiation_oncology", 0.50, 0)
add("77799", "Unlisted procedure therapeutic radiology", "Radiology", "Radiation Therapy", "radiation_oncology", 3.00, 0)

# ============================================================
# MOHS SURGERY 17311-17315
# ============================================================
add("17311", "Mohs micrographic technique including removal of all gross tumor first stage head neck hands feet genitalia", "Surgery", "Integumentary", "dermatology", 7.60, 10)
add("17312", "Mohs micrographic technique each additional block first stage add-on", "Surgery", "Integumentary", "dermatology", 2.80, 0, addon=True)
add("17313", "Mohs micrographic technique first stage trunk arms legs", "Surgery", "Integumentary", "dermatology", 6.50, 10)
add("17314", "Mohs micrographic technique each additional block any stage add-on", "Surgery", "Integumentary", "dermatology", 2.80, 0, addon=True)
add("17315", "Mohs micrographic technique each additional stage after the first stage", "Surgery", "Integumentary", "dermatology", 5.20, 0, addon=True)

# ============================================================
# SHAVING OF LESIONS 11300-11313
# ============================================================
add("11300", "Shaving of epidermal or dermal lesion trunk arms or legs 0.5cm or less", "Surgery", "Integumentary", "dermatology", 0.80, 10)
add("11301", "Shaving of epidermal or dermal lesion trunk arms or legs 0.6-1.0cm", "Surgery", "Integumentary", "dermatology", 0.95, 10)
add("11302", "Shaving of epidermal or dermal lesion trunk arms or legs 1.1-2.0cm", "Surgery", "Integumentary", "dermatology", 1.10, 10)
add("11303", "Shaving of epidermal or dermal lesion trunk arms or legs over 2.0cm", "Surgery", "Integumentary", "dermatology", 1.40, 10)
add("11305", "Shaving of epidermal or dermal lesion scalp neck hands feet genitalia 0.5cm or less", "Surgery", "Integumentary", "dermatology", 0.90, 10)
add("11306", "Shaving of epidermal or dermal lesion scalp neck hands feet genitalia 0.6-1.0cm", "Surgery", "Integumentary", "dermatology", 1.05, 10)
add("11307", "Shaving of epidermal or dermal lesion scalp neck hands feet genitalia 1.1-2.0cm", "Surgery", "Integumentary", "dermatology", 1.25, 10)
add("11308", "Shaving of epidermal or dermal lesion scalp neck hands feet genitalia over 2.0cm", "Surgery", "Integumentary", "dermatology", 1.55, 10)
add("11310", "Shaving of epidermal or dermal lesion face ears eyelids nose lips mucous membrane 0.5cm or less", "Surgery", "Integumentary", "dermatology", 1.00, 10)
add("11311", "Shaving of epidermal or dermal lesion face ears eyelids nose lips mucous membrane 0.6-1.0cm", "Surgery", "Integumentary", "dermatology", 1.15, 10)
add("11312", "Shaving of epidermal or dermal lesion face ears eyelids nose lips mucous membrane 1.1-2.0cm", "Surgery", "Integumentary", "dermatology", 1.35, 10)
add("11313", "Shaving of epidermal or dermal lesion face ears eyelids nose lips mucous membrane over 2.0cm", "Surgery", "Integumentary", "dermatology", 1.65, 10)

# ============================================================
# SKIN TAGS 11200-11201
# ============================================================
add("11200", "Removal of skin tags multiple fibrocutaneous tags up to and including 15 lesions", "Surgery", "Integumentary", "dermatology", 0.80, 10)
add("11201", "Removal of skin tags each additional 10 lesions add-on", "Surgery", "Integumentary", "dermatology", 0.30, 0, addon=True)

# ============================================================
# PULMONARY FUNCTION TESTS 94010-94799
# ============================================================
add("94010", "Spirometry including graphic record total and timed vital capacity", "Medicine", "Pulmonary", "pulmonology", 0.50, 0)
add("94011", "Spirometry measurement of forced expiratory flows in infants", "Medicine", "Pulmonary", "pulmonology", 0.60, 0)
add("94012", "Measurement of spirometric forced expiratory flows in first 2 years of life", "Medicine", "Pulmonary", "pulmonology", 0.50, 0)
add("94013", "Measurement of lung volumes in infants", "Medicine", "Pulmonary", "pulmonology", 0.60, 0)
add("94014", "Patient-initiated spirometric recording per 30-day period", "Medicine", "Pulmonary", "pulmonology", 0.20, 0)
add("94015", "Patient-initiated spirometric recording with physician review", "Medicine", "Pulmonary", "pulmonology", 0.30, 0)
add("94016", "Review and interpretation of spirometric data", "Medicine", "Pulmonary", "pulmonology", 0.15, 0)
add("94060", "Bronchodilation responsiveness spirometry pre and post bronchodilator", "Medicine", "Pulmonary", "pulmonology", 0.55, 0)
add("94070", "Bronchospasm provocation evaluation with spirometry", "Medicine", "Pulmonary", "pulmonology", 1.00, 0)
add("94150", "Vital capacity total", "Medicine", "Pulmonary", "pulmonology", 0.17, 0)
add("94200", "Maximum breathing capacity maximal voluntary ventilation", "Medicine", "Pulmonary", "pulmonology", 0.25, 0)
add("94250", "Expired gas collection quantitative single procedure", "Medicine", "Pulmonary", "pulmonology", 0.10, 0)
add("94375", "Respiratory flow volume loop", "Medicine", "Pulmonary", "pulmonology", 0.30, 0)
add("94400", "Breathing response to CO2", "Medicine", "Pulmonary", "pulmonology", 0.50, 0)
add("94450", "Breathing response to hypoxia", "Medicine", "Pulmonary", "pulmonology", 0.50, 0)
add("94452", "High altitude simulation test", "Medicine", "Pulmonary", "pulmonology", 0.60, 0)
add("94453", "High altitude simulation test with supplemental oxygen", "Medicine", "Pulmonary", "pulmonology", 0.70, 0)
add("94610", "Intrapulmonary surfactant administration through endotracheal tube", "Medicine", "Pulmonary", "pulmonology", 2.00, 0)
add("94620", "Pulmonary stress testing simple", "Medicine", "Pulmonary", "pulmonology", 0.80, 0)
add("94621", "Cardiopulmonary exercise testing", "Medicine", "Pulmonary", "pulmonology", 1.80, 0)
add("94640", "Pressurized or nonpressurized inhalation treatment for acute airway obstruction", "Medicine", "Pulmonary", "pulmonology", 0.30, 0)
add("94642", "Aerosol inhalation of pentamidine for pneumocystis carinii pneumonia", "Medicine", "Pulmonary", "pulmonology", 0.20, 0)
add("94644", "Continuous inhalation treatment first hour", "Medicine", "Pulmonary", "pulmonology", 0.50, 0)
add("94645", "Continuous inhalation treatment each additional hour", "Medicine", "Pulmonary", "pulmonology", 0.30, 0, addon=True)
add("94660", "Continuous positive airway pressure ventilation CPAP initiation and management", "Medicine", "Pulmonary", "pulmonology", 1.50, 0)
add("94662", "Continuous negative pressure ventilation", "Medicine", "Pulmonary", "pulmonology", 1.20, 0)
add("94664", "Demonstration and/or evaluation of patient utilization of aerosol generator", "Medicine", "Pulmonary", "pulmonology", 0.15, 0)
add("94667", "Manipulation of chest wall such as cupping pounding and vibration", "Medicine", "Pulmonary", "pulmonology", 0.50, 0)
add("94668", "Manipulation of chest wall such as cupping pounding and vibration each additional day", "Medicine", "Pulmonary", "pulmonology", 0.30, 0)
add("94680", "Oxygen uptake expired gas analysis rest and exercise", "Medicine", "Pulmonary", "pulmonology", 0.40, 0)
add("94681", "Oxygen uptake expired gas analysis including CO2 output", "Medicine", "Pulmonary", "pulmonology", 0.50, 0)
add("94690", "Oxygen uptake expired gas analysis rest exercise and CO2", "Medicine", "Pulmonary", "pulmonology", 0.60, 0)
add("94726", "Plethysmography for determination of lung volumes and when performed airway resistance", "Medicine", "Pulmonary", "pulmonology", 0.60, 0)
add("94727", "Gas dilution or washout for determination of lung volumes", "Medicine", "Pulmonary", "pulmonology", 0.50, 0)
add("94728", "Airway resistance by impulse oscillometry", "Medicine", "Pulmonary", "pulmonology", 0.35, 0)
add("94729", "Diffusing capacity", "Medicine", "Pulmonary", "pulmonology", 0.40, 0)
add("94750", "Pulmonary compliance study", "Medicine", "Pulmonary", "pulmonology", 0.50, 0)
add("94760", "Noninvasive ear or pulse oximetry single determination", "Medicine", "Pulmonary", "pulmonology", 0.10, 0)
add("94761", "Noninvasive ear or pulse oximetry multiple determinations", "Medicine", "Pulmonary", "pulmonology", 0.15, 0)
add("94762", "Noninvasive ear or pulse oximetry continuous overnight monitoring", "Medicine", "Pulmonary", "pulmonology", 0.50, 0)
add("94770", "Carbon dioxide expired gas determination by infrared analyzer", "Medicine", "Pulmonary", "pulmonology", 0.15, 0)
add("94772", "Circadian respiratory pattern recording pediatric 12-24 hours", "Medicine", "Pulmonary", "pulmonology", 1.00, 0)
add("94774", "Pediatric home apnea monitoring event recording including analysis", "Medicine", "Pulmonary", "pulmonology", 0.50, 0)
add("94775", "Pediatric home apnea monitoring event recording including parent instructions", "Medicine", "Pulmonary", "pulmonology", 0.30, 0)
add("94776", "Pediatric home apnea monitoring event recording interpretation only", "Medicine", "Pulmonary", "pulmonology", 0.40, 0)
add("94777", "Pediatric home apnea monitoring complete system including analysis", "Medicine", "Pulmonary", "pulmonology", 0.80, 0)
add("94780", "Car seat/bed testing for airway integrity neonate 60 min", "Medicine", "Pulmonary", "pulmonology", 0.50, 0)
add("94781", "Car seat/bed testing for airway integrity neonate each additional 30 min", "Medicine", "Pulmonary", "pulmonology", 0.25, 0, addon=True)
add("94799", "Unlisted pulmonary service or procedure", "Medicine", "Pulmonary", "pulmonology", 1.00, 0)

# ============================================================
# PSYCHIATRY 90791-90840
# ============================================================
add("90791", "Psychiatric diagnostic evaluation", "Medicine", "Psychiatry", "psychiatry", 3.00, 0)
add("90792", "Psychiatric diagnostic evaluation with medical services", "Medicine", "Psychiatry", "psychiatry", 3.50, 0)
add("90832", "Psychotherapy 30 minutes", "Medicine", "Psychiatry", "psychiatry", 1.50, 0)
add("90833", "Psychotherapy 30 minutes with E/M service add-on", "Medicine", "Psychiatry", "psychiatry", 1.35, 0, addon=True)
add("90834", "Psychotherapy 45 minutes", "Medicine", "Psychiatry", "psychiatry", 2.10, 0)
add("90836", "Psychotherapy 45 minutes with E/M service add-on", "Medicine", "Psychiatry", "psychiatry", 1.90, 0, addon=True)
add("90837", "Psychotherapy 60 minutes", "Medicine", "Psychiatry", "psychiatry", 2.80, 0)
add("90838", "Psychotherapy 60 minutes with E/M service add-on", "Medicine", "Psychiatry", "psychiatry", 2.50, 0, addon=True)
add("90839", "Psychotherapy for crisis first 60 minutes", "Medicine", "Psychiatry", "psychiatry", 3.60, 0)
add("90840", "Psychotherapy for crisis each additional 30 minutes add-on", "Medicine", "Psychiatry", "psychiatry", 1.80, 0, addon=True)
add("90845", "Psychoanalysis", "Medicine", "Psychiatry", "psychiatry", 2.80, 0)
add("90846", "Family psychotherapy without patient present 50 minutes", "Medicine", "Psychiatry", "psychiatry", 2.50, 0)
add("90847", "Family psychotherapy with patient present 50 minutes", "Medicine", "Psychiatry", "psychiatry", 2.60, 0)
add("90849", "Multiple-family group psychotherapy", "Medicine", "Psychiatry", "psychiatry", 1.20, 0)
add("90853", "Group psychotherapy", "Medicine", "Psychiatry", "psychiatry", 1.00, 0)
add("90863", "Pharmacologic management with psychotherapy", "Medicine", "Psychiatry", "psychiatry", 0.80, 0, addon=True)
add("90865", "Narcosynthesis for psychiatric diagnostic and therapeutic purposes", "Medicine", "Psychiatry", "psychiatry", 3.00, 0)
add("90867", "Therapeutic repetitive transcranial magnetic stimulation treatment delivery initial", "Medicine", "Psychiatry", "psychiatry", 2.50, 0)
add("90868", "Therapeutic repetitive transcranial magnetic stimulation treatment delivery subsequent", "Medicine", "Psychiatry", "psychiatry", 1.50, 0)
add("90869", "Therapeutic repetitive transcranial magnetic stimulation treatment redetermination", "Medicine", "Psychiatry", "psychiatry", 2.00, 0)
add("90870", "Electroconvulsive therapy", "Medicine", "Psychiatry", "psychiatry", 3.50, 0)
add("90875", "Individual psychophysiological therapy with biofeedback 30 min", "Medicine", "Psychiatry", "psychiatry", 1.50, 0)
add("90876", "Individual psychophysiological therapy with biofeedback 45 min", "Medicine", "Psychiatry", "psychiatry", 2.00, 0)
add("90880", "Hypnotherapy", "Medicine", "Psychiatry", "psychiatry", 2.50, 0)
add("90882", "Environmental intervention for medical management purposes", "Medicine", "Psychiatry", "psychiatry", 1.50, 0)
add("90885", "Psychiatric evaluation of hospital records", "Medicine", "Psychiatry", "psychiatry", 1.00, 0)
add("90887", "Interpretation or explanation of results to family or other persons", "Medicine", "Psychiatry", "psychiatry", 1.00, 0)
add("90889", "Preparation of report of patient psychiatric status", "Medicine", "Psychiatry", "psychiatry", 1.20, 0)
add("90899", "Unlisted psychiatric service or procedure", "Medicine", "Psychiatry", "psychiatry", 2.00, 0)

# ============================================================
# PT/OT 97001-97799
# ============================================================
add("97010", "Application of a modality hot or cold packs", "Medicine", "Physical Medicine", "physical_therapy", 0.10, 0)
add("97012", "Application of a modality traction mechanical", "Medicine", "Physical Medicine", "physical_therapy", 0.20, 0)
add("97014", "Application of a modality electrical stimulation unattended", "Medicine", "Physical Medicine", "physical_therapy", 0.20, 0)
add("97016", "Application of a modality vasopneumatic devices", "Medicine", "Physical Medicine", "physical_therapy", 0.15, 0)
add("97018", "Application of a modality paraffin bath", "Medicine", "Physical Medicine", "physical_therapy", 0.10, 0)
add("97022", "Application of a modality whirlpool", "Medicine", "Physical Medicine", "physical_therapy", 0.15, 0)
add("97024", "Application of a modality diathermy", "Medicine", "Physical Medicine", "physical_therapy", 0.15, 0)
add("97026", "Application of a modality infrared", "Medicine", "Physical Medicine", "physical_therapy", 0.10, 0)
add("97028", "Application of a modality ultraviolet", "Medicine", "Physical Medicine", "physical_therapy", 0.15, 0)
add("97032", "Application of a modality electrical stimulation manual each 15 minutes", "Medicine", "Physical Medicine", "physical_therapy", 0.45, 0)
add("97033", "Application of a modality iontophoresis each 15 minutes", "Medicine", "Physical Medicine", "physical_therapy", 0.45, 0)
add("97034", "Application of a modality contrast baths each 15 minutes", "Medicine", "Physical Medicine", "physical_therapy", 0.20, 0)
add("97035", "Application of a modality ultrasound each 15 minutes", "Medicine", "Physical Medicine", "physical_therapy", 0.40, 0)
add("97036", "Application of a modality Hubbard tank each 15 minutes", "Medicine", "Physical Medicine", "physical_therapy", 0.30, 0)
add("97039", "Unlisted modality", "Medicine", "Physical Medicine", "physical_therapy", 0.30, 0)
add("97110", "Therapeutic procedure therapeutic exercises each 15 minutes", "Medicine", "Physical Medicine", "physical_therapy", 0.75, 0)
add("97112", "Therapeutic procedure neuromuscular reeducation each 15 minutes", "Medicine", "Physical Medicine", "physical_therapy", 0.75, 0)
add("97113", "Therapeutic procedure aquatic therapy each 15 minutes", "Medicine", "Physical Medicine", "physical_therapy", 0.75, 0)
add("97116", "Therapeutic procedure gait training each 15 minutes", "Medicine", "Physical Medicine", "physical_therapy", 0.60, 0)
add("97124", "Therapeutic procedure massage each 15 minutes", "Medicine", "Physical Medicine", "physical_therapy", 0.60, 0)
add("97129", "Therapeutic interventions cognitive function each 15 minutes", "Medicine", "Physical Medicine", "physical_therapy", 0.75, 0)
add("97130", "Therapeutic interventions cognitive function each additional 15 min add-on", "Medicine", "Physical Medicine", "physical_therapy", 0.60, 0, addon=True)
add("97139", "Unlisted therapeutic procedure", "Medicine", "Physical Medicine", "physical_therapy", 0.50, 0)
add("97140", "Manual therapy techniques one or more regions each 15 minutes", "Medicine", "Physical Medicine", "physical_therapy", 0.75, 0)
add("97150", "Therapeutic procedure group 2 or more individuals", "Medicine", "Physical Medicine", "physical_therapy", 0.40, 0)
add("97161", "Physical therapy evaluation low complexity", "Medicine", "Physical Medicine", "physical_therapy", 1.20, 0)
add("97162", "Physical therapy evaluation moderate complexity", "Medicine", "Physical Medicine", "physical_therapy", 1.50, 0)
add("97163", "Physical therapy evaluation high complexity", "Medicine", "Physical Medicine", "physical_therapy", 2.00, 0)
add("97164", "Physical therapy re-evaluation", "Medicine", "Physical Medicine", "physical_therapy", 1.00, 0)
add("97165", "Occupational therapy evaluation low complexity", "Medicine", "Physical Medicine", "occupational_therapy", 1.20, 0)
add("97166", "Occupational therapy evaluation moderate complexity", "Medicine", "Physical Medicine", "occupational_therapy", 1.50, 0)
add("97167", "Occupational therapy evaluation high complexity", "Medicine", "Physical Medicine", "occupational_therapy", 2.00, 0)
add("97168", "Occupational therapy re-evaluation", "Medicine", "Physical Medicine", "occupational_therapy", 1.00, 0)
add("97530", "Therapeutic activities direct patient contact each 15 minutes", "Medicine", "Physical Medicine", "physical_therapy", 0.70, 0)
add("97533", "Sensory integrative techniques each 15 minutes", "Medicine", "Physical Medicine", "physical_therapy", 0.70, 0)
add("97535", "Self-care/home management training each 15 minutes", "Medicine", "Physical Medicine", "physical_therapy", 0.65, 0)
add("97537", "Community/work reintegration training each 15 minutes", "Medicine", "Physical Medicine", "physical_therapy", 0.65, 0)
add("97542", "Wheelchair management each 15 minutes", "Medicine", "Physical Medicine", "physical_therapy", 0.60, 0)
add("97545", "Work hardening/conditioning initial 2 hours", "Medicine", "Physical Medicine", "physical_therapy", 2.50, 0)
add("97546", "Work hardening/conditioning each additional hour add-on", "Medicine", "Physical Medicine", "physical_therapy", 1.00, 0, addon=True)
add("97550", "Caregiver training in use of assistive technology 15 min", "Medicine", "Physical Medicine", "physical_therapy", 0.60, 0)
add("97597", "Debridement open wound selective first 20 sq cm", "Medicine", "Physical Medicine", "physical_therapy", 1.50, 0)
add("97598", "Debridement open wound selective each additional 20 sq cm add-on", "Medicine", "Physical Medicine", "physical_therapy", 0.50, 0, addon=True)
add("97602", "Removal of devitalized tissue from wound non-selective", "Medicine", "Physical Medicine", "physical_therapy", 0.50, 0)
add("97605", "Negative pressure wound therapy surface area less than 50 sq cm", "Medicine", "Physical Medicine", "physical_therapy", 1.00, 0)
add("97606", "Negative pressure wound therapy surface area greater than 50 sq cm", "Medicine", "Physical Medicine", "physical_therapy", 1.30, 0)
add("97607", "Negative pressure wound therapy using disposable device less than 50 sq cm per day", "Medicine", "Physical Medicine", "physical_therapy", 0.30, 0)
add("97608", "Negative pressure wound therapy using disposable device greater than 50 sq cm per day", "Medicine", "Physical Medicine", "physical_therapy", 0.40, 0)
add("97750", "Physical performance test or measurement each 15 minutes", "Medicine", "Physical Medicine", "physical_therapy", 0.50, 0)
add("97755", "Assistive technology assessment each 15 minutes", "Medicine", "Physical Medicine", "physical_therapy", 0.50, 0)
add("97760", "Orthotic management and training initial encounter each 15 minutes", "Medicine", "Physical Medicine", "physical_therapy", 0.50, 0)
add("97761", "Prosthetic training initial encounter each 15 minutes", "Medicine", "Physical Medicine", "physical_therapy", 0.55, 0)
add("97763", "Orthotic/prosthetic management subsequent encounter each 15 minutes", "Medicine", "Physical Medicine", "physical_therapy", 0.45, 0)
add("97799", "Unlisted physical medicine/rehabilitation service or procedure", "Medicine", "Physical Medicine", "physical_therapy", 0.50, 0)

# ============================================================
# TRIGGER POINTS 20552-20553
# ============================================================
add("20552", "Injection single or multiple trigger point(s) 1 or 2 muscle(s)", "Surgery", "Musculoskeletal", "pain_management", 1.04, 0)
add("20553", "Injection single or multiple trigger point(s) 3 or more muscles", "Surgery", "Musculoskeletal", "pain_management", 1.30, 0)

# ============================================================
# ACUPUNCTURE 97810-97814
# ============================================================
add("97810", "Acupuncture 1 or more needles without electrical stimulation initial 15 minutes", "Medicine", "Physical Medicine", "acupuncture", 0.80, 0)
add("97811", "Acupuncture 1 or more needles without electrical stimulation each additional 15 min add-on", "Medicine", "Physical Medicine", "acupuncture", 0.70, 0, addon=True)
add("97813", "Acupuncture 1 or more needles with electrical stimulation initial 15 minutes", "Medicine", "Physical Medicine", "acupuncture", 0.90, 0)
add("97814", "Acupuncture 1 or more needles with electrical stimulation each additional 15 min add-on", "Medicine", "Physical Medicine", "acupuncture", 0.80, 0, addon=True)

# ============================================================
# CHIROPRACTIC 98940-98943
# ============================================================
add("98940", "Chiropractic manipulative treatment spinal 1-2 regions", "Medicine", "Physical Medicine", "chiropractic", 0.75, 0)
add("98941", "Chiropractic manipulative treatment spinal 3-4 regions", "Medicine", "Physical Medicine", "chiropractic", 1.00, 0)
add("98942", "Chiropractic manipulative treatment spinal 5 regions", "Medicine", "Physical Medicine", "chiropractic", 1.30, 0)
add("98943", "Chiropractic manipulative treatment extraspinal 1 or more regions", "Medicine", "Physical Medicine", "chiropractic", 0.50, 0)

# ============================================================
# SLEEP STUDIES 95782-95811
# ============================================================
add("95782", "Polysomnography younger than 6 years sleep staging with 4+ parameters", "Medicine", "Neurology", "sleep_medicine", 4.00, 0)
add("95783", "Polysomnography younger than 6 with CPAP or BiPAP", "Medicine", "Neurology", "sleep_medicine", 5.00, 0)
add("95800", "Sleep study unattended with heart rate oxygen saturation respiratory analysis", "Medicine", "Neurology", "sleep_medicine", 1.50, 0)
add("95801", "Sleep study unattended with minimum of heart rate oxygen saturation respiratory effort", "Medicine", "Neurology", "sleep_medicine", 1.80, 0)
add("95803", "Actigraphy testing recording analysis and interpretation minimum 3 days", "Medicine", "Neurology", "sleep_medicine", 0.50, 0)
add("95805", "Multiple sleep latency or maintenance of wakefulness testing", "Medicine", "Neurology", "sleep_medicine", 2.50, 0)
add("95806", "Sleep study unattended with airflow oxygen saturation respiratory effort and ECG", "Medicine", "Neurology", "sleep_medicine", 2.00, 0)
add("95807", "Sleep study simultaneous recording of ventilation respiratory effort ECG attended", "Medicine", "Neurology", "sleep_medicine", 4.50, 0)
add("95808", "Polysomnography any age sleep staging with 4+ parameters attended", "Medicine", "Neurology", "sleep_medicine", 4.20, 0)
add("95810", "Polysomnography age 6 or older sleep staging with 4+ parameters attended", "Medicine", "Neurology", "sleep_medicine", 4.00, 0)
add("95811", "Polysomnography age 6 or older sleep staging with CPAP or BiPAP attended", "Medicine", "Neurology", "sleep_medicine", 5.20, 0)

# ============================================================
# EEG 95812-95830
# ============================================================
add("95812", "Electroencephalogram extended monitoring 41-60 minutes", "Medicine", "Neurology", "neurology", 2.50, 0)
add("95813", "Electroencephalogram extended monitoring greater than 1 hour", "Medicine", "Neurology", "neurology", 3.00, 0)
add("95816", "Electroencephalogram including recording awake and asleep", "Medicine", "Neurology", "neurology", 1.50, 0)
add("95819", "Electroencephalogram including recording awake and asleep with sleep deprivation", "Medicine", "Neurology", "neurology", 2.00, 0)
add("95822", "Electroencephalogram recording in coma or sleep only", "Medicine", "Neurology", "neurology", 1.80, 0)
add("95824", "Electroencephalogram recording in cerebral death evaluation", "Medicine", "Neurology", "neurology", 2.00, 0)
add("95827", "Electroencephalogram all night recording", "Medicine", "Neurology", "neurology", 3.50, 0)
add("95829", "Electrocorticogram at surgery separate procedure", "Medicine", "Neurology", "neurology", 4.50, 0)
add("95830", "Insertion by physician of sphenoidal electrodes for EEG recording", "Medicine", "Neurology", "neurology", 1.50, 0)

# Additional EEG/neurodiagnostic
add("95700", "Electroencephalogram continuous recording with review and report each 24 hours", "Medicine", "Neurology", "neurology", 3.00, 0)
add("95711", "Electroencephalogram with video continuous monitoring 2-12 hours unmonitored", "Medicine", "Neurology", "neurology", 3.50, 0)
add("95712", "Electroencephalogram with video continuous monitoring 2-12 hours intermittent monitoring", "Medicine", "Neurology", "neurology", 4.00, 0)
add("95713", "Electroencephalogram with video continuous monitoring 2-12 hours continuous monitoring", "Medicine", "Neurology", "neurology", 5.00, 0)
add("95714", "Electroencephalogram with video each increment of 12-26 hours unmonitored", "Medicine", "Neurology", "neurology", 4.50, 0)
add("95715", "Electroencephalogram with video each increment of 12-26 hours intermittent monitoring", "Medicine", "Neurology", "neurology", 5.50, 0)
add("95716", "Electroencephalogram with video each increment of 12-26 hours continuous monitoring", "Medicine", "Neurology", "neurology", 6.50, 0)
add("95717", "Electroencephalogram with video each increment of greater than 26 hours unmonitored", "Medicine", "Neurology", "neurology", 5.00, 0)
add("95718", "Electroencephalogram with video each increment of greater than 26 hours intermittent", "Medicine", "Neurology", "neurology", 6.00, 0)
add("95719", "Electroencephalogram with video each increment of greater than 26 hours continuous", "Medicine", "Neurology", "neurology", 7.00, 0)
add("95720", "Electroencephalogram continuous recording with review and report maintenance", "Medicine", "Neurology", "neurology", 2.50, 0)

# ============================================================
# EMG/NCS 95907-95913
# ============================================================
add("95907", "Nerve conduction studies 1-2 studies", "Medicine", "Neurology", "neurology", 1.00, 0)
add("95908", "Nerve conduction studies 3-4 studies", "Medicine", "Neurology", "neurology", 1.50, 0)
add("95909", "Nerve conduction studies 5-6 studies", "Medicine", "Neurology", "neurology", 2.00, 0)
add("95910", "Nerve conduction studies 7-8 studies", "Medicine", "Neurology", "neurology", 2.50, 0)
add("95911", "Nerve conduction studies 9-10 studies", "Medicine", "Neurology", "neurology", 3.00, 0)
add("95912", "Nerve conduction studies 11-12 studies", "Medicine", "Neurology", "neurology", 3.50, 0)
add("95913", "Nerve conduction studies 13 or more studies", "Medicine", "Neurology", "neurology", 4.00, 0)
add("95860", "Needle electromyography 1 extremity with or without related paraspinal areas", "Medicine", "Neurology", "neurology", 1.50, 0)
add("95861", "Needle electromyography 2 extremities with or without related paraspinal areas", "Medicine", "Neurology", "neurology", 2.50, 0)
add("95863", "Needle electromyography 3 extremities with or without related paraspinal areas", "Medicine", "Neurology", "neurology", 3.20, 0)
add("95864", "Needle electromyography 4 extremities with or without related paraspinal areas", "Medicine", "Neurology", "neurology", 3.80, 0)
add("95865", "Needle electromyography larynx", "Medicine", "Neurology", "neurology", 2.00, 0)
add("95866", "Needle electromyography hemidiaphragm", "Medicine", "Neurology", "neurology", 1.50, 0)
add("95867", "Needle electromyography cranial nerve supplied muscle unilateral", "Medicine", "Neurology", "neurology", 1.20, 0)
add("95868", "Needle electromyography cranial nerve supplied muscles bilateral", "Medicine", "Neurology", "neurology", 2.00, 0)
add("95869", "Needle electromyography thoracic paraspinal muscles", "Medicine", "Neurology", "neurology", 1.00, 0)
add("95870", "Needle electromyography nonparaspinal limited study of muscles in 1 extremity", "Medicine", "Neurology", "neurology", 0.80, 0)
add("95872", "Needle electromyography using single fiber electrode", "Medicine", "Neurology", "neurology", 2.50, 0)
add("95885", "Needle electromyography each extremity limited study add-on", "Medicine", "Neurology", "neurology", 0.50, 0, addon=True)
add("95886", "Needle electromyography each extremity complete study add-on", "Medicine", "Neurology", "neurology", 1.00, 0, addon=True)
add("95887", "Needle electromyography nonextremity add-on", "Medicine", "Neurology", "neurology", 0.50, 0, addon=True)

# ============================================================
# ADDITIONAL SURGICAL PROCEDURES - Various specialties
# ============================================================

# Spine procedures (additional)
add("22551", "Arthrodesis anterior interbody cervical below C2", "Surgery", "Musculoskeletal", "orthopedics", 20.00, 90, asst=True)
add("22552", "Arthrodesis anterior interbody cervical each additional interspace add-on", "Surgery", "Musculoskeletal", "orthopedics", 6.00, 0, addon=True)
add("22554", "Arthrodesis anterior interbody including disc space preparation cervical", "Surgery", "Musculoskeletal", "orthopedics", 18.50, 90, asst=True)
add("22556", "Arthrodesis anterior interbody thoracic", "Surgery", "Musculoskeletal", "orthopedics", 22.00, 90, asst=True)
add("22558", "Arthrodesis anterior interbody lumbar", "Surgery", "Musculoskeletal", "orthopedics", 20.00, 90, asst=True)
add("22585", "Arthrodesis anterior interbody each additional interspace add-on", "Surgery", "Musculoskeletal", "orthopedics", 5.50, 0, addon=True)
add("22586", "Arthrodesis pre-sacral interbody L5-S1", "Surgery", "Musculoskeletal", "orthopedics", 22.00, 90, asst=True)
add("22590", "Arthrodesis posterior technique craniocervical", "Surgery", "Musculoskeletal", "orthopedics", 22.00, 90, asst=True)
add("22595", "Arthrodesis posterior technique atlas-axis", "Surgery", "Musculoskeletal", "orthopedics", 18.50, 90, asst=True)
add("22600", "Arthrodesis posterior or posterolateral technique single interspace cervical", "Surgery", "Musculoskeletal", "orthopedics", 16.00, 90, asst=True)
add("22610", "Arthrodesis posterior or posterolateral technique single interspace thoracic", "Surgery", "Musculoskeletal", "orthopedics", 16.50, 90, asst=True)
add("22612", "Arthrodesis posterior or posterolateral technique single interspace lumbar", "Surgery", "Musculoskeletal", "orthopedics", 18.00, 90, asst=True)
add("22614", "Arthrodesis posterior or posterolateral each additional interspace add-on", "Surgery", "Musculoskeletal", "orthopedics", 5.50, 0, addon=True)
add("22630", "Arthrodesis posterior interbody including laminectomy lumbar", "Surgery", "Musculoskeletal", "orthopedics", 20.50, 90, asst=True)
add("22632", "Arthrodesis posterior interbody each additional interspace add-on", "Surgery", "Musculoskeletal", "orthopedics", 6.00, 0, addon=True)
add("22633", "Arthrodesis combined posterior interbody and posterolateral lumbar", "Surgery", "Musculoskeletal", "orthopedics", 24.00, 90, asst=True)
add("22634", "Arthrodesis combined posterior interbody and posterolateral each additional add-on", "Surgery", "Musculoskeletal", "orthopedics", 6.50, 0, addon=True)

# Spinal instrumentation
add("22840", "Posterior non-segmental instrumentation", "Surgery", "Musculoskeletal", "orthopedics", 8.00, 0, addon=True)
add("22841", "Internal spinal fixation by wiring of spinous processes", "Surgery", "Musculoskeletal", "orthopedics", 6.00, 0, addon=True)
add("22842", "Posterior segmental instrumentation 3-6 vertebral segments", "Surgery", "Musculoskeletal", "orthopedics", 12.00, 0, addon=True)
add("22843", "Posterior segmental instrumentation 7-12 vertebral segments", "Surgery", "Musculoskeletal", "orthopedics", 14.00, 0, addon=True)
add("22844", "Posterior segmental instrumentation 13 or more vertebral segments", "Surgery", "Musculoskeletal", "orthopedics", 16.00, 0, addon=True)
add("22845", "Anterior instrumentation 2-3 vertebral segments", "Surgery", "Musculoskeletal", "orthopedics", 10.00, 0, addon=True)
add("22846", "Anterior instrumentation 4-7 vertebral segments", "Surgery", "Musculoskeletal", "orthopedics", 12.00, 0, addon=True)
add("22847", "Anterior instrumentation 8 or more vertebral segments", "Surgery", "Musculoskeletal", "orthopedics", 14.00, 0, addon=True)
add("22848", "Pelvic fixation add-on", "Surgery", "Musculoskeletal", "orthopedics", 6.50, 0, addon=True)
add("22849", "Reinsertion of spinal fixation device", "Surgery", "Musculoskeletal", "orthopedics", 12.00, 90, asst=True)
add("22850", "Removal of posterior nonsegmental instrumentation", "Surgery", "Musculoskeletal", "orthopedics", 8.00, 90)
add("22852", "Removal of posterior segmental instrumentation", "Surgery", "Musculoskeletal", "orthopedics", 10.00, 90, asst=True)
add("22853", "Insertion of interbody biomechanical device with integral anterior instrumentation", "Surgery", "Musculoskeletal", "orthopedics", 5.00, 0, addon=True)
add("22854", "Insertion of interbody biomechanical device with integral anterior instrumentation with 360", "Surgery", "Musculoskeletal", "orthopedics", 5.50, 0, addon=True)
add("22855", "Removal of anterior instrumentation", "Surgery", "Musculoskeletal", "orthopedics", 12.00, 90, asst=True)
add("22856", "Total disc arthroplasty anterior approach single interspace cervical", "Surgery", "Musculoskeletal", "orthopedics", 20.00, 90, asst=True)
add("22857", "Total disc arthroplasty anterior approach single interspace lumbar", "Surgery", "Musculoskeletal", "orthopedics", 22.00, 90, asst=True)
add("22858", "Total disc arthroplasty second level cervical add-on", "Surgery", "Musculoskeletal", "orthopedics", 8.00, 0, addon=True)
add("22859", "Interspinous process stabilization device", "Surgery", "Musculoskeletal", "orthopedics", 6.00, 0, addon=True)

# Additional E/M codes
add("99201", "Office or other outpatient visit new patient minimal", "E/M", "Office Visit", "primary_care", 0.48, 0)
add("99241", "Office or other outpatient consultation new or established level 1", "E/M", "Consultation", "primary_care", 0.64, 0)
add("99242", "Office or other outpatient consultation level 2", "E/M", "Consultation", "primary_care", 1.28, 0)
add("99243", "Office or other outpatient consultation level 3", "E/M", "Consultation", "primary_care", 1.90, 0)
add("99244", "Office or other outpatient consultation level 4", "E/M", "Consultation", "primary_care", 2.88, 0)
add("99245", "Office or other outpatient consultation level 5", "E/M", "Consultation", "primary_care", 3.77, 0)
add("99251", "Inpatient or observation consultation level 1", "E/M", "Consultation", "primary_care", 0.64, 0)
add("99252", "Inpatient or observation consultation level 2", "E/M", "Consultation", "primary_care", 1.32, 0)
add("99253", "Inpatient or observation consultation level 3", "E/M", "Consultation", "primary_care", 1.98, 0)
add("99254", "Inpatient or observation consultation level 4", "E/M", "Consultation", "primary_care", 2.96, 0)
add("99255", "Inpatient or observation consultation level 5", "E/M", "Consultation", "primary_care", 3.94, 0)
add("99281", "Emergency department visit level 1", "E/M", "Emergency", "emergency_medicine", 0.45, 0)
add("99282", "Emergency department visit level 2", "E/M", "Emergency", "emergency_medicine", 0.88, 0)
add("99283", "Emergency department visit level 3", "E/M", "Emergency", "emergency_medicine", 1.42, 0)
add("99284", "Emergency department visit level 4", "E/M", "Emergency", "emergency_medicine", 2.56, 0)
add("99285", "Emergency department visit level 5", "E/M", "Emergency", "emergency_medicine", 3.80, 0)
add("99288", "Physician direction of emergency medical systems", "E/M", "Emergency", "emergency_medicine", 1.39, 0)

# Critical care
add("99291", "Critical care evaluation and management first 30-74 minutes", "E/M", "Critical Care", "critical_care", 4.50, 0)
add("99292", "Critical care each additional 30 minutes add-on", "E/M", "Critical Care", "critical_care", 2.25, 0, addon=True)

# Nursing facility
add("99304", "Nursing facility care initial comprehensive level 1", "E/M", "Nursing Facility", "primary_care", 2.00, 0)
add("99305", "Nursing facility care initial comprehensive level 2", "E/M", "Nursing Facility", "primary_care", 2.50, 0)
add("99306", "Nursing facility care initial comprehensive level 3", "E/M", "Nursing Facility", "primary_care", 3.00, 0)
add("99307", "Nursing facility subsequent care level 1", "E/M", "Nursing Facility", "primary_care", 0.80, 0)
add("99308", "Nursing facility subsequent care level 2", "E/M", "Nursing Facility", "primary_care", 1.10, 0)
add("99309", "Nursing facility subsequent care level 3", "E/M", "Nursing Facility", "primary_care", 1.40, 0)
add("99310", "Nursing facility subsequent care level 4", "E/M", "Nursing Facility", "primary_care", 2.00, 0)
add("99315", "Nursing facility discharge management 30 min or less", "E/M", "Nursing Facility", "primary_care", 1.28, 0)
add("99316", "Nursing facility discharge management more than 30 min", "E/M", "Nursing Facility", "primary_care", 1.90, 0)

# Home services
add("99341", "Home visit new patient level 1", "E/M", "Home Services", "primary_care", 1.00, 0)
add("99342", "Home visit new patient level 2", "E/M", "Home Services", "primary_care", 1.60, 0)
add("99343", "Home visit new patient level 3", "E/M", "Home Services", "primary_care", 2.15, 0)
add("99344", "Home visit new patient level 4", "E/M", "Home Services", "primary_care", 3.00, 0)
add("99345", "Home visit new patient level 5", "E/M", "Home Services", "primary_care", 3.75, 0)
add("99347", "Home visit established patient level 1", "E/M", "Home Services", "primary_care", 0.76, 0)
add("99348", "Home visit established patient level 2", "E/M", "Home Services", "primary_care", 1.25, 0)
add("99349", "Home visit established patient level 3", "E/M", "Home Services", "primary_care", 1.90, 0)
add("99350", "Home visit established patient level 4", "E/M", "Home Services", "primary_care", 2.80, 0)

# Preventive medicine
add("99381", "Preventive visit new patient infant age under 1 year", "E/M", "Preventive", "primary_care", 1.50, 0)
add("99382", "Preventive visit new patient age 1-4", "E/M", "Preventive", "primary_care", 1.55, 0)
add("99383", "Preventive visit new patient age 5-11", "E/M", "Preventive", "primary_care", 1.50, 0)
add("99384", "Preventive visit new patient age 12-17", "E/M", "Preventive", "primary_care", 1.60, 0)
add("99385", "Preventive visit new patient age 18-39", "E/M", "Preventive", "primary_care", 1.50, 0)
add("99386", "Preventive visit new patient age 40-64", "E/M", "Preventive", "primary_care", 1.70, 0)
add("99387", "Preventive visit new patient age 65 and older", "E/M", "Preventive", "primary_care", 1.80, 0)
add("99391", "Preventive visit established patient infant age under 1 year", "E/M", "Preventive", "primary_care", 1.30, 0)
add("99392", "Preventive visit established patient age 1-4", "E/M", "Preventive", "primary_care", 1.35, 0)
add("99393", "Preventive visit established patient age 5-11", "E/M", "Preventive", "primary_care", 1.30, 0)
add("99394", "Preventive visit established patient age 12-17", "E/M", "Preventive", "primary_care", 1.40, 0)
add("99395", "Preventive visit established patient age 18-39", "E/M", "Preventive", "primary_care", 1.30, 0)
add("99396", "Preventive visit established patient age 40-64", "E/M", "Preventive", "primary_care", 1.50, 0)
add("99397", "Preventive visit established patient age 65 and older", "E/M", "Preventive", "primary_care", 1.60, 0)

# Care management
add("99490", "Chronic care management services first 20 minutes per month", "E/M", "Care Management", "primary_care", 0.61, 0)
add("99491", "Chronic care management services first 30 minutes per month by physician", "E/M", "Care Management", "primary_care", 1.50, 0)
add("99439", "Chronic care management services each additional 20 minutes per month add-on", "E/M", "Care Management", "primary_care", 0.54, 0, addon=True)
add("99487", "Complex chronic care management first 60 minutes per month", "E/M", "Care Management", "primary_care", 1.00, 0)
add("99489", "Complex chronic care management each additional 30 minutes per month add-on", "E/M", "Care Management", "primary_care", 0.50, 0, addon=True)
add("99495", "Transitional care management moderate complexity", "E/M", "Care Management", "primary_care", 2.11, 0)
add("99496", "Transitional care management high complexity", "E/M", "Care Management", "primary_care", 3.05, 0)
add("99497", "Advance care planning first 30 minutes", "E/M", "Care Management", "primary_care", 1.50, 0)
add("99498", "Advance care planning each additional 30 minutes add-on", "E/M", "Care Management", "primary_care", 1.40, 0, addon=True)

# Prolonged services
add("99354", "Prolonged service office direct patient contact first hour", "E/M", "Office Visit", "primary_care", 2.10, 0)
add("99355", "Prolonged service office direct patient contact each additional 30 min add-on", "E/M", "Office Visit", "primary_care", 2.00, 0, addon=True)
add("99356", "Prolonged service inpatient direct patient contact first hour", "E/M", "Hospital", "primary_care", 2.10, 0)
add("99357", "Prolonged service inpatient each additional 30 min add-on", "E/M", "Hospital", "primary_care", 2.00, 0, addon=True)
add("99358", "Prolonged service without direct patient contact first hour", "E/M", "Office Visit", "primary_care", 2.10, 0)
add("99359", "Prolonged service without direct patient contact each additional 30 min add-on", "E/M", "Office Visit", "primary_care", 2.00, 0, addon=True)

# Newborn care
add("99460", "Initial hospital or birthing center care per day for normal newborn", "E/M", "Newborn", "pediatrics", 1.48, 0)
add("99461", "Initial care per day for normal newborn admitted and discharged same day", "E/M", "Newborn", "pediatrics", 1.50, 0)
add("99462", "Subsequent hospital care per day for normal newborn", "E/M", "Newborn", "pediatrics", 0.62, 0)
add("99463", "Same day admit and discharge for normal newborn", "E/M", "Newborn", "pediatrics", 1.50, 0)
add("99464", "Attendance at delivery and initial stabilization of newborn", "E/M", "Newborn", "pediatrics", 2.00, 0)
add("99465", "Delivery/birthing room resuscitation", "E/M", "Newborn", "pediatrics", 3.00, 0)
add("99468", "Initial inpatient neonatal critical care per day age 28 days or younger", "E/M", "Critical Care", "neonatology", 18.50, 0)
add("99469", "Subsequent inpatient neonatal critical care per day age 28 days or younger", "E/M", "Critical Care", "neonatology", 8.00, 0)
add("99471", "Initial inpatient pediatric critical care per day age 29 days through 24 months", "E/M", "Critical Care", "pediatrics", 16.00, 0)
add("99472", "Subsequent inpatient pediatric critical care per day age 29 days through 24 months", "E/M", "Critical Care", "pediatrics", 7.50, 0)
add("99475", "Initial inpatient pediatric critical care per day age 2-5 years", "E/M", "Critical Care", "pediatrics", 14.00, 0)
add("99476", "Subsequent inpatient pediatric critical care per day age 2-5 years", "E/M", "Critical Care", "pediatrics", 7.00, 0)
add("99477", "Initial hospital care per day for neonatal 28 days or younger not critically ill", "E/M", "Newborn", "neonatology", 4.00, 0)
add("99478", "Subsequent intensive care per day for recovering very low birth weight infant", "E/M", "Critical Care", "neonatology", 3.00, 0)
add("99479", "Subsequent intensive care per day for recovering low birth weight infant 1500-2500g", "E/M", "Critical Care", "neonatology",